### ISSUE TITLE
Missing Family Options

### ISSUE THREAD

**Issue by ghost** [yeti-platform/yeti#100]
### Description
The options for family are not there. Also I can not copy/paste or click/drag images into descriptions. Adding both in here as they feel related, perhaps a permission issue?

### Environment
| Question         | Answer
|------------------|--------------------
| Git commit       | 83b9d23370c13f29ae730da0d4632dfdd61d7aac
| OS version       | Ubuntu 1.04
| Browser          | Chrome 59.0.3071.86

### Steps to Reproduce
1. Open malware entity to edit
2. Click and note no options in "family"

1. Edit malware entity
2. click and drag image from desktop into edit box
3. shows uploading, then disappears
4. no image is uploaded

#### Expected behavior
-Pre-filled family options to be presented. 
-Image added to description

#### Actual behavior
-No options in family
-No image uploaded via copy/past or click/drag

**Comment by gamelinux** [comment]
I think you need to add families names first, but there is now option in the GUI to do so.
IIRC, I might have seen family names in my first install when I imported all the feeds? Maybe you can add family names through code for now as a quick fix. I see that there might be some hints here on how to do it: plugins/feeds/public/malwareconfig.py

**Comment by tomchop** [comment]
Poking @gaelmuller as the local image adding should've been fixed in #97.

As for the malware families, they have to be populated manually from the database. We realize this is far from ideal, and we should offer the option for users to populate them themselves.

**Comment by antwanvanderstap** [comment]
Quite new to Yeti and liking very much what I see ... I stumbled on this same issue. Has anyone found a work-around or is there a fix?
