### ISSUE TITLE
Top domains feed

### ISSUE THREAD

**Issue by udgover** [yeti-platform/yeti#1005]
I would like to ingest top domains list and tag them as allow_list for example in order to automatically remove them from export feeds. There was AlexaTop1M which no longer exists. However Cloudflare is providing different list of [Top domains](https://radar.cloudflare.com/domains). 

Since there are several feeds depending on the number of the domain, the feed needs to support a configuration that would define the number of domains to import.

![Screenshot 2024-02-05 at 11 31 26](https://github.com/yeti-platform/yeti/assets/1006203/6c6ad033-4351-4234-95bb-4166506fc58e)

**Comment by tomchop** [comment]
Have a look at the `_default_values` dict. This could be used to store dynamic configs (ie. editable from the UI), but maybe a hardocded limit in the yeti.conf file is enough for this.
