### ISSUE TITLE
Private report

### ISSUE THREAD

**Issue by Sim4n6** [yeti-platform/yeti#1014]
Just checking if any update on this privately submitted report https://github.com/yeti-platform/yeti/security/advisories/GHSA-cwwm-pq9x-2cxv please notice no notifications are received via the GitHub mobile app and only the collaborators (maintainers & owners) have access to the report.

**Comment by Sim4n6** [comment]
poke @tomchop ... ?

**Comment by tomchop** [comment]
Hey @Sim4n6! We've received your report, thanks a lot! We'll get around to fix it when time permits. I'm closing this issue in favor of the one in the Security section.

**Comment by Sim4n6** [comment]
Perfecr
