### ISSUE TITLE
Feature Request: Feeds quality control features

### ISSUE THREAD

**Issue by trolldbois** [yeti-platform/yeti#102]
When one has access to "paying" feeds, it becomes important to be able to "rate" the feed quality, and be able to pitch them against each-other.

Example of quality control metrics:
 - False positive counts per period (it happens)
 - Overlapping indicators between feeds (a la MISP http://www.misp-project.org/2017/05/09/MISP.2.4.73.released.html )

Request is a bit similar to #40

**Comment by WArurrt** [comment]
+1!

**Comment by tomchop** [comment]
I would like to implement views that can help an analyst have a better view of what the feed is providing. This would include something like:

* **Timeliness**: which feed is the "first" to include a given observable
* **Uniqueness**: which feed provides the most unique observables (this would amount to the overlap matrix)
* **Freshness**: how long do indicators stay in a given feed? How are they deprecated?
* **Usefulness**: how often does an analyst search for an observable that's in a given feed?
* **Contextual relevance**: How often does your constituency hit observables that are in those feeds?

Any other ideas?

**Comment by soulsf** [comment]
+1

**Comment by tomchop** [comment]
OK, I feel like we should actually go ahead and do this. I'll see if I can find someone who's interested in starting to build something for it.
