### ISSUE TITLE
Service frontend has neither an image nor a build context specified. At least one must be provided.

### ISSUE THREAD

**Issue by aceraulo** [yeti-platform/yeti#1025]
Hello, 

I've followed the guide to set up Yeti https://yeti-platform.io/docs/getting-started/, but every time i try to do docker-compose up it returns me the following error "Service frontend has neither an image nor a build context specified. At least one must be provided."

I've tried to do docker compose up but it returns me the error "docker: 'compose' is not a docker command."

### Environment

| Question                  | Answer
|---------------------------|--------------------
| Yeti release              | 3.3
| Yeti-frontend release     |
| OS version                | Ubuntu 22.04
| Browser                   | Chrome 119.0.6045.123

**Comment by tomchop** [comment]
If you managed to solve this, could you share how? I've never run into this error before, but it might be useful for other people running into it :)

**Comment by fl0wc0ntr0l** [comment]
@tomchop This is due to a mismatched version of docker-compose; try installing Docker from their official repos as opposed to the unofficial versions from whichever distribution you are using.

**Comment by tomchop** [comment]
If you follow the official docker instructions (here: https://docs.docker.com/engine/install/debian/), you'll end up with the latest version of the `docker compose` plugin, which is invoked via `docker compose` and not `docker-compose` (that's a legacy version, the one you were using).
