### ISSUE TITLE
Interface appears broken now

### ISSUE THREAD

**Issue by DigiAngel** [yeti-platform/yeti#103]
### Description
Interface appears broken

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 6ef77452d1aeb3fa0b08824011ac366b2d450c25
| OS version       | Debian
| Browser          | Chrome 59.0.3071.104

### Steps to Reproduce
1. git pull

#### Expected behavior
Same interface

#### Actual behavior
Something appears off..
![2017-06-21 11_53_31-users - yeti](https://user-images.githubusercontent.com/947191/27399577-78386e90-567a-11e7-9c42-ff5666f02bcc.png)

**Comment by DigiAngel** [comment]
![screenshot from 2017-06-21 13-00-30](https://user-images.githubusercontent.com/947191/27401778-aa161bae-5681-11e7-9cb7-eb0a2d3d1824.png)

**Comment by gaelmuller** [comment]
Frontend dependencies are now managed with yarn.

You have to install yarn first (see https://yarnpkg.com/en/docs/install for instructions), and then fetch the dependencies:

```
yeti $ yarn install
```

**Comment by DigiAngel** [comment]
Thanks that fixed it up.
