### ISSUE TITLE
The "All" option to display all items per page does not work in the "Observables" page.

### ISSUE THREAD

**Issue by y0sh1mitsu** [yeti-platform/yeti#1037]
### Description

Hi guys, when I want to see all the items on the "Observables" page, the "All" option doesn't work and displays the last option chosen. And if you keep it, the results of a new search won't be displayed dynamically; you have to click on display on 10 items, for example, for the results to be displayed.

### Environment

| Question                  | Answer
|---------------------------|--------------------
| Yeti release              | Yeti 2.1.4
| Yeti-frontend release     | Yeti Frontend 2.1.4
| OS version                | WSL - Ubuntu 22.04.3 LTS
| Browser                   | Firefox Version 123.0.1

### Steps to Reproduce

- Mount the docker on the latest release
- Populate "Observables" with public feeds for example
- And go to the Observable page and click on the "All" option
- Leave the "All" option and try a new search

#### Expected behavior

That the "All" option lists all the Observables on a page and a search is automatically displayed even if the "All" option is activated.

#### Actual behavior
![Screenshot](https://github.com/yeti-platform/yeti/assets/62485373/03408d53-a6ea-4a55-871a-34bf88649c04)

**Comment by tomchop** [comment]
Thanks for the heads up, we'll look into it. Just so we know, we're planning to remove the `All` option because it would be too expensive for servers to return the massive amount of observables they might gather over time (and also for your browser to render it, probably). What would a reasonable upper bound be for your use-case?

**Comment by tomchop** [comment]
Closing this in favor of https://github.com/yeti-platform/yeti-feeds-frontend/issues/156
