### ISSUE TITLE
Update broke UI

### ISSUE THREAD

**Issue by WArurrt** [yeti-platform/yeti#104]
### Description
After updating to the latest release, the UI no longer functions as intended (see screenshot). Any thoughts on what I did to break it? 

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 3715dfe8ed55c88df82fe53e8bf6deada871536a
| OS version       | Ubuntu 14.04
| Browser          | Chrome 59.0.3071.109

### Steps to Reproduce
1. Navigate to /home/yeti/yeti/
2. git pull
3. ./yeti.py syncdb
4. Reboot host
5. Login

#### Expected behavior
Expect the UI to appear as intended

#### Actual behavior
UI appears to lack formatting and other visual configurations. 

![screen shot 2017-06-26 at 9 46 44 am](https://user-images.githubusercontent.com/29357661/27548210-85ae793c-5a55-11e7-87f7-7de655491197.png)

**Comment by gaelmuller** [comment]
Please see https://github.com/yeti-platform/yeti/issues/103 for explanations.

**Comment by WArurrt** [comment]
That was it - thanks for the fwd!
