### ISSUE TITLE
Feed task - mongo - unlock all feed on task (re)start

### ISSUE THREAD

**Issue by trolldbois** [yeti-platform/yeti#109]
### Description
When the feed task is stopped abruptly, any running feeds will be freezed in a locked state and will not run after task/service restart

### Steps to Reproduce
1. run the Feed task, with a Feed A that take a few minutes to run (parsing, transform...)
2. kill/stop the Feed Task/celery workers
3. Mongo DB task show a lock task 
4. restart Feed task
5. observe that that Feed A will never be run ever again.

#### Expected behavior
All Feed status should be reset after celery worker restart.

#### Actual behavior
Feed state is not changed.

see lock: true
$ mongo
> use yeti
> db.schedule_entry.find({_id: ObjectId("595999999999999b5cbc")})
{ "_id" : ObjectId("595999999999999b5cbc"), "_cls" : "ScheduleEntry.Feed.PrivateFeedName", "name" : "ThreatInsight", "enabled" : true, "description" : "This feed contains super secret feed information that takes a bit of time to process from the data source", "frequency" : 3600, "lock" : true, "source" : "https://supersecret.private.local", "status" : "Updating...", "last_run" : ISODate("2017-07-13T19:21:47.902Z") }

**Comment by tomchop** [comment]
Thanks for the bug report. We're aware of this and we're working on a foolproof solution to keep this from happening. One way would be to programatically launch the celery workers after having unlocked the corresponding feeds the workers will ingest.

**Comment by tomchop** [comment]
Fixed in #137
