### ISSUE TITLE
Omit sensitive fields from logging

### ISSUE THREAD

**Issue by tomchop** [yeti-platform/yeti#1113]
Some sensitive fields should be exempt from logging. 

As seen in https://github.com/yeti-platform/yeti/pull/1111, if we want to be precise, this requires a bit more thought than just parsing the JSON body of the request. Pydantic offers a potentially useful mechanism, https://docs.pydantic.dev/2.0/usage/types/secrets/.

**Comment by udgover** [comment]
Fixed in https://github.com/yeti-platform/yeti/pull/1151
