### ISSUE TITLE
Search does not work with special character

### ISSUE THREAD

**Issue by udgover** [yeti-platform/yeti#1117]
When looking for observables of type command line containing special characters, the search does not return results. It also impacts running analytics on these observable.

After investigating, method `filter` in `ArangoYetiConnector` class is adding REGEX conditions which requires to escape all special characters.  Replacing this [condition](https://github.com/yeti-platform/yeti/blob/main/core/database_arango.py#L835) with `conditions.append(f"(CONTAINS(o.@arg{i}_key, @arg{i}_value) OR REGEX_TEST(o.@arg{i}_key, @arg{i}_value, true))")` will work for all cases.

The question is, do we want to replace all occurrences of the faulty condition with the suggested ones or should we provide a regex operator in search?

**Comment by tomchop** [comment]
This should be fixed in https://github.com/yeti-platform/yeti/pull/1118, can you double check?
