### ISSUE TITLE
default_tag_expiration from yeti.conf not used

### ISSUE THREAD

**Issue by 0xRet** [yeti-platform/yeti#1145]
### Description

In yeti.conf.sample we can find a `default_tag_expiration` variable. 
This variable seems to not be used elsewhere.

#### Expected behavior
This variable should replace the default value `DEFAULT_EXPIRATION` specified in core/schemas/tag.py

#### Actual behavior
Only `DEFAULT_EXPIRATION` is used.

**Comment by mbonino** [comment]
https://github.com/yeti-platform/yeti/pull/1147 should fix the issue.

**Comment by udgover** [comment]
Fixed by https://github.com/yeti-platform/yeti/pull/1147
