### ISSUE TITLE
Sources of observables are not always correctly defined

### ISSUE THREAD

**Issue by pstirparo** [yeti-platform/yeti#116]
Not sure if it is me not finding it or if I can label this as feature request.

When going to the menu "Observable--> Browse" would be good to have a column reporting the source of each observable.

This applies also to the observable page itself: in the "info" box on the top left corner, a "source" field would be good to have.
Thanks
P.

**Comment by gaelmuller** [comment]
Observables already have a "sources" field that is displayed in the "info" box when set. It seems however that sources are not always correctly set.

We will keep this issue open in order to remember that.

**Comment by tomchop** [comment]
@gaelmuller: Can you think of any examples where sources are not correctly set?
