### ISSUE TITLE
Define returned value for all API endpoints

### ISSUE THREAD

**Issue by udgover** [yeti-platform/yeti#1161]
Several endpoints in API does not define returned value: 

https://github.com/yeti-platform/yeti/blob/526caf6597f6e817ddedbaee44d5d9d94826c84d/core/web/apiv2/auth.py#L240-L243

**Comment by daisukixci** [comment]
FTR this forces us to cast responses in Go client generated code https://github.com/yeti-platform/goyeti/pull/2/files#diff-61330c731aebd1271b4a203118e856e8b0224baa8a4bc536b188081f33dd393aR33
