### ISSUE TITLE
Feature Request: MISP galaxies feed

### ISSUE THREAD

**Issue by pstirparo** [yeti-platform/yeti#117]
Hi,
It would be useful to be have a sort of "centralized" aliases db that you set once and the connection remains, like the MISP galaxies.

So, if I create a new Actor "Sofacy", and another user searches for "APT28", he can find my entry.

**Comment by adulau** [comment]
We might work soon on a PyGalaxy just like [PyTaxonomies](https://github.com/MISP/PyTaxonomies) like that other projects using Python can easily reuse it without the need to write a parser.

**Comment by trolldbois** [comment]
Some raw data from MITRE https://attack.mitre.org/wiki/Category:Group

**Comment by gaelmuller** [comment]
YETI already supports aliases on Threat Actors. If you want them to be populated automatically from some source, it should probably be in a feed.
