### ISSUE TITLE
Exports feeds not loaded in celery beat

### ISSUE THREAD

**Issue by Heat-Miser** [yeti-platform/yeti#118]
### Description
It appears that the exports feeds are not loaded in the celery beat modules to execute.

Consequences: the exports feeds are not generated.

### Environment

yeti up to date: commit 6fa959b78e5a473587ceef47df2d7fd447dbcaac

### Steps to Reproduce
All the feeds / analytics & cie are executed in due time except export feeds which are no more generated.

**Comment by gaelmuller** [comment]
Should be fixed, can you confirm ?

**Comment by Heat-Miser** [comment]
I confirm it works ! Thanks !
