### ISSUE TITLE
Actor and Campaign (and other Entities) cannot have the same name

### ISSUE THREAD

**Issue by trolldbois** [yeti-platform/yeti#120]
### Description
Actor and Campaign (and other Entities) cannot have the same name

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | aea12b5c92814ad3337c0e8da1b19a2d4b4135cb
| OS version       | Ubuntu 16.04.2

### Steps to Reproduce

    >>> Actor.get_or_create(name="Naikon")
    <Actor: Naikon>
    >>> Campaign.get_or_create(name="Naikon-Campaign")
    <Campaign: Naikon-Campaign>
    >>> Campaign.get_or_create(name="Naikon")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "core/database.py", line 77, in get_or_create
        return cls.objects.get(name=obj.name)
      File "/var/www/yeti/py2_yeti/local/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 277, in get
        raise queryset._document.DoesNotExist(msg)
    core.entities.campaign.DoesNotExist: Entity.Campaign matching query does not exist.

#### Expected behavior
>>> Actor.get_or_create(name="Naikon")
<Actor: Naikon>
>>> Campaign.get_or_create(name="Naikon")
<Campaign: Naikon>

#### Actual behavior
>>> Actor.get_or_create(name="Naikon")
<Actor: Naikon>
>>> Campaign.get_or_create(name="Naikon-Campaign")
<Campaign: Naikon-Campaign>
>>> Campaign.get_or_create(name="Naikon")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "core/database.py", line 77, in get_or_create
    return cls.objects.get(name=obj.name)
  File "/var/www/yeti/py2_yeti/local/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 277, in get
    raise queryset._document.DoesNotExist(msg)
core.entities.campaign.DoesNotExist: Entity.Campaign matching query does not exist.

**Comment by gaelmuller** [comment]
I think we could remove the uniqueness constraint, not sure it brings anything.

@tomchop what do you think ?

**Comment by tomchop** [comment]
Yes I'm pretty sure we could, or at the very least couple the uniqueness constraint with the Entity type so as to have unique `(name, type)` values.

That said, semantically does it make sense to have e.g. an "APT28" actor AND an "APT28" campaign?
