### ISSUE TITLE
Feature Request: Non-Mongo Version

### ISSUE THREAD

**Issue by a5m0** [yeti-platform/yeti#123]
Just wondering if there are any thoughts about the feasibility of a non-mongo version of yeti. I've briefly looked through the source and it appears to be a very non-abstracted integration of MongoDB.

**Comment by tomchop** [comment]
This is something we're actively working on. As you said, the code is not very abstracted from mongo which means there's still a lot of work to be done... we are considering ElastiSearch as an alternative backend.

**Comment by a5m0** [comment]
Awesome! Can I help?

**Comment by tomchop** [comment]
@a5m0: Any help is welcome:

* Finding the best way to structure ES5 database queries to maintain current functionality
* Eventual performance improvements
* Testing, testing, testing!

**Comment by ameygat** [comment]
@tomchop Ping me if need to do ES based testing.
