### ISSUE TITLE
Problem with "openphish" feed

### ISSUE THREAD

**Issue by Heat-Miser** [yeti-platform/yeti#126]
### Description
I think there is a "size" problem with OpenPhish feed

ERROR updating feed: Could not save document (WiredTigerIndex::insert: key too large to index, failing 1035 { : "http://www.buldru.434.com1.ru/sites/default/clfiles/wp-includesing/ccdetails.php?SIgY2xhc3M9ImxibHVlSGVhZGVyIj4mbmJzcDs8L3RkPg0KICAgICAgICAgICAgICAgID..." })

**Comment by tomchop** [comment]
Are you still getting this?

**Comment by knutern007** [comment]
Just installed and got this:

> ERROR updating feed: Could not save document (insertDocument :: caused by :: 17280 Btree::insert: key too large to index, failing yeti.observable.$value_1 1033 { : "http://biokamakozmetik.com/afstandsbediening/7465081bb39f1b9008a04f0aab7cf78aa9cf91.php?52.91.94.56&ix2304=dbec8addaddea4290745b924d3f43f2824710322032..." })
