### ISSUE TITLE
Static Files Missing

### ISSUE THREAD

**Issue by airlinedev** [yeti-platform/yeti#130]
Flask frontend static directory and files are missing. For example, jquery and bootstrap css are missing from the git repo. If this is intended, could someone please provide a documentation update?

**Comment by gaelmuller** [comment]
Frontend dependencies are managed with yarn. Running `yarn install` in your code repository should fetch all these dependencies.

This should be specified in the documentation. If not, could you point to the documentation section that should be improved ?

**Comment by airlinedev** [comment]
Ah, it looks like it's in the full documentation. I was going with the quick and dirty install on the github main page. Thank you!
