### ISSUE TITLE
Create New investigation / Add to existing from browse view

### ISSUE THREAD

**Issue by tomchop** [yeti-platform/yeti#131]
It would be nice to be able to create a new investigation from observables in the "browse" view (i.e. after a filter is set or a few lines are selected)

**Comment by gamelinux** [comment]
![browserview](https://user-images.githubusercontent.com/53898/29820793-f040b86c-8cc5-11e7-9eef-c1f9c363be09.png)

Searching for "tags=something" and selecting (clicking) on the some or all of the returned matches would be good for kicking of an investigation with more than one node.

This would make things way faster and efficient in cases where the nodes are not directly linked, so you cant enrich your way to having all nodes in the graph. Entering more than a few nodes manually is boring and time consuming, and should be avoided.

(Importing more than one node to an existing graph is also something to consider in another issue)

**Comment by axpatito** [comment]
+1
