### ISSUE TITLE
Selection is cleared when switching pages

### ISSUE THREAD

**Issue by tomchop** [yeti-platform/yeti#132]
The observable selection seems to be cleared when switching pages in the result set.

**Comment by gamelinux** [comment]
![browserview-select](https://user-images.githubusercontent.com/53898/29821173-456e1cfc-8cc7-11e7-8523-7b72dc0c192b.png)

When selecting a set of "values" returned in a search (does not need to be from a search), moving to another page to find more values to select will clear out the all ready selected values from previous page(s). Preferably they would be remembered, and that you could start an investigation or export them all in one go.
