### ISSUE TITLE
Unable to use search using created date parameter

### ISSUE THREAD

**Issue by ameygat** [yeti-platform/yeti#136]
### Description

I need to get observable created in a certain datetime range
I Tried searching 

created="2017-09-08T13:53:44.138000"
created=2017-09-08T13:53:44.138000
created=2017-09-08

The documentation at http://yeti-platform.readthedocs.io do not have any details about which fields can be used in search. 

Please provide help in finding list of attirbutes with sample search uses.

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       |commit 6fa959b78e5a473587ceef47df2d7fd447dbcaac
| OS version       | Ubuntu 16.04
| Browser          | Firefox 55.0.3 (32-bit)

### Steps to Reproduce
Enter any date in search field of observables

#### Expected behavior
I am expecting to get observables created on certain date

#### Actual behavior
Not getting any output

**Comment by tomchop** [comment]
I'll have to check if this is a bug or a lack in the documentation. Thanks for reporting.

**Comment by bradleykite** [comment]
Hi there,
I have also been trying to create filters based on the created date of an observable. For example, I'd like to use the API (/api/observablesearch/) to fetch a list of observables created since a specific date.

I'm still trying to get familiar with the code but have not been able to see where different operators can be used - eg instead of created=2017-09-08 I'd like to say created>2017-09-08 - it looks like an array of key/value pairs are passed as a JSON filter, but the operator is always '=' so it might not be possible to filter on created date?

**Comment by tomchop** [comment]
You need to pass parameters using the mongoengine / django syntax for queries (details [here](http://docs.mongoengine.org/guide/querying.html#query-operators))

Some examples:

* `created__gt=2017-09-09` 
* `created__lt=2017-09-10`

@ameygat this also works in the web interface.

**Comment by bradleykite** [comment]
Hi,

Thats very useful, thanks I can now use created__gt and thats fine.

I am trying to also select specific tags though - and this is causing an error:

results = api.observable_search(count=50, offset=page, regex=False, tag=tag["name"], created__gt=mtimestamp)

This creates the following HTTP request:

```
POST /api/observablesearch/ HTTP/1.1
Host: localhost:5000
Content-Length: 123
Accept-Encoding: gzip, deflate
Accept: application/json
User-Agent: python-requests/2.6.0 CPython/2.7.5 Linux/3.10.0-514.26.2.el7.x86_64
Connection: keep-alive
Content-Type: application/json

{"filter": {"tag": "aar", "created__gt": "2017-10-02T12:11:06.499201"}, "params": {"regex": false, "range": 50, "page": 1}}
```
But this fails with 
```
HTTP/1.0 400 BAD REQUEST
```

If I remove either the tag or the created__gt parameter then the search works correctly, but I need to filter on both.

Do you know if this is possible?

Thanks
--
Brad.

**Comment by tomchop** [comment]
You're using the wrong key, try `tags__name` instead of `tag`.

E.g. `results = api.observable_search(count=50, offset=page, regex=False, tags__name=tag["name"], created__gt=mtimestamp)`
