### ISSUE TITLE
Internal server error when attaching file to actor

### ISSUE THREAD

**Issue by bkime** [yeti-platform/yeti#143]
### Description
Error encountered when attempting to attach a file to an actor. 

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 6c8e1e5732637678c68137b4229554fa3363935c
| OS version       | RedHat 7.3
| Browser          | Version 60.0.3112.113 (Official Build) (32-bit)

### Steps to Reproduce
1. Create New Actor, name it, add tag 'adversary', and add a description
2. From new actor page, choose a file (in my case a PDF) to attach and click attach button.
3. Get error.

#### Expected behavior
File is successfully attached to actor page.

#### Actual behavior
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

No files are attached if I go back and refresh the actor page.

**Comment by tomchop** [comment]
Sounds like a bug alright. Any chance you have a stacktrace handy?

**Comment by bkime** [comment]
My infrastructure team got a stacktrace and figured out it was a permission error on our end. They made a temporary change and everything works as should. Now they'll rebuild YETI and do it right this time. :-) Thanks for replying.
