### ISSUE TITLE
Can a feed be created which can insert data into Entity subtypes ?

### ISSUE THREAD

**Issue by ameygat** [yeti-platform/yeti#145]
### Question
Is it possible to create a feed which can add data to the Entity sub-types such as TTP / Malware / Campaign / Actor etc. ?

If yes it would be great if someone points which fields could be used in the function analyze(self, dict) ?
E.g. Like would the information about Alias / Bind to entities would go on the same dict of context ?
```
context['description'] = "{} C2 server".format(description)
context['date_added'] = datetime.strptime(dict['pubDate'], "%d-%m-%Y")
context['alias'] = actor_alias #got from feed
context['bind_to'] = ['entity1','entity2']
```

**Comment by tomchop** [comment]
No, context only exists in Observables. You can check out the available feeds for Entities in [entity.py](https://github.com/yeti-platform/yeti/blob/master/core/entities/entity.py), and in whichever other class extends that (e.g. `Actor` in [actor.py](https://github.com/yeti-platform/yeti/blob/master/core/entities/actor.py)). These fields can be manipulated in analytics as any other object (e.g. the `aliases` field in `Actor` is an array to which you can append any string).

**Comment by ameygat** [comment]
> You can check out the available feeds for Entities in entity.py / actor.py

 Sorry I didn't get you, Cause I saw only these functions in the actor.py and none of them seems related to feed.
```
def get_form(klass):
def generate_tags(self):
def info(self):
```

**Comment by gaelmuller** [comment]
He meant "fields", not "feeds" 😄

**Comment by tomchop** [comment]
Yes, sorry!
