### ISSUE TITLE
Question about one shot analytics

### ISSUE THREAD

**Issue by axpatito** [yeti-platform/yeti#146]
Hi everyone. 

I'm really enjoying the platform. First of all thank you very much for your hard work.

I'm struggling with the oneshot analytics. I can't get them to fire. I was going through the code and I now understand that unknown observables are only written to the DB. I would like to fire up oneshot analytics on freshly added unknown observables. 

Example, I analyze a new malware that has a C&C connection to XX.XX.XX.XX, I would like the platform to automate the task of going to each site to get the information. 

As I understand, this is the objective of the platform, and I know that maybe the answer is that I miss configured something. Any help would be appreciated!

Btw, I'm working on a few PR's if anyone wants to CR them:

- Improves to the centos deploy script.
- Bug fixes to the api when no single_template is set.
- Adding a master script to fire up all services and stop them as necessary.
- Adding celery flower for better output and understanding of what celery is up to.

More to come...

**Comment by tomchop** [comment]
Wow, that's a big list of PRs! I have some time this week to merge or at the very least CR the 8 (!) PRs that are in the queue.

Going back to your question, what do you mean by "going to each site to get the information"? OneShot analytics fire on-add if the type of the observable that is added is in the Analytics' `ACTS_ON` attribute (this happens with `ProcessUrl` for instance). When you say you "can't get them to fire", how are you testing them? Did you double-check that the corresponding celery worker is running?

**Comment by axpatito** [comment]
Hi! Thanks for the answer. Please don't think they are huge PR's, just small improvements 😀 

As for my question, I do have all the workers up, but nothing is getting pushed to the oneshot queue. I'm monitoring the queue both on redis, and celery flower (http://flower.readthedocs.io/en/latest/). I'm adding a new unknown observable, let's say an ip address with shodan enabled.

I would expect for both the shodan and the whois analysis to be ran the moment I add the observable to the DB, but somehow, I'm not being able to do so.

**Comment by tomchop** [comment]
What happens when you add a URL? Does it trigger any oneshot analytics? Maybe @gaelmuller can pitch-in?

**Comment by axpatito** [comment]
No, can't get them to trigger. Working from commit 6c8e1e5732637678c68137b4229554fa3363935c On Centos 7.4.1708, Python 2.7.5.

**Comment by tomchop** [comment]
OK, I'll look into it. Thanks!

**Comment by gaelmuller** [comment]
You are mixing things up.

- "one shot" analytics are triggered by humans. They are only triggered from the investigation graph (in the Analytics tab)
- "scheduled" analytics are running on a schedule (every hour for example), on certain observables. You can have a scheduled analytics act only on new observables with expiration set to `None`
- "inline" analytics are running when an observable is created. This can run in the context of the web server so this is only for small computations

I don't understand your issue regarding one shot analytics in the investigation tab. What do you mean by the threshold ?

**Comment by axpatito** [comment]
@gaelmuller  Thanks for the update. I now understand the concept of "one shot".
