### ISSUE TITLE
How to creating context with the API

### ISSUE THREAD

**Issue by MrThreatFinder** [yeti-platform/yeti#153]

**Comment by tomchop** [comment]
Hey, can you paste the full HTTP request that you sent? Ideally, if you could also run Yeti in development mode and print the stacktrace that ensues, that would be really helpful.

**Comment by MrThreatFinder** [comment]
So I'm using the postman client to test this, I'm construction the Json using a raw body option. The below works if I exclude the context field but as soon as I include it then it fails.  I'll enable the development option and post that too. 

```
POST /api/observable/ HTTP/1.1
Host: IP
x-api-key: KEY
Accept: application/json
Content-Type: application/json
Cache-Control: no-cache

{ 
	"value":"test.no-ip.biz", 
	"context": [ 
		{ 
			"report": "https://malwareconfig.com/config/46ca387e6730d4b8b4dc4d3d7450ce9c/", 
			"first_seen": "2015-03-23 20:29:25+00:00", 
			"family": "DarkComet", 
			"source": "MalwareConfig" 	
		} 
	]
}
```
