### ISSUE TITLE
Add TAXII support - Feature request

### ISSUE THREAD

**Issue by keoni161** [yeti-platform/yeti#158]
Hi,
It would be nice if you could add support/functionality for TAXII services.
This would allow integration with SIEM systems which only support standard TAXII, not raw input.
Thank you.
Claudiu

**Comment by tomchop** [comment]
Just to be clear: you mean you would want a TAXII wrapper for a STIX representation of the data in Yeti? If it's only XML wrapped in XML, export templates might be enough for that.

On another notes, would you want this only for observables or also the full STIX representation of e.g. an actor as well?

**Comment by keoni161** [comment]
Hi.
What I was trying to achieve is to import the Yety exports into a SIEM. The SIEM accepts feeds only from a TAXII server. It would be nice if exported observables were available though a TAXII discovery service like for instance Soltra Edge or hailataxii.
If that is not possible, or too complicated it's no problem. I will make an app for Qradar to pull exported indicators from YETI and populate some reference sets.
Thank you
Respectfully,
Claudiu

**Comment by LilaLipetti** [comment]
so what's this https://github.com/TAXIIProject/yeti ?

**Comment by tomchop** [comment]
@LilaLipetti I know this is very confusing, but https://github.com/TAXIIProject/yeti has no relation whatsoever to this Yeti project.

**Comment by login-securite** [comment]
@keoni161 : Did you manage to create the export template, or the QRadar you talked about ? 
I am willing to do the same so if the wheel is already built, it would help me :) !

Best regards

**Comment by keoni161** [comment]
Hi,
Sorry for the delay.
No I haven't had the time.
I fixed it somewhat with a cron task which executes a local script to update a reference set.
Hoping to find some time to implement the app as well.

**Comment by zmellal** [comment]
+1
