### ISSUE TITLE
Suricata / Snort indicator type

### ISSUE THREAD

**Issue by tomchop** [yeti-platform/yeti#162]
### Description
Create a Suricata / Snort indicator type

**Comment by dumprop** [comment]
Hi! Can you describe it in a little more detail, please?

**Comment by tomchop** [comment]
We have Yara indicator types that can be associated to samples, etc. (the goal being for other apps to be able to download said rules and run them on e.g. a sandbox)

It would be good to have Suricata / Snort rules that could be used in the same way: associated with entities and used by third-party apps when needed.

**Comment by dumprop** [comment]
> We have Yara indicator types that can be associated to samples, etc. (the goal being for other apps to be able to download said rules and run them on e.g. a sandbox)
> 
> It would be good to have Suricata / Snort rules that could be used in the same way: associated with entities and used by third-party apps when needed.

Do I understand correctly that I would like to see the snort/suricata engine in yeti? And for example, to be able to automatically analyze pcap/binary files by signatures? Or just keep these rules and use them in the investigation?

**Comment by tomchop** [comment]
No, having an engine that analyzes pcaps with suricata rules is precisely *not* what we want. We just want to provide an API endpoint that other tools can query and obtain surcata rules. It's basically as simple as a text-storage - the only suricata-specific code in there would be one that validates that the rule is actually sound.
