### ISSUE TITLE
Feature Request: 'Universal' API keys that apply to all users

### ISSUE THREAD

**Issue by scrublullz** [yeti-platform/yeti#163]
Good Morning,  
  
I am wanting to see if we could do something that allows an API key to be applied to all user's accounts that are on the YETI instance.  Maybe something like a tick box off to the right that is something to the effect of "Apply Globally."  This will allow all users to have that API key added to the profile.  
  
If a user wants to place their own key in the spot, they can remove the key and add their own. Our instance is shared among a small team which have team API keys.  This feature would make it easier for everyone in lieu of manually adding each key.  
  
Thank you again for this great product!

**Comment by tomchop** [comment]
A default API key sounds reasonable. Thanks for the input!
