### ISSUE TITLE
Text-select mouse cursor used for Prev, Page # and Next buttons

### ISSUE THREAD

**Issue by gabrielcurrie** [yeti-platform/yeti#165]
When browsing the list of observables, indicators, entities or investigations there are three buttons shown on the right of the screen: "Prev", "Page #", and "Next". 

When the mouse is over these buttons the text-select cursor is shown, however when hovering over other buttons on the site the hand cursor is shown. Is it possible to change the cursor for these buttons to the hand cursor, for consistency.

I've experienced this error using Chrome 61.0.3163.100, Firefox 55.0.1 and IE 11, all on Windows 7.

**Comment by tomchop** [comment]
Should not be very hard to fix. Thanks!
