### ISSUE TITLE
All data appears to be inaccessible after latest git pull

### ISSUE THREAD

**Issue by DigiAngel** [yeti-platform/yeti#168]
### Description
All data appears to be inaccessible after latest git pull

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | commit edf7035f41644cc5394b9ef1fab85e6f2f4473b0
| OS version       | Debian stretch
| Browser          | Chrome 62.0.3202.94 (64-bit)

### Steps to Reproduce
1. Git pull
2. Browse current data

#### Expected behavior
See current data

#### Actual behavior
All areas are blank.  Additionally I see this in the console:
~~~
Filter: {u'_cls': <_sre.SRE_Pattern object at 0x7f27cf4453d0>} {}
Filter: {u'_cls': <_sre.SRE_Pattern object at 0x7f27cf5138e8>} {}
Filter: {u'_cls': <_sre.SRE_Pattern object at 0x7f27cf52f9f0>} {}
Filter: {u'_cls': <_sre.SRE_Pattern object at 0x7f27cf524c30>} {}
Filter: {u'_cls': <_sre.SRE_Pattern object at 0x7f27cf3941f0>} {}
Filter: {u'_cls': <_sre.SRE_Pattern object at 0x7f27cf3942d0>} {}
Filter: {u'_cls': <_sre.SRE_Pattern object at 0x7f27cf3943b0>} {}
~~~

Not gonna lie....feels like almost every time I've updated yeti something breaks.  Thank you.

**Comment by DigiAngel** [comment]
I think think this might be my fault...I see data in Observable, but all my entities are gone...BUT, I may have redone that db...earlier in the month...sorry for the noise on this.

**Comment by tomchop** [comment]
No worries, glad it wasn't a huge bug on our end.
