### ISSUE TITLE
Better errors when accessing API in HTML: /api/investigation.

### ISSUE THREAD

**Issue by suomikaveri** [yeti-platform/yeti#171]
I'm running default settings, so maybe this problem is universal?
TemplateNotFound: .html
https://imgur.com/a/Bmk2e

OS: Ubuntu 16.04.03

**Comment by gaelmuller** [comment]
Some API endpoints are only available in JSON and this is one of them. You need to use the `Accept: application/json` HTTP header for it to work.

Yeti should provide a better error though.

**Comment by suomikaveri** [comment]
Can you give me instructions on how to do that?
I'm using firefox.

**Comment by gaelmuller** [comment]
Could you tell me what you are trying to do ? The API is meant to be used by code, not humans and therefore not easily accessible in a browser.

**Comment by suomikaveri** [comment]
I just wanted to see what the output looks like. What variables are there for information.
I'm writing a school report on incident response programs.

**Comment by gaelmuller** [comment]
You can go to an investigation's graph and inspect the network traffic in order to see what it looks like (https://developers.google.com/web/tools/chrome-devtools/network-performance/reference)
