### ISSUE TITLE
Find a way to commit Investigation information to the database

### ISSUE THREAD

**Issue by tomchop** [yeti-platform/yeti#173]
Links drawn during investigations are very valuable, let's find a way to incorporate this into Yeti's main DB.

Example use cases:

- Several reports (investigations) tied to one actor. It would be cool to have a list of related investigations, and see where observables come from.
- Leverage this information when Searching & Adding observables

**Comment by axpatito** [comment]
+1

**Comment by haxpak** [comment]
+1
