### ISSUE TITLE
Feature Request: Add MaxMind DB Integration

### ISSUE THREAD

**Issue by scrublullz** [yeti-platform/yeti#176]
Hello! 

I think a helpful addition to YETI would be for linking data from MaxMind's databases. Both the free MMDBs and the premium ones.

List of MaxMind databases:
https://www.maxmind.com/en/geoip2-services-and-databases

I think that the free databases would be a great starting point. The premium versions are the same data points; just updated weekly versus monthly.
https://dev.maxmind.com/geoip/geoip2/geolite2/

The ISP DB would also be a great addition (premium).

**Comment by tomchop** [comment]
Yes! This was implemented a while ago, I think there's some dead code lying around. Shouldn't be hard to make it come back from the dead. The part that would take the most time is setting up the DB configuration, but I'll think I'll start with something basic like a hardcoded path in the config. Stay tuned!
