### ISSUE TITLE
Documentation of yeti - fir ecosystem

### ISSUE THREAD

**Issue by LilaLipetti** [yeti-platform/yeti#177]
### Description
Read : https://yeti-platform.github.io/yeti-ecosystem
It says that yeti and fir can be connected?

But how?
Where's the documentation how the system needs to be configured?

**Comment by LilaLipetti** [comment]
Running yeti & fir 2 different machines.....

**Comment by gaelmuller** [comment]
This is done via a FIR plugin: https://github.com/certsocietegenerale/FIR/tree/master/fir_threatintel

Installing and activating this plugin will add configuration options to each user's profile.

Do not hesitate to reopen if you need more assistance with this.
