### ISSUE TITLE
[Help-Wanted] SAML Documentation?

### ISSUE THREAD

**Issue by ag100** [yeti-platform/yeti#178]
Hello,

I saw that Yeti has some skeleton files for using SAML authentication...  Has anyone got it setup and working properly?  I'm working on configuring it, but admittedly I don't have much experience with SAML and while I'm going through the OneLogin (and other docs), I wanted to ask and see if anyone had any suggestions, or pointers. 

Thanks in advance.

**Comment by tomchop** [comment]
Hi! This auth mode was copied on https://github.com/certsocietegenerale/fame/tree/master/web/auth, so feel free to get inspiration from that. If you manage to get it working, pull requests are very very welcome!

**Comment by ag100** [comment]
Thanks, and absolutely will do!  In the meantime, any thoughts around how easy it would be to update the local authentication code with that from fame, to enforce password strength, etc...?  Thanks again!

**Comment by tomchop** [comment]
The way Yeti's auth is written is very similar to how FAME's is. In a nutshell, the controls happen in `views.py` (this is where you check for password validity, reset, etch. and can eventually enforce password lengths, like [here](https://github.com/certsocietegenerale/fame/blob/master/web/auth/user_password/views.py#L44)).

**Comment by ag100** [comment]
Thanks Tom.

**Comment by tomchop** [comment]
No worries. Feel free to reopen if you need help with this. Also please remember to do a PR if you manage to get SAML auth working; even if it's hacky, we can work it out from there as soon as you have a working setup. Thanks!

**Comment by ag100** [comment]
Will do, thanks again!
