### ISSUE TITLE
Feature request: Creating a Yeti Docker image

### ISSUE THREAD

**Issue by dewiestr** [yeti-platform/yeti#179]
As the title says it, create a docker image.

**Comment by tomchop** [comment]
Assigning @gaelmuller who is our local Docker expert.

**Comment by tdr0** [comment]
Hi, first of all thank you for all the work you've put into YETI.
I've been playing around with it and since this issue wasn't resolved yet i created my own images starting from the `Docker` branch.

Is it ok to issue a PR for this one?

**Comment by tomchop** [comment]
@tdr0 Yes please do! That way we can see what changes you brought and make adjustments if necessary. Thanks!

**Comment by tdr0** [comment]
@tomchop there you go. I'm not very happy with the image size though. Using a multistage build would improve things significantly but that would require a more recent version of docker to build the image.

**Comment by tomchop** [comment]
This shows as merged but I think it was merged in a `Docker` branch instead of master. I'll try it out later this week and finish merging it if everything turns out to work.

**Comment by hasanshabbir** [comment]
> This shows as merged but I think it was merged in a `Docker` branch instead of master. I'll try it out later this week and finish merging it if everything turns out to work.

any update?

**Comment by gaelmuller** [comment]
Not sure of the exact history, but we now have a Dockerfile in `extras\docker`.
