### ISSUE TITLE
 Mixed Content issue

### ISSUE THREAD

**Issue by jipegit** [yeti-platform/yeti#18]
Mixed Content: The page at 'https://hostname.com/investigation/graph/observable/577f910a4e563b05955cac9b' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://hostname.com/observable/577f9be24e563b1b5bf05876'. This request has been blocked; the content must be served over HTTPS.

**Comment by tomchop** [comment]
Are you still seeing this issue?

**Comment by tomchop** [comment]
Closing, feel free to reopen if you run into this again.
