### ISSUE TITLE
504 adding 20+ observables

### ISSUE THREAD

**Issue by jsau** [yeti-platform/yeti#186]
### Description
When adding or searching more than 20~ observables via the search function the web server returns a 504. 

### Environment

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 16.04
| Browser          | Chrome Version 62.0.3202.94 (Official Build) (64-bit)

#### Expected behavior
Results are returned or observables page shows confirmation. It appears that on the backend the observables are added. 

#### Actual behavior
Page returns a 504 Gateway Time Out.

**Comment by tomchop** [comment]
Are you doing this on a "pristine" database or is your database already populated?

**Comment by jsau** [comment]
Both Pristine and Populated DB

**Comment by tomchop** [comment]
I assume you're running a production instance of Yeti (you're getting a 504 from nginx?). What hardware setup are you running Yeti on?

**Comment by jsau** [comment]
Correct, nginx on a Google Cloud Compute instance.

**Comment by tomchop** [comment]
I am trying with [this list](https://gist.github.com/tomchop/179eadc84e3c1efc12c81d352c4f0234), and get results fairly quickly, on a pristine database with no observables in it. Can you check with that list to see if you observe the same behavior?

**Comment by jsau** [comment]
Error's out:
504 Gateway Time-out

nginx/1.10.3 (Ubuntu)

**Comment by tomchop** [comment]
What specs did you use to build your instance?

**Comment by jsau** [comment]
To pick this up again looking at the nginx error messages:

`2018/01/10 15:42:28 [error] 5799#5799: *665 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xxx.xxx.xxx.xxx, server: yeti, request: "POST /observable/ HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000"`

Adding `uwsgi_read_timeout 120s; ` did help a bit, but the errors still occur when uploading large amounts of IOC's. 

Specs to build the instance current sit at n1-standard-8

**Comment by tomchop** [comment]
This is the app taking too long to respond and nginx just cuts it short. But that's definitely not the behavior we want. I'll try to reproduce this on a similar instance and let you know.

Thanks!

**Comment by jags613** [comment]
Update: Despite having added the larger nginx window for the timeout, most of the time I'll get a timeout anyways. Even when just adding two previously unknown hashes with a tag, YETI is taking minutes to give anything back. Is there any chance something is going wrong with an attempt at enrichment? Makes ingestion through the UI painful.

**Comment by jags613** [comment]
Update2: This was fixed by the same instructions to update MongoDB found here: https://github.com/yeti-platform/yeti/issues/232

**Comment by tomchop** [comment]
This is madness! I can't reproduce here (should be noted I'm running mongo v3.4.7). If @jags613 managed to solve this by buming mongo from 2 to 3, then I would assume that's where it comes from.
@jsau can you confirm your mongodb version using `mongod -v` ?

```
$ mongod -v
2018-03-30T09:04:55.942+0000 I CONTROL  [initandlisten] MongoDB starting : pid=10622 port=27017 dbpath=/data/db 64-bit host=yeti-ubuntu-big
2018-03-30T09:04:55.942+0000 I CONTROL  [initandlisten] db version v3.4.7
[snip]
```

**Comment by jsau** [comment]
Looks like the update to latest mongodb resolved the issue. 

Yeti is now responding as desired!
