### ISSUE TITLE
Unable to Search Tags Associated w/Entities

### ISSUE THREAD

**Issue by ag100** [yeti-platform/yeti#187]
Searching entities by tag does not return any results.

### Steps to Reproduce
1.  Add tags to an entity (tested with actor, ttp, campaign and malware).
2.  Search for a tag (tags=evil)

#### Expected behavior
Matching entities should be returned.

#### Actual behavior
No results are found.

**Comment by tomchop** [comment]
There's a miscomprehension around what "tags that link to this entity" are (which is admittedly convoluted). They're not actually there to "tag the entity" but to tell Yeti to link an Observable to that entity should it be tagged with it. 

For example, if an "Angler" entity has an "angler" tag, then any observables that are tagged "angler" will be directly linked to that entity.

**Comment by tomchop** [comment]
PR #193 should fix that.

**Comment by ag100** [comment]
Thanks Tom, for both the clarification and the fix!

**Comment by tomchop** [comment]
No worries, sorry it took so long for what ended up being a relatively simple fix.
