### ISSUE TITLE
User logging

### ISSUE THREAD

**Issue by tomchop** [yeti-platform/yeti#190]
It would be nice to have attributable actions in Yeti.

* What did a user do in Yeti? 
  * Logged in
  * CRUD logs
* Who added / searched for this observable?

**Comment by alexandrelim** [comment]
Hello, 
I'd like to contribute to the project. I graduated with a Masters degree in network security from the Pierre & Marie-Curie University, Paris, France.
Can I implement this feature ?

**Comment by tomchop** [comment]
Hey! Thanks a lot for your interest. Sure, feel free to implement it :) 

FYI, I am currently working on a new version of Yeti (https://github.com/yeti-platform/TibetanBrownBear) in which I still need to implement authentication. Is this something you would be interested in helping out with?

**Comment by alexandrelim** [comment]
Hi,
I have been working on other project. I now have time to devote to this project :) 
I think that I don't have enough experience to implement the authentication from scratch (maybe later) so I'll start by trying to help on this version. 

Can you develop a little more about what kind of log you want ? Is it a log file in which all those information are stored or is it something more elaborate than that ?
