### ISSUE TITLE
Analytics Configuration Not Displaying or Executing

### ISSUE THREAD

**Issue by darksheer** [yeti-platform/yeti#199]
### Description
After installing and setting up Yeti, the analytics page doesn't display any configuration information similar to the documentation. 

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 6c324800cbaa7841b9776ecc0f5218e133f8c0bf
| OS version       | Ubuntu 16.04
| Browser           | Chrome Version 62.0.3202.94 (Official Build) (64-bit)

### Steps to Reproduce
1. Follow install steps in Yet documentation
2. Allow feeds to ingest data. 
3. Setup API keys in User settings
4. View the Analytics page. 
5. No configuration information displayed

#### Expected behavior
We page should display the configuration information for the different analytics. 

#### Actual behavior
The analytics pages displays no configuration information

![image](https://user-images.githubusercontent.com/1522288/34321986-8254224c-e7d0-11e7-85f2-1f20fbbb98b0.png)

**Comment by tomchop** [comment]
Looks like you're getting error 500s somewhere. Can you launch the debug server using `/yeti.py webserver --debug` and tell me the output?

**Comment by darksheer** [comment]
Executed the webserver with --debug and hit the analytics page.  No output on the CLI for information.  Are the logs pushed somewhere else?

**Comment by tomchop** [comment]
Just to make sure there are no misunderstandings, the debug webserver listens for requests requests to `http://<server>:5000/`.

If you load the analytics webpage with the developer Chrome console open (Cmd + J) on the Networking tab, you should see these three entries when selecting XHR. 

![image](https://user-images.githubusercontent.com/1257972/34363121-a2f41d4e-ea79-11e7-9ef3-2789288ec54e.png)

According to your screenshot, they should be returning 500's. Is that the case? Can you tell me what actual data they are returning?

**Comment by darksheer** [comment]
Yes, http://<server>:5000 is the url I'm using.  I confirmed it by navigating to other pages, it's only the Analytics page thats returning no information.  I also confirmed that all other services are running properly (beats, analytics, feeds, etc.)  I do see in the observables that objects are being added via Analytics, just nothing displayed as your screen shot shows.

**Comment by tomchop** [comment]
OK thanks. Can you please check the thing about the XHR requests to `scheduled/`, `oneshot/` and `inline/`?

**Comment by darksheer** [comment]
Apprently chrome is the source of the issues...I should have checked via different browser.  Something within Chrome is blocking the page with a:
```
ERR_BLOCKED_BY_CLIENT
```

I flipped to FireFox and everything appeared properly--minus I need to find out why hostname analytics aren't functioning properly. 

![image](https://user-images.githubusercontent.com/1522288/34368209-fa65fe2a-ea66-11e7-8737-1913c5c612b4.png)

**Comment by darksheer** [comment]
Closing this as I'm sure it's something with my chrome installation...I just need to figure out what's blocking it. 

Thanks for the help.
