### ISSUE TITLE
Blocklist.de Analytics Function (DNS Lookup for malicious domains)

### ISSUE THREAD

**Issue by darksheer** [yeti-platform/yeti#201]
### Description
Create an analytics function to lookup domains via blocklist.de DNS server

http://www.blocklist.de/en/rbldns.html

Query example (with returned data):
```
host -t any 2.0.0.127.bl.blocklist.de 

Answer: 
2.0.0.127.bl.blocklist.de TXT "Infected System (Service: w00tw00t, Last-Attack: $unixtimestamp), see http://www.blocklist.de/en/view.html?ip=127.0.0.2" 
2.0.0.127.bl.blocklist.de A 127.0.0.15 
```

More examples here => https://forum.blocklist.de/viewtopic.php?f=11&t=17

**Comment by tomchop** [comment]
Sounds good. If I understand correctly, this analytics would run on IPs (rather than domains)

**Comment by darksheer** [comment]
Ah yeah sorry, meant IP's not domains!
