### ISSUE TITLE
Virushare Hash Ingest Correlation 

### ISSUE THREAD

**Issue by darksheer** [yeti-platform/yeti#204]
I'm looking at building a feed to ingest hashes from VirusShare as they produce a list of all objects in their repo.  The list provided has two columns (MD5 original, MD5 Unpacked).  I can easily create the parser to pull both feeds and ingest, but as they are associated they should probably be associated in MongoDB.  I'm not sure the best approach for doing this as I still don't fully understand the backend of Yeti.  

Any thoughts on how best to accomplish this?  I'm happy to do the work, just need some guidance or examples moving forward. 

https://virusshare.com/hashes/unpacked_hashes.md5

**Comment by ag100** [comment]
Hey, I'm not a Yeti expert by any stretch of the imagination, but would something like this accomplish what you're trying to do?  It  creates a related observable link between the original and unpacked md5.

def strip(str):
    return str.strip()


class virusshareHashes(Feed):
#
	def strip(str):
    		return str.strip()
#

	default_values = {
		"frequency": timedelta(minutes=600),
		"name": "virusshare 0.1",
		"source": <url>
		"description": "virusshare feed",
	}
#
#

        def update(self):
            a = '  '
            for line in self.update_csv(delimiter=',', quotechar='"'):
                self.analyze(line)
#
	def analyze(self, line):
            if not line or line[0].startswith("Original"):
                return
#
            Original_MD5, Unpacked_MD5 = tuple(line)
#
            tags = []
            tags.append("virusshare")
#
#
            try:
                o_md5 = Hash.get_or_create(value=Original_MD5)
                o_md5.tag(tags)
            except ObservableValidationError as e:
                logging.error("Invalid line: {}\nLine: {}".format(e, line))
#
            try:
                u_md5 = Hash.get_or_create(value=Unpacked_MD5)
                u_md5.tag(tags)
                if o_md5 != '':
                    u_md5.active_link_to(o_md5, 'hash', self.name, clean_old=False)
            except ObservableValidationError as e:
                logging.error("Invalid line: {}\nLine: {}".format(e, line))

**Comment by tomchop** [comment]
Sorry for not getting back to you earlier. Basically you just need to create both observable sin the database and call `link_to` on one of them. The gist is what @ag100 said:

```
o_md5 = Hash.get_or_create(value=<ORIGINALMD5>)
u_md5 = Hash.get_or_create(value=<UNPACKEDMD5>)
o_md5.active_link_to(u_md5, 'unpacked hash', self.name) # here, self.name is the name of the feed
```

**Comment by tomchop** [comment]
Assigning this to you @darksheer since you indicated you were working on this.

**Comment by darksheer** [comment]
Got it.  I'll revisit this and see if I can suss it out.

**Comment by doomedraven** [comment]
this feed is dead

```
>>> r = requests.get("https://virusshare.com/hashes/unpacked_hashes.md5")
>>> r.headers
{'Content-Length': '126795872', 'ServerToken': 'Apache/5.1.0', 'Accept-Ranges': 'bytes', 'Keep-Alive': 'timeout=5, max=100', 'Server': 'Apache', 'Last-Modified': 'Wed, 11 May 2016 01:39:02 GMT', 'Connection': 'Keep-Alive', 'ETag': '"22469d2-78ec060-532871b353980"', 'Date': 'Sat, 25 May 2019 13:11:54 GMT', 'Content-Type': 'text/plain'}
```

'Last-Modified': 'Wed, 11 May 2016 01:39:02 GMT',
