### ISSUE TITLE
Team CYMRU Malware Hash Registry Lookup

### ISSUE THREAD

**Issue by darksheer** [yeti-platform/yeti#205]
### Description
Throwing this out as an additional analytics lookup possibility. 

Hashes can be checked against hash.cymru.com with the following methods:

```whois -h hash.cymru.com 66fdd0199653d42bae7f8e73ffe423cd```

```netcat hash.cymru.com 43 < list01 > list02```

```date --date="1970-01-01 <unix timestamp> secs UTC"```

I'm not aware of what rate limiting/blocking is enabled, but this could be used for more than just a one-shot lookup and could be used to enrich against any hash within the DB. 

More info available here:
http://www.team-cymru.org/MHR.html

**Comment by tomchop** [comment]
That sounds cool. They seem to do bulk as well which is probably better for their service to handle. I've reached out to them to see what the best avenue of progress is.
