### ISSUE TITLE
Case Sensitive Searching

### ISSUE THREAD

**Issue by ag100** [yeti-platform/yeti#209]
When searching for observables from the "Search/Add" text box (with/without add new observables checked), the search appears to be case insensitive.  When searching for observables from the "Advanced Search" box on the same page, or from the search query text box on the browse page, searching appears to be case sensitive (with/without regex).

Is this by design?

Thanks!

**Comment by tomchop** [comment]
Yeah, that's working as intended. The Search/Add endpoint will normalize observables before looking for them in the database (eg. lowercase hostnames and normalize URLs), and then performs an "exact" match between that result and the database.

The Advanced Search will also do exact matches when the "regex" checkbox is left unchecked.

**Comment by ag100** [comment]
Ok, thanks Tom.  We'll look to make some changes on our local instance to enable case insensitive searching across the board.

**Comment by tomchop** [comment]
You would like to see cases insensitiveness in the "Advanced Search" tool?

**Comment by ag100** [comment]
Ideally, yeah..  A lot of our analysts who use the tool may not know the differences in expected behaviour when performing a search, whether it be from the "Advanced Search" box, the browse page, or the API.  I'd just hate for them to miss something in the database, just because the case they used differs from when the observable was entered (though I understand scenarios where case sensitive searching is important, as well).  Perhaps an option to change the search (either a checkbox, an API argument, etc...)?  Thanks again!

**Comment by tomchop** [comment]
Not knowing the tool's behavior is bad, I agree. What about making the regular expression case-insensitive by default?

**Comment by williamsdr** [comment]
@tomchop Thanks for the details.
I noted in core/web/api/crud.py:CrudSearchAPi:search() that `ignorecase` is pulled from the parameters, however I don't see a corresponding `ignorecase` field on the form ./web/frontend/templates/observable/browse.html.   Resulting in `ignorecase` always being `false`.

Also, I 'm not sure this is the right flow, but it looks like the case sensitivity check in get_queryset() is dependent on Regex checkbox being enabled.:
`if regex and isinstance(value, basestring):
            flags = 0
            if ignorecase:
                flags |= re.I
            value = re.compile(value, flags=flags)
`

Enabling an independent `ignorecase` parameter, as the code suggests may at least give visibility to the behavior and allow user control for when to be case sensitive.    

In my testing, by defaulting the CrudSearchAPI:search() to `true`, case insensitive searches can be enabled with the regex flag.

**Comment by tomchop** [comment]
That's right, `ignorecase` defaults to False in `CrudSearchApi:searc()`. And yes, that variable will only have an effet when searching through regular expressions. This means that all case-insensitive searches will actually be regular expression searches, which will slow everything down considerably (especially on large datasets).

An alternative is to leverage Mongo's [full-text search](https://docs.mongodb.com/manual/core/index-text/), or [Collations](https://docs.mongodb.com/manual/core/index-case-insensitive/). This works well on natural language but could have strange effects on technical observables. Maybe we should test and find out? :)

Thoughts?

**Comment by williamsdr** [comment]
Yes, I've started looking at collation with MongoDB 3.6.   Setting a default collation did overcome the case sensitive search point - but it also rendered us unable to insert observables which should be case sensitive (URL, filenames for instance).     I'll keep exploring this aspect, as I think this provides the best future option; and flexibility.

**Comment by ag100** [comment]
*building test platform as we speak*

Thanks @tomchop  - I had a conversation with @williamsdr and we were looking at options.  I like the idea of testing Mongo's collations to improve searching, without (hopefully) taking too much of a performance hit, and am happy to stand up a box to test with.

**Comment by williamsdr** [comment]
Creating collation indexes is straight forward using the "meta:" values.   Simple tests surfaces issues where data which are case sensitive (Url, Text, File) would not keep each unique value when the default index specified a case insensitive collation [see below].    The "get_or_create" was using the default index and (as expected) found an entry, even when case was different.     Currently exploring use of a secondary collation for case-insensitive search conditions.

**Comment by williamsdr** [comment]
Still open.   No progress since last comment.
