### ISSUE TITLE
Internal Server Error after server restart

### ISSUE THREAD

**Issue by v0ris** [yeti-platform/yeti#211]
### Description
After a server restart I get "500 Internal Server Error" message when I connect the webinterface

### uwsgi status:

yeti_uwsgi.service - Yeti UWSGI server
   Loaded: loaded (/etc/systemd/system/yeti_uwsgi.service; enabled; vendor preset: enabled)
   Active: active (running) since k 2018-01-09 12:37:08 CET; 17min ago
 Main PID: 2421 (uwsgi)
   Status: "uWSGI is ready"
   CGroup: /system.slice/yeti_uwsgi.service
           ├─2421 /usr/local/bin/uwsgi --socket 127.0.0.1:8000 -w yeti --callable webapp --processes 4 --threads 2
           ├─2431 /usr/local/bin/uwsgi --socket 127.0.0.1:8000 -w yeti --callable webapp --processes 4 --threads 2
           ├─2432 /usr/local/bin/uwsgi --socket 127.0.0.1:8000 -w yeti --callable webapp --processes 4 --threads 2
           ├─2433 /usr/local/bin/uwsgi --socket 127.0.0.1:8000 -w yeti --callable webapp --processes 4 --threads 2
           └─2435 /usr/local/bin/uwsgi --socket 127.0.0.1:8000 -w yeti --callable webapp --processes 4 --threads 2
uwsgi[2421]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1607, i
uwsgi[2421]:     self.try_trigger_before_first_request_functions()
uwsgi[2421]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1654, i
uwsgi[2421]:     func()
uwsgi[2421]:   File "./core/yeti_plugins.py", line 24, in get_plugins
uwsgi[2421]:     entry = obj.objects.get(name=obj.default_values['name'])
uwsgi[2421]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.p
uwsgi[2421]:     raise queryset._document.MultipleObjectsReturned(message)
uwsgi[2421]: MultipleObjectsReturned: 2 items returned, instead of 1

### syslog:

uwsgi[2421]: [2018-01-09 12:56:27,455] ERROR in app: Exception on / [GET]
uwsgi[2421]: Traceback (most recent call last):
uwsgi[2421]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
uwsgi[2421]:     response = self.full_dispatch_request()
uwsgi[2421]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1607, in full_dispatch_request
uwsgi[2421]:     self.try_trigger_before_first_request_functions()
uwsgi[2421]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1654, in try_trigger_before_first_request_functions
uwsgi[2421]:     func()
uwsgi[2421]:   File "./core/yeti_plugins.py", line 24, in get_plugins
uwsgi[2421]:     entry = obj.objects.get(name=obj.default_values['name'])
uwsgi[2421]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 286, in get
uwsgi[2421]:     raise queryset._document.MultipleObjectsReturned(message)
uwsgi[2421]: MultipleObjectsReturned: 2 items returned, instead of 1

**Comment by tomchop** [comment]
Did you run the migrations before restarting Yeti as a service?

    $ ./yeti.py syncdb

**Comment by v0ris** [comment]
I did run the following commands:

./yeti.py syncdb
service yeti_uwsgi restart
service yeti_web restart

But the problem is still exist.

**Comment by tomchop** [comment]
You need to make sure there is only one entry per name in some mongodb collections (schedule_entry, one_shot_entry, inline_analytics).
If you don't mind loosing individual settings for each `ScheduledEntry`, you can run this (after making a backup of course):

* Stop all running Yeti services
* Launch a mongo shell
```
$ mongo
> use yeti
> db.schedule_entry.drop()
> db.one_shot_entry.drop()
> db.inline_analytics.drop()
```
* Relaunch system services (including the sleep call)
```
$ sudo systemctl start yeti_oneshot.service
$ sleep 5
$ sudo systemctl start yeti_feeds.service
$ sudo systemctl start yeti_inline.service
$ sudo systemctl start yeti_exports.service
$ sudo systemctl start yeti_analytics.service
$ sudo systemctl start yeti_beat.service
$ sudo systemctl start yeti_uwsgi.service
```
Let me know if that solved the problem for you. Thanks!

**Comment by v0ris** [comment]
This solved the problem. Thank you very much!
One more thing: Please add "python-dateutil" to the requirements.txt beacuse system services do not start until you do not get it.

Thanks!

**Comment by tomchop** [comment]
Will do. Thanks!

**Comment by v0ris** [comment]
The 3f7ace12bc3b7b44f420c6527902b750b2455e87 add it, but my install is older than that.
Sorry for my ignorance.
