### ISSUE TITLE
Advance search Observables is taking time.

### ISSUE THREAD

**Issue by sumeena-rakhwal** [yeti-platform/yeti#221]
Hello, 
When i enter ip in advance search as a input, it takes around 10-15 mins to show the results.
Is there any idea, why this process is taking so long, but at the same end if for particular id, test the simple query in mongo console, it shows me data/response very quickly.

Any help, working flow description is appreciated .

Thanks !

**Comment by tomchop** [comment]
This is definitely not normal behavior. How many observables do you have in your database?

Can you please paste a screenshot of the exact request you're sending (using the Chrome dev tools for instance?) This will really help us find the root cause of the issue.

Thanks!
