### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by jimbolya0607** [yeti-platform/yeti#229]
Went to install Yeti last night and it failed.  This is probably on me.  However, I know there's yet.example file that allows me to point Yeti at a different DB.  The current architecture I'm using points applications to DBs that do not reside on the application server.  So my question:  what file does Yeti use to point the application at a different DB location?

Jimbo

**Comment by tomchop** [comment]
You can tweak this in the yeti.conf file. Simply copy or rename the `yeti.conf.sample` ([link](https://github.com/yeti-platform/yeti/blob/master/yeti.conf.sample)) file to `yeti.conf` in the same directory and edit it as you see fit. The first few lines should resolve your issue:

```
[mongodb]

##
## Use these settings to configure how to connect to your MongoDB database.
## All settings are optional, with default values being the one in the comment.
## If you do not specify a username and password, there will be no authentication.
##

# host = 127.0.0.1
# port = 27017
# database = yeti
# username = yeti
# password = STRONG_PASSWORD
```

**Comment by jimbolya0607** [comment]
Huh - That's what I thought.  I searched for a yeti.conf file as i thought that would make sense. 
Never found it.  The install must have failed more than i thought?

**Comment by tomchop** [comment]
If you installed it via `bootstrap.sh`, then it's normal since it doesn't make a usable copy of yeti.conf (since all values are default anyways)

**Comment by jimbolya0607** [comment]
I'd have to go back and look to be honest.  I want to say I think I tried it both ways. 
I'm at work though so I can't look at my command line to confirm.
