### ISSUE TITLE
Running webapp over HTTPS

### ISSUE THREAD

**Issue by JoelKieper** [yeti-platform/yeti#230]
I am trying to find a way to add a certificate to the yeti web interface, rather than hosting this over standard http (openssl, maybe a 3rd party purchased cert). I would like to host yeti on a system and make it accessible out over my LAN to multiple individuals. I already altered the yeti.py file to host the web app over a routable IP instead of localhost but I can't find anywhere that allows me alter settings to include a certificate.

My question is, is hosting the web app over https with either a self-signed or 3rd party certificate possible and if so, how can I make this change?

Thanks.

**Comment by tomchop** [comment]
You should really use nginx for HTTPS traffic. You can check out [this](https://github.com/yeti-platform/yeti/blob/master/extras/nginx/yeti) example config for uwsgi. To set up SSL, you can use Let's encrypt (free!) and follow [this](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04) guide. Hope it helped!
