### ISSUE TITLE
Tagged observables not displayed in Entity content

### ISSUE THREAD

**Issue by dfuertes79** [yeti-platform/yeti#232]
Adding an observable with a tag that maches an entity tag, properly shows the relationship: 
![image](https://user-images.githubusercontent.com/11603084/36982406-1e65aa78-2090-11e8-8a35-fd0ae8732cc5.png)

However, the problem is that observables are not displayed on Entity views: 

![image](https://user-images.githubusercontent.com/11603084/36982457-32130e12-2090-11e8-9d3f-aaeb873250c6.png)

Following the exact same example on the use case guide, leads to this situation.

**Comment by dfuertes79** [comment]
Using the API provides the expected information, it seems to be a UI only issue.


{
    "matches": [],
    "unknown": [],
    "known": [
        {
            "description": "IP to test",
            "created": "2018-03-01T19:29:41.699000",
            "last_analyses": {},
            "tags": [
                {
                    "fresh": true,
                    "first_seen": "2018-03-05T15:10:20.389000",
                    "name": "cobalt",
                    "last_seen": "2018-03-05T15:10:20.389000"
                }
            ],
            "value": "89.46.222.18",
            "human_url": "http://[ACCESS URL HERE]/observable/5a9854a5836a142af8f551d8",
            "sources": [],
            "url": "http://[ACCESS URL HERE]/api/observable/5a9854a5836a142af8f551d8",
            "context": [],
            "type": "Ip",
            "id": "5a9854a5836a142af8f551d8"
        }
    ],
    "neighbors": [],
    "entities": [
        {
            "name": "Cobalt",
            "family": null,
            "tags": [
                "cobalt"
            ],
            "url": "http://[ACCESS URL HERE]/api/entity/5a9d1a08836a142af8f551e6",
            "human_url": "http://[ACCESS URL HERE]/entity/5a9d1a08836a142af8f551e6",
            "matches": {
                "observables": [
                    {
                        "name": "Cobalt",
                        "family": null,
                        "tags": [
                            "cobalt"
                        ],
                        "url": "http://[ACCESS URL HERE]/api/entity/5a9d1a08836a142af8f551e6",
                        "matched_observable": {
                            "human_url": "http://[ACCESS URL HERE]/observable/5a9854a5836a142af8f551d8",
                            "url": "http://***********/api/observable/5a9854a5836a142af8f551d8",
                            "value": "89.46.222.18",
                            "tags": [
                                "cobalt"
                            ]
                        },
                        "human_url": "http://[ACCESS URL HERE]/entity/5a9d1a08836a142af8f551e6",
                        "type": "Malware",
                        "id": "5a9d1a08836a142af8f551e6",
                        "description": ""
                    }
                ]
            },
            "type": "Malware",
            "id": "5a9d1a08836a142af8f551e6",
            "description": ""
        }
    ]
}

**Comment by tomchop** [comment]
Weird, can't reproduce here. What browser are you using?

Can you please try the following (on Chrome): 

* Go to the Entities page, Observables tab. 
* Bring up the Chrome developer tools, go to Network tab
* Click on "Filter" in Yeti's UI
* See if anything behaves differently?

**Comment by dfuertes79** [comment]
I have installed it in 2 different environments and asked a friend to do the same and in the 3 cases got the same result.

By loading the dev tools, you can see a 500: 
<img width="1086" alt="image" src="https://user-images.githubusercontent.com/11603084/37045236-c50bd160-2165-11e8-9ec7-745c0d6bcba2.png">

**Comment by tomchop** [comment]
OK cool. If you can show me the exact request that is sent (i.e. the headers tab, that would be super helpful).

Which example did you follow? I'll start from a pristine DB and see if I can get the same result.

**Comment by dfuertes79** [comment]
Request headers:

POST /api/neighbors/tuples/entity/5a9d1a08836a142af8f551e6/ttp HTTP/1.1
Host: [IPADDRESS]:5000
Connection: keep-alive
Content-Length: 64
Accept: */*
Origin: http://[IP ADDRESS]:5000
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
Content-Type: application/json
Referer: http://[IPADDRESS]:5000/entity/5a9d1a08836a142af8f551e6
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Cookie: session=......................................[SESSION COOKIE ]....................

Request Payload:

{filter: {}, params: {page: 1, regex: true, ignorecase: true}}

Response:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

**Comment by tomchop** [comment]
I followed the instructions [here](http://yeti-platform.readthedocs.io/en/latest/use-cases.html#documenting-malware-intelligence) and could not reproduce. I did fix some code that affected these functions, so could you please try again? Otherwise, please describe step-by-step what you did to reproduce.

**Comment by tomchop** [comment]
Any updates?

**Comment by mbower** [comment]
Im seeing the same thing. Headers below

POST /api/neighbors/tuples/entity/5aac5f951d41c803bfa467d2/malware HTTP/1.1
Host: [IP ADDRESS]
Connection: keep-alive
Content-Length: 64
Accept: */*
Origin: http://[IP ADDRESS]
X-Requested-With: XMLHttpRequest
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36
Content-Type: application/json
DNT: 1
Referer: http://[IP ADDRESS]/entity/5aac5f951d41c803bfa467d2
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Cookie: session=.eJwdjrFugzAURX-l8pzB79mAidShkiHqYFtEJggvEdg4KYEladSUKP9e1OlKV-ce3Sc5xutwO5Pt9_U-bMjxK5Dtk7z1ZEuM9YuxH2ik_zG7GvRYTkqWF9McpnaZZtW0XNlyNlJPGitQcn92dj85e5iV1KOT-9k0FW-XcNbYMic_mZ71qGzFdFMzZ2vU8rT2Beq5vLhGoR4vTNswurFF1RRMyxqV9Q-zek1TTm3TLnopfo09PdxYodoV6Obinbw25H4brv__iQiUUQSRxKQLueDARRo9C74bugCMdjxmAihDzHO6pugzCtFDBJoEBI4RIIUsySFgAJ7nHLM-Zb5PASnNPO9iB1kmGPguXVnRD7TPk3XJBy58Tl5_cfNmUg.DZpvjw.tP603txxhK1WmC4mx_KETPbVuBA

![screen shot 2018-03-26 at 7 59 36 am](https://user-images.githubusercontent.com/408684/37905080-b30d9c08-30cb-11e8-85b0-d2216a4f547c.png)

**Comment by mbower** [comment]
Sure, I'll probably get to it this weekend. In the mean time, commands below are what I did to upgrade from mongodb 2.6 to 3.6. 

Backup DB:
`sudo mongodump -d yeti`

Stop mongodb and rename local directory:
`sudo service mongodb stop`
`sudo mv /var/lib/mongodb /var/lib/mongodb_26/`

Add latest mongodb repo:
`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5`

`echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.6.list`

Install the newest version:
`sudo apt-get update && sudo apt-get install -y mongodb-org`

Start up mongodb:
`sudo service mongod start`

Restore data from backup:
`mongorestore`

Verify everything is working, then delete the old data:
`sudo rm -rf /var/lib/mongodb_26/`

**Comment by sumeena-rakhwal** [comment]
Hi @mbower @tomchop ,
Your comments were very helpful. As now, i am also facing the same issue & ready to go with the upgradation of mongodb from 2.6 to 3.6 . Before proceeding further, i have following queries:-

- Do i need to make any minor or major changes in queries already written in yeti ? As i have checked 3.6 compatibility issues/changes https://docs.mongodb.com/manual/release-notes/3.6-compatibility/ ?

- Before making mongodb upgrade, do i need to upgrade mongodb 2.6 to 3.4 first & then to 3.6 , as it's mentioned in official documentation https://docs.mongodb.com/manual/release-notes/3.6-upgrade-standalone/#upgrade-process . ?

Please let me know your views on both points.

**Comment by mbower** [comment]
☝️ What he said. 😄

**Comment by sumeena-rakhwal** [comment]
In my case, things are pretty different & they are following:-

1. My yeti dB has been reached upto 10 GB.
2. I have followed the steps, directly upgrading to 3.6 from 2.6 on new VM instance but it failed.
3. After some unsuccessful trials, i had grab the conecpt of step-by-step upgradtion of mongo (https://docs.mongodb.com/manual/release-notes/3.6-upgrade-standalone/#upgrade-process), which safely allow me to upgrade till 3.4 .
4. As dB size is very large, on upgrading to 3.6, showing some key index error. Well, i am pretty much ok with 3.4.

Sometimes, these things behave differently on diff-2 machines. 
Might be my comment will help someone.
