### ISSUE TITLE
Cybercrimetracker.py needs updating

### ISSUE THREAD

**Issue by pingone** [yeti-platform/yeti#235]
The XML in cybercrime-tracker[.]net/rss.xml changed a few months back to include the sandbox name and IP address (if found) in the description field. As tagging is created by the description field in this feed, most observables ingested by it are getting unique tags for each instead of just the malware name.

**Comment by tomchop** [comment]
Thanks for the heads up, will fix ASAP.

**Comment by sebdraven** [comment]
We are fixed in the PR, don't hesitate to update and test it and make a feedback to close the issue
