### ISSUE TITLE
static Folder missing

### ISSUE THREAD

**Issue by 219liangyi** [yeti-platform/yeti#238]
Before opening an issue, please make do a quick search through the current issues
and the mailing list (https://groups.google.com/forum/#!forum/yeti-users) to see
if it hasn't been answered already.

### Description
[Please provide a description of the issue encountered]

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log | head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3
| Browser          | Chrome 56.0.2924.87

### Steps to Reproduce
1. git clone the repo
1. cd yeti
1. pip install -r
1. observe stacktrace

#### Expected behavior
[How are you expecting the application to behave?]

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]

**Comment by tomchop** [comment]
You probably forgot to run `yarn install`.
