### ISSUE TITLE
No logo

### ISSUE THREAD

**Issue by atluxity** [yeti-platform/yeti#239]
### Description
Yeti does not have a logo yet.
 
#### Expected behavior
Giving out stickers is a great way to promote free software, but one has to have a logo to have a sticker.

#### Actual behavior
Asked for sticker, got answer that there is no logo yet.

#### Steps to solve
Please describe, as detailed as possible, what you would like to achive from a logo. Do you have an idea? Are there some things you would want to avoid? How can we make it uniqe? How can we make it translate well across differnt mediums? It should be somewhat timeless, how do we achive that? What is the target audience, what values and culture do you want a logo to reflect? Some questions to try to trigger some ideas in your head.

Make a description, and I'll try to find someone willing to make something. But we need to know what something is first.

**Comment by tomchop** [comment]
The tool is named Yeti, and Yeti is a mystical animal that has inspired fear and curiosity in the nepalese folklore for decades. (see [here](https://en.wikipedia.org/wiki/Yeti) for specifications). I think this can give a good starting base for inspiration.

I'm pretty bad at logo specifications, but here they go:

* Preferably vectored drawing, so we can easily scale it up or down with no quality loss, and make stickers out of it
* Needs to have an icon (e.g. the monster) + some text ("Yeti"). The two should be dissociable, that is to say we need to be able to display the logo independently of the text
  * This will give us greater flexibility — text on the right of the logo for horizontal display, just the logo for the favicon, etc.
* The "graphic" part of the logo should be square-ish, so we can easily fit it on the webpage, avatars, favicons, etc.

**Comment by CirKu17** [comment]
Not a great graphic design pro here, but I have a proposal:

![yeti-logo svg](https://user-images.githubusercontent.com/833603/49645642-059d7180-fa1d-11e8-966f-cbd47297601e.png)

![yeti-logo-font svg](https://user-images.githubusercontent.com/833603/49645653-0e8e4300-fa1d-11e8-9738-cf3741503dbc.png)

I have the svg, in case you like it, ask me or tell me how to contribute.

**Comment by atluxity** [comment]
I thought this looked really good!

**Comment by tomchop** [comment]
Oh wow, this looks really good! Is there any way I can experiment / tweak it a bit?

(sorry for the late reply btw, it has been a couple of hectic days)

**Comment by CirKu17** [comment]
Yes, here the svgs:
[yeti-logo-font.svg.zip](https://github.com/yeti-platform/yeti/files/2672661/yeti-logo-font.svg.zip)

**Comment by doomedraven** [comment]
the .ico would be good for browser too :)

@tomchop  do you have latest/tweaked version to add ?
