### ISSUE TITLE
Update bootstrap scripts to install a recent mongodb version

### ISSUE THREAD

**Issue by tomchop** [yeti-platform/yeti#244]
bootstrap installs whatever version of mongodb is considered stable by the distribution it runs on (~2 on Ubuntu 16.04). Yeti uses versions that have been introduced in mongo 3.2.

The commands to install this are provided in [this comment](https://github.com/yeti-platform/yeti/issues/232#issuecomment-376618501). We should update the bootstrap scripts (at least ubuntu_bootstrap) to include this.

**Comment by darksheer** [comment]
I'll take this one if you can assign to me.

**Comment by gaelmuller** [comment]
We can't assign it to you on GitHub because you don't have write access to the repository.

We are happily waiting for your pull request however 😄

**Comment by amateur-professional** [comment]
As a side note for enhancing the Ubuntu bootstrap script - The yeti_inline.service file it references does not exist in the repo.

**Comment by FirehaK** [comment]
@amateur-professional if the pull request I just submitted is accepted, I also removed the yeti_inline.service references and some sudo usage that wasn't necessary if you follow the README installation instructions.

**Comment by robertnixon2003** [comment]
This is complete correct?

**Comment by tomchop** [comment]
@robertnixon2003 yes this was merged in #274
