### ISSUE TITLE
Change Default Tag Expiration

### ISSUE THREAD

**Issue by jags613** [yeti-platform/yeti#246]
Is there a way to change the default tag expiration globally?

Thanks!

JA

**Comment by tomchop** [comment]
No, for the time being they are set on a tag-by-tag basis. There is a way to change them all running a mongo query if that's something you can muster, or you can change it in the code. I know it's less than ideal but unfortunately I haven't gotten around to writing the backend customization part.

**Comment by jags613** [comment]
Thanks man. I’ll go change it in the code and see what I can fiddle with mongo as my experience there is limited.

I thinks a year is a more desirable default. Though there’s something to be said for a historical mode where you can see previously tagged.


Juan Andres Guerrero-Saade
Principal Security Researcher, Insikt Group
Recorded Future 
jags@recordedfuture.com
Twitter- @juanandres_gs

On Apr 1, 2018, at 10:45 PM, Thomas Chopitea <notifications@github.com> wrote:

No, for the time being they are set on a tag-by-tag basis. There is a way to change them all running a mongo query if that's something you can muster, or you can change it in the code. I know it's less than ideal but unfortunately I haven't gotten around to writing the backend customization part.

**Comment by tomchop** [comment]
FYI, expired tags are not deleted, they are just marked as expired. This changes whether they are included in any exports that select that specific tag or not.
