### ISSUE TITLE
Can you provide a more detailed user manual?

### ISSUE THREAD

**Issue by spookssos** [yeti-platform/yeti#253]
Can you provide a more detailed user manual?  I can not import some XML File into investigations, and i don't know the correct format of file.

**Comment by tomchop** [comment]
Are you requesting a general user manual or a specific one on how to use imports? Please provide more information as to what behavior you are observing.

**Comment by spookssos** [comment]
I have got a general user manual that described import from URL , but there is no use case which can import from file into investigations. I want to know the correct format of the file can import. 
Thanks for your comment.
