### ISSUE TITLE
Feature Request: New field in error logs which lists the offending feed

### ISSUE THREAD

**Issue by scrublullz** [yeti-platform/yeti#255]
Hello,

I would like to see which feeds are causing issues with incomplete URLs or invalid host names.  The two shown below are missing the trailing `/` after the TLD. 

```
Apr 10 15:20:08 MachineName celery[92725]: [2018-04-10 15:20:08,684: ERROR/ForkPoolWorker-1] 'sygicsupportnumber.comparent' is not a valid 'Hostname'

Apr 10 15:20:48 MachineName celery[92725]: [2018-04-10 15:20:48,691: ERROR/ForkPoolWorker-1] 'system.securityerror0x080579b.xyzcool' is not a valid 'Hostname'
```

**Comment by tomchop** [comment]
I agree it would be nice to have, but just FYI this feeds are failing because there `.comparent` and `.xyzcool` are not valid TLDs (I think at least)

**Comment by scrublullz** [comment]
Correct. I want to get with the owner of the list to see if they are having parsing issues or if they have a bad source providing URLs without the `/` between the TLD and directory/page.  Likely a parsing issue.
