### ISSUE TITLE
Bug: Hybrid Analysis feed does not tag all fields for the same data

### ISSUE THREAD

**Issue by scrublullz** [yeti-platform/yeti#256]
Only the value of the `FILE:<SHA256>` shows the proper tags and source.  The other attributes to the same record do not have tags nor source.

most recent `git pull`:
`19d16f0..39ac45d  master     -> origin/master`

Behavior Observed:
![screenshot from 2018-04-12 09-23-47](https://user-images.githubusercontent.com/16104066/38683516-477ab4c4-3e33-11e8-8301-fb783a48d802.png)

**Comment by tomchop** [comment]
This is WAI. 

The `FILE:` observable is the actual file: it contains references to filenames seen in the wild and the actual file contents when available.

The other observables you see are just hashes. Every `FILE:` observable is linked to the three hashes (SHA256, SHA1, MD5). 

If you have other, more intuitive ways to represent the semantic difference between an actual file observable and it's cryptographic hash, I'm all ears! :)
