### ISSUE TITLE
Context For Observables Imported from Investigations

### ISSUE THREAD

**Issue by ag100** [yeti-platform/yeti#261]
Hello,

When importing observables from a web page or PDF, the observables are created, but when an one of these observables is viewed individually, there is no context/source to indicate where it originated from, or why it was created.  I know they can be tagged, but I know I would see value it at least including the report name/URL in the description or source.  Thoughts?  Thanks!

**Comment by tomchop** [comment]
Yes, this would be a good addition.

**Comment by villain** [comment]
+1 for this
