### ISSUE TITLE
Unable to "View Source" of Investigation After Name Change

### ISSUE THREAD

**Issue by ag100** [yeti-platform/yeti#262]
Hey - Wanted to open an issue on this as we've noted this a few times.  Thanks!

### Steps to Reproduce

- Start a new investigation from an import using a PDF/URL/Text.  Import the observables.
- Go back to the investigations list.  With PDF/Text, it is often untitled (understood as to why)
- Open the investigation you created and edit the name.
- The button to see the original source data which was there prior to renaming the investigation is now gone.

#### Expected behavior
The view-source button should be there following the name change.

**Comment by tomchop** [comment]
Assigning this to Gael :)
