### ISSUE TITLE
Multiple tag placement after import

### ISSUE THREAD

**Issue by chenerlich** [yeti-platform/yeti#266]
### Description
When you import a blog for example, there are multiple IOCs, and you have to go each one adding tags.

#### Expected behavior
Adding the same tag for multiple IOCs

#### Actual behavior
Going every IOC and adding manually tags

**Comment by ag100** [comment]
While possibly not what you're looking for, if you go to the graph view of the investigation and select all nodes, you can add/remove tags for all related observables from there.

Aaron

**Comment by chenerlich** [comment]
@ag100, nice!
But yet not as comfortable.
