### ISSUE TITLE
web interface doesn't work properly

### ISSUE THREAD

**Issue by fredisanmar** [yeti-platform/yeti#269]
### Description
the web interface doesn't look as the images on your website. it apears on top of the web a big area showing a message that says drag and drop files. and the other fields looks like links and when you press them the content appears in the bottom of the web.
![captura de pantalla de 2018-06-26 18-11-50](https://user-images.githubusercontent.com/40606800/41925314-8da7f154-796c-11e8-8c4d-c86025728628.png)

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log | head -n1` to find out
| OS version       | Kali linux 2018.2, debian 9.0
| Browser          | firefox

### Steps to Reproduce
1. cd yeti/
1. ./yeti.py webserver
1. go web browser and enter the direction

#### Expected behavior
load properly the web interface

#### Actual behavior
the interface dont loads properly

**Comment by sebdraven** [comment]
In yeti folder do you bave launch yarn install ?

**Comment by fredisanmar** [comment]
yes, i did

**Comment by tomchop** [comment]
That's very strange. Have you tried reloading the webpage and clearing your cache?

Can you please paste the output of the `yarn install` command you ran?

**Comment by fredisanmar** [comment]
the output of yarn install is: 
yarn install v1.7.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.10s.

i wil try now to clear the cache

**Comment by fredisanmar** [comment]
i cleared the cache and the same happens

**Comment by fredisanmar** [comment]
most of the js and css dont load.
![captura de pantalla de 2018-06-26 19-21-10](https://user-images.githubusercontent.com/40606800/41928657-2eface06-7976-11e8-875e-154d02a65504.png)

**Comment by fredisanmar** [comment]
guys thanks 
now its working.

**Comment by fredisanmar** [comment]
i just reinstall yarn

**Comment by tomchop** [comment]
Thanks for confirming it works!

**Comment by fredisanmar** [comment]
its a very good tool.
