### ISSUE TITLE
celery issues on Centos prevent feeds and system pages working (similar to #220)

### ISSUE THREAD

**Issue by jmckinlay** [yeti-platform/yeti#276]
### Description
Feed page draws but doesnt update
System page timesout
behaves same from nginx or direct to uwsgi presented port 8000

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 705ba1e453cc94cfbe593342fa3c7e2e4c53f62a
| OS version       | Centos7.5
| uname-a | Linux 3.10.0-862.9.1.el7.x86_64 #1 SMP 
| Browser          | Chrome Version 67.0.3396.99

### Steps to Reproduce
Installed using extras/centos_bootstrap
and extras/systemd services
and uwsgi tweak from issue #82 

#### Expected behavior
similar to #220 

#### Actual behavior
similar to #220

**Comment by jmckinlay** [comment]
FIXED 

the centos_bootstrap script installs redis but doesn't start or enable it - celery needs a message broker like redis

**Comment by tomchop** [comment]
Ha, so you mean that centos_bootstrap does not install redis by default? I'll close this issue and open a separate one to track that. Thanks! (and feel free to reopen if you think this warrants further discussion)

**Comment by tomchop** [comment]
@jmckinlay Any chance you can tell us what you added to the script to get redis started?

**Comment by jmckinlay** [comment]
sudo systemctl enable redis
sudo systemctl start redis

**Comment by jmckinlay** [comment]
even tho it is redis-server under covers , systemctl expects "redis"

**Comment by jmckinlay** [comment]
and script wont need sudo - that is for my octopusdeploy calamari process

**Comment by tomchop** [comment]
OK sounds like an easy change to push. Any idea why this is necessary with redis and not other services e.g. mongo?

**Comment by jmckinlay** [comment]
there is a line for mongo near the bottom of the script, 

some installers but not all start a service , but very few "enable" service for start on boot
