### ISSUE TITLE
out of box /extras/systemd not happy on centos7.5

### ISSUE THREAD

**Issue by jmckinlay** [yeti-platform/yeti#278]
### Description
after following /extras/centos_bootstrap.sh - none of the services start

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 705ba1e
| OS version       | Centos7.5
| Browser          | Chrome Version 67.0.3396.99

### Steps to Reproduce
Installed using extras/centos_bootstrap
and extras/systemd services
and uwsgi tweak from issue #82

#### Expected behavior
Services to run at start up

#### Actual behavior

[ ~]$ sudo systemctl list-units --state=failed

  UNIT                   LOAD   ACTIVE SUB    DESCRIPTION
● rngd.service           loaded failed failed Hardware RNG Entropy Gatherer Daemon
● yeti_analytics.service loaded failed failed Yeti workers - Analytics
● yeti_beat.service      loaded failed failed Yeti beat scheduler
● yeti_exports.service   loaded failed failed Yeti workers - Exports
● yeti_feeds.service     loaded failed failed Yeti workers - Feeds
● yeti_oneshot.service   loaded failed failed Yeti workers - Oneshot
● yeti_uwsgi.service     loaded failed failed Yeti UWSGI server

**Comment by jmckinlay** [comment]
FIXED,

the centos_bootstrap does not create the user "yeti" but the systemd files tell the services to start as user yeti

a scriptable way of doing this on centos would be

useradd -m yeti
usermod -aG wheel yeti
echo yeti:<change_me> | chpasswd

**Comment by jmckinlay** [comment]
Best fix so far is to remove line 

user=yeti from the [service] section of the yeti_*.service unit files

**Comment by tomchop** [comment]
Weird, what kind of error do you get when removing the yeti user? The ubuntu scripts has yeti services run under a different user just so it doesn't run as root, so adding the user (or alternatively removing the `user=yeti` line) should make things work. Do you have a more detailed error message?

**Comment by jmckinlay** [comment]
the other problem was ...

in CENTOS75 celery is found in /usr/bin not /usr/local/bin so we need a soft link or a different unit file

I would suggest under extras we have a  debian/ubunti folder and a centos folder because

nginx is different
systemd is different
package names are different

I would be happy to help as work in both ubuntu16 and centos7

**Comment by tomchop** [comment]
The systems seem to have more difference than anticipated so I agree it makes sense to have different directories. You're more than welcome to submit a PR if you have the bandwidth @jmckinlay, it would be much appreciated!

**Comment by jalbrizio** [comment]
I put yeti in /opt to fix this.  below are the commands I ran to get it working in centos 7.5 
__________
#Start Script
#!/bin/bash
yum install vim curl wget net-tools nginx
cd /opt
git clone https://github.com/yeti-platform/yeti.git
pip install django libtaxii pyOpenSSL uwsgi cabby django-solo taxii_services python-dateutil
pip install -r requirements.txt
yarn install
cd yeti

PWD1=`pwd`
sudo chmod +x $PWD1/extras/centos_bootstrap.sh
sudo chmod +x $PWD1/extras/systemd/*
sed -i s'/\/usr\/local\/bin/\/bin/g' $PWD1/extras/systemd/*
sudo ln -s $PWD1/extras/systemd/* /lib/systemd/system/

nohup $PWD1/extras/centos_bootstrap.sh &


systemctl list-unit-files | grep yeti

sudo systemctl enable yeti_web.service
sudo systemctl enable yeti_analytics.service
sudo systemctl enable yeti_beat.service
sudo systemctl enable yeti_exports.service
sudo systemctl enable yeti_feeds.service
sudo systemctl enable yeti_oneshot.service
sudo systemctl enable yeti_uwsgi.servic

sudo systemctl restart yeti_web.service
sudo systemctl restart yeti_analytics.service
sudo systemctl restart yeti_beat.service
sudo systemctl restart yeti_exports.service
sudo systemctl restart yeti_feeds.service
sudo systemctl restart yeti_oneshot.service
sudo systemctl restart yeti_uwsgi.service

ls plugins/feeds/public/ | sed s/\.pyc//g | sed s/\.py//g | sed s/^/python\ testfeeds.py\ /g > /opt/yeti/process-feeds.sh

grep "(Feed)"  plugins/feeds/public/*.py | awk -F : '{print $2}'| sed s/\class\ //g | sed s/\(Feed\)//g | sed s/^/python\ testfeeds.py\ /g > /opt/yeti/process-feeds.sh


chmod +x /opt/yeti/process-feeds.sh
cd /opt/yeti/
./process-feeds.sh
#End script
__________
my script is here if you want it.

https://github.com/jalbrizio/yeti-CENTOS-installer.git
I still have a few issues but for the most part, it works. 
I am opening a new issue for the other issues I am running into.

**Comment by tomchop** [comment]
Thanks a lot @jalbrizio ! Do you know what should be changed in https://github.com/yeti-platform/yeti/blob/master/extras/centos_bootstrap.sh for it to work correctly?

**Comment by jalbrizio** [comment]
on line 8  change $releasever to \$releasever

add a line  before line28  the does a cd /opt
add  yum -y install vim curl wget net-tools nginx
add pip install django libtaxii pyOpenSSL uwsgi cabby django-solo taxii_services python-dateutil
 line 32 add
PWD1=`pwd`

sudo chmod +x $PWD1/extras/systemd/*
sed -i s'/\/usr\/local\/bin/\/bin/g' $PWD1/extras/systemd/*
sudo ln -s $PWD1/extras/systemd/* /lib/systemd/system/

line 46  replace it with  the below

sudo systemctl enable yeti_web.service
sudo systemctl enable yeti_analytics.service
sudo systemctl enable yeti_beat.service
sudo systemctl enable yeti_exports.service
sudo systemctl enable yeti_feeds.service
sudo systemctl enable yeti_oneshot.service
sudo systemctl enable yeti_uwsgi.servic

sudo systemctl start yeti_web.service
sudo systemctl start yeti_analytics.service
sudo systemctl start yeti_beat.service
sudo systemctl start yeti_exports.service
sudo systemctl start yeti_feeds.service
sudo systemctl start yeti_oneshot.service
sudo systemctl start yeti_uwsgi.service

**Comment by jalbrizio** [comment]
Sorry for the comment edit. I had to add an extra backslash to the comment because github removed it from being visible without the extra one.

**Comment by jalbrizio** [comment]
I noticed that the feeds dont run automaticly so you can also add the below to the end.
#
cd $PWD1
ls plugins/feeds/public/ | sed s/\.pyc//g | sed s/\.py//g | sed s/^/python\ testfeeds.py\ /g > $PWD1/process-feeds.sh

grep "(Feed)"  plugins/feeds/public/*.py | awk -F : '{print $2}'| sed s/\class\ //g | sed s/\(Feed\)//g | sed s/^/python\ testfeeds.py\ /g > $PWD1/process-feeds.sh

chmod +x $PWD1/process-feeds.sh

./process-feeds.sh
#

**Comment by jalbrizio** [comment]
also add 
systemctl enable redis

systemctl start redis

**Comment by jalbrizio** [comment]
also add 
chown yeti:yeti /opt/yeti/exports

**Comment by jalbrizio** [comment]
I added a pull request to be reviewed.

**Comment by jalbrizio** [comment]
Here is the pull request if you want to merge the fixes for it.
https://github.com/yeti-platform/yeti/pull/305

**Comment by tomchop** [comment]
Travis is failing due to an exception raised by requests, this has nothing to do with your PR :)

**Comment by jalbrizio** [comment]
This should be fixed with the latest commit.

**Comment by tomchop** [comment]
Fixed in #305
