### ISSUE TITLE
Unbalanced quotes in systemd scripts

### ISSUE THREAD

**Issue by daniel-gallagher** [yeti-platform/yeti#28]
Just a quick fix in the install docs. The systemd scripts for "Feeds" and "Exports" have unbalanced quotes.

[https://github.com/daniel-gallagher/yeti/commit/b6597582b8ed43d3ea344e0a7ec5afb2f7054e8d](https://github.com/daniel-gallagher/yeti/commit/b6597582b8ed43d3ea344e0a7ec5afb2f7054e8d)

**Comment by tomchop** [comment]
Thanks!
