### ISSUE TITLE
ResolveHostnames: ERROR

### ISSUE THREAD

**Issue by villain** [yeti-platform/yeti#286]
running the latest version of yeti (although not sure its applicable) .. i have noticed ResolveHostnames in my instance of yeti has a status of ERROR

how would one go about seeing the log output for the analytics services? i can't seem to find a log under /opt/yeti

**Comment by tomchop** [comment]
You can check out the logs for the analytics service: `journalctl -u yeti_analytics.service`.

> Running the latest version of yeti (although not sure its applicable) 

What do you mean by not applicable?

**Comment by villain** [comment]
ah, meaning its probably a bad domain (eg; unrecognised tld) thats been added

running 'journalctl -u yeti_analytics.service' produces nothing of value;

# journalctl -u yeti_analytics.service
-- Logs begin at Tue 2018-08-21 21:34:29 AEST, end at Tue 2018-08-21 21:53:13 AEST. --
Aug 21 21:34:32 yeti-host systemd[1]: Started Yeti workers - Analytics.

**Comment by tomchop** [comment]
What about `systemctl status yeti_analytics.service` ? You can use the `-n X` flag to display the last `X` lines.

**Comment by villain** [comment]
looks like it was something messed up in the build. rebuilt the host and all is well
