### ISSUE TITLE
How do I determine, from the logs, whether an investigation import is actually working?

### ISSUE THREAD

**Issue by smclinden** [yeti-platform/yeti#292]
I started an import of this URL:

http://www.viruss.eu/news/lazarus-under-the-hood/

and it has been running for over an hour. The uWSGI logs contain thousands of lines like these, below:

[pid: 26402|app: 0|req: 2069/2942] 10.10.81.167 () {44 vars in 1175 bytes} [Tue Sep 11 07:25:17 2018] GET /api/investigation/import_results/5b97c40617a1c26721f00873 => generated 146 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 26402|app: 0|req: 2070/2943] 10.10.81.167 () {44 vars in 1175 bytes} [Tue Sep 11 07:25:18 2018] GET /api/investigation/import_results/5b97c40617a1c26721f00873 => generated 146 bytes in 8 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 1)
[pid: 26402|app: 0|req: 2071/2944] 10.10.81.167 () {44 vars in 1175 bytes} [Tue Sep 11 07:25:19 2018] GET /api/investigation/import_results/5b97c40617a1c26721f00873 => generated 146 bytes in 9 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 26402|app: 0|req: 2072/2945] 10.10.81.167 () {44 vars in 1175 bytes} [Tue Sep 11 07:25:20 2018] GET /api/investigation/import_results/5b97c40617a1c26721f00873 => generated 146 bytes in 6 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 1)
[pid: 26402|app: 0|req: 2073/2946] 10.10.81.167 () {44 vars in 1175 bytes} [Tue Sep 11 07:25:21 2018] GET /api/investigation/import_results/5b97c40617a1c26721f00873 => generated 146 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)

**Comment by gaelmuller** [comment]
Investigation imports require the `oneshot` worker. Is it running ? If so, check its logs instead of the web server's.

**Comment by smclinden** [comment]
That was it. I didn't realize that celery was sending messages via syslog.
