### ISSUE TITLE
Investigations/Import not identifying Registry/Pathnames observables

### ISSUE THREAD

**Issue by smclinden** [yeti-platform/yeti#295]
I've been testing Yeti and importing various reports and noticed that I don't, typically, see registry information is imported as Observables.

If I am doing something wrong, please let me know what I should do differently.

If this is a feature that needs to be added, please let me know where would be the best place to add it in the source code.

Thanks.

**Comment by tomchop** [comment]
We don't support registry observables as of yet. Of course this would be extremely valuable, but modeling an accurate representation of registry keys is not trivial - we just haven't gotten around to it yet.

You can start experimenting by creating a new type here: https://github.com/yeti-platform/yeti/tree/master/core/observables. Hopefully the other "type" examples will be clear enough for you to start experimenting!

Feel free to ping us if you still need help :)

**Comment by smclinden** [comment]
Thanks. I love writing parsers so I'll have fun taking a crack at it.

**Comment by smclinden** [comment]
Ok, so as an exemplar, I used this: https://www.us-cert.gov/ncas/alerts/TA18-201A

The end of the document contains both registry entries and pathnames, yet none of the pathnames are extracted as observables. I haven't delved into the code, yet, but is there a simple explanation?

**Comment by tomchop** [comment]
Is the webpage correctly parsed as markdown (i.e. do you see all the text and filepaths in the generated markdown?)

**Comment by smclinden** [comment]
The text is registered down to and including the <div> containing the file paths.

Images are not included and neither are the headings <h3>.

The text following the <div> reference, above, is omitted.

**Comment by smclinden** [comment]
So, help me to understand. Does Yeti convert HTML to Markdown, before processing it for observables?

I could read through the code to get the answer but knowing the answer would simplify looking for the solution.

**Comment by smclinden** [comment]
The reason that I ask is that the Markdown for the relevant sections of the page in question is:

**Example Filenames and Paths:**

`C:\Users\<username>\AppData \Local\Microsoft\Windows\shedaudio.exe`

`C:\Users\<username>\AppData\Roaming\Macromedia\Flash Player\macromedia\bin\flashplayer.exe`

**Typical Registry Keys:**

`HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run`

`HKEY_LOCAL_MACHINE\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Run`

`HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run`

**System Root Directories:**

`C:\Windows\11987416.exe`

`C:\Windows\System32\46615275.exe`

`C:\Windows\System32\shedaudio.exe`

`C:\Windows\SysWOW64\f9jwqSbS.exe`

Which means that the RE expression which would match would be r"""([`]*[A-X]:\\|/[`]*)"""

**Comment by gaelmuller** [comment]
Yes, HTML is converted to markdown before parsing. All observables are not automatically extracted when importing investigations (see https://github.com/yeti-platform/yeti/blob/master/core/observables/observable.py, line 115).

The main reason is that it can be quite difficult to create a good regex / validation process for pathnames.

**Comment by smclinden** [comment]
Understood about the pathnames, but there is a separate issue that the parsing seems to break just beyond the above expression. Also, headings of the form ### are not being rendered, at all, in the left window.

**Comment by smclinden** [comment]
Can I assume that core/observables/path.py is a placeholder for some greater functionality in the future?

**Comment by tomchop** [comment]
Yes, thats completely fair to assume. FWIW, we are currently working hard on version 2 of Yeti, so expect further developments there. You can take a look at https://github.com/yeti-platform/TibetanBrownBear

**Comment by smclinden** [comment]
Well, I've modified my local copy of path.py and related files to do a better job of parsing file names and making them observables (the perfect being the enemy of the good, I couldn't make it work with regular expressions, alone) and it seems to be doing ok albeit it is not hugely efficient.
