### ISSUE TITLE
Feature Request: MITRE ATT&CK Framework  

### ISSUE THREAD

**Issue by shaunh87** [yeti-platform/yeti#298]
More organizations than ever are adopting the MITRE framework, and its slowly becoming industry standard (Hybrid Analysis, AnyRun and SANS to name a few). 

Would it be possible to incorporate the MITRE ATT&CK framework into YETI? I know there's already a “TTP” section (Kill Chain), but I believe ATT&CK would add extra value, and will allow for better link analysis between Actors, Malware and TTPs. Especially if you could leverage the MITRE API to pre-populate the data..

https://attack.mitre.org/wiki/Main_Page
https://mitre.github.io/attack-navigator/enterprise/

Thanks..

**Comment by villain** [comment]
+1

**Comment by tomchop** [comment]
You'll be happy to learn that this is already a thing in the v2 of Yeti we're currently working on: https://github.com/yeti-platform/TibetanBrownBear

There's still some work to do until we start publicizing it more widely but feel free to try it out!

**Comment by premum** [comment]
Hi team
Is there any update in this MITRE ATTACK integration with Yeti platform.
I was working with generic docker images and wonder whether yeti support MITRE database or not.

Is the integration ready now ..

**Comment by sebdraven** [comment]
Yep It's in TiberianBrownBear. I close this issue.
