### ISSUE TITLE
Upstream timeout errors.

### ISSUE THREAD

**Issue by smclinden** [yeti-platform/yeti#303]
I'm getting Yeti upstream timeout errors when called from FAME. Any suggestions as to how I should debug these?

2018/10/11 12:51:03 [error] 31860#31860: *1772 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.23.28.110, server: REDACTED, request: "POST /api/analysis/match HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "REDACTED:8080"
2018/10/11 12:52:05 [error] 31860#31860: *1802 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.23.28.110, server: REDACTED, request: "POST /api/analysis/match HTTP/1.1", upstream: "uwsgi://127.0.0.1:8000", host: "REDACTED:8080"

The uWSGI log entries are:

[pid: 4589|app: 0|req: 1047/1503] 172.23.28.110 () {46 vars in 738 bytes} [Thu Oct 11 12:50:01 2018] POST /api/analysis/match => generated 1493 bytes in 1705 msecs (HTTP/1.1 200) 2 headers in 73 bytes (1 switches on core 1)
[pid: 4589|app: 0|req: 1049/1504] 172.23.28.110 () {46 vars in 740 bytes} [Thu Oct 11 12:51:03 2018] POST /api/analysis/match => generated 223 bytes in 200 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 1)
[pid: 4588|app: 0|req: 269/1505] 172.23.28.110 () {46 vars in 740 bytes} [Thu Oct 11 12:51:03 2018] POST /api/analysis/match => generated 171 bytes in 9 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 1)
[pid: 4589|app: 0|req: 1050/1506] 172.23.28.110 () {46 vars in 740 bytes} [Thu Oct 11 12:51:03 2018] POST /api/analysis/match => generated 238 bytes in 119 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 1)
[pid: 4588|app: 0|req: 270/1507] 172.23.28.110 () {46 vars in 740 bytes} [Thu Oct 11 12:51:03 2018] POST /api/analysis/match => generated 608 bytes in 1798 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 4588|app: 0|req: 271/1508] 172.23.28.110 () {46 vars in 740 bytes} [Thu Oct 11 12:52:05 2018] POST /api/analysis/match => generated 608 bytes in 1861 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 1)
[pid: 4588|app: 0|req: 272/1509] 172.23.28.110 () {46 vars in 738 bytes} [Thu Oct 11 12:52:07 2018] POST /api/analysis/match => generated 109 bytes in 9 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1 switches on core 0)
[pid: 4585|app: 0|req: 79/1510] 172.23.28.110 () {46 vars in 740 bytes} [Thu Oct 11 12:52:07 2018] POST /api/analysis/match => generated 610 bytes in 1877 msecs (HTTP/1.1 200) 2 headers in 72 bytes (1switches on core 1)
[pid: 4588|app: 0|req: 273/1511] 172.23.28.110 () {46 vars in 740 bytes} [Thu Oct 11 12:52:09 2018] POST /api/analysis/match => generated 2767 bytes in 1921 msecs (HTTP/1.1 200) 2 headers in 73 bytes(1 switches on core 1)

**Comment by tomchop** [comment]
How may observables are in the FAME results? How many observables do you have in your DB? There's a known issue where this can timeout. I'll see if I can come up with a fix later next week.

**Comment by smclinden** [comment]
I had, originally, selected around 20 observables, but it timed out even with 1. The current observable database has 1,476,511 observables and is about 2GB in size.

**Comment by tomchop** [comment]
Hm that's not normal. If you can capture the full HTTP request that did this, that would be super helpful.

Note that this may also depend on the type of observable you're submitting. If it has many neighbors associated with it (e.g. a subdomain linked to a domain that has several thousands subdomains), it may cause some slowdown or even timeouts depending on the amount of connected nodes. Do you think this might be the case?

I'll try to come up with a fix to prevent this behavior from happening. Once that is ready, is it possible for you to run code from a different Yeti branch (i.e. using `git checkout`)?

**Comment by smclinden** [comment]
I'm trying to capture the full HTTP request but when I enable the echo module in nginx, it doesn't show any access. Strange.

**Comment by tomchop** [comment]
I suggest you use Chrome developer tools for that, it native and displays all requests issued by your browser

**Comment by smclinden** [comment]
The problem might be with Fame. I'm getting a 500 error https://{fame server}/{hash}/submit_iocs/Yeti

Method Not Allowed

**Comment by smclinden** [comment]
This appears to be a problem related to the use of HTTPS and the POST method. If I open an insecure Web port for Yeti, it has no problems acccepting the post. I also removed the nginx directive forcing HTTP2 although I am not sure that this was the issue.

**Comment by tomchop** [comment]
Huh, I wouldn't have thought that this could come from TLS or not. I'll ping other people running into the same issue to see if they were having this setup, too.
