### ISSUE TITLE
url:5000/system hangs

### ISSUE THREAD

**Issue by jalbrizio** [yeti-platform/yeti#304]
Before opening an issue, please make do a quick search through the current issues
and the mailing list (https://groups.google.com/forum/#!forum/yeti-users) to see
if it hasn't been answered already.

### Description
[Please provide a description of the issue encountered]

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 56cd9e847c6e6f39656a48999f4439fdaf693d9d
| OS version       | Centos 7.5
| Browser          | Chrome Version 67.0.3396.99 (Official Build) (64-bit)  

### Steps to Reproduce
1. install centos
2. use https://github.com/jalbrizio/yeti-CENTOS-installer.git to install yeti  fairly standard
3. go to my workstation and open a browser  log in
4. go to /system 

#### Expected behavior
[How are you expecting the application to behave?]
I expected a system page to open

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]
/system spins and never opens.

**Comment by tomchop** [comment]
This is "slightly" normal since the `/system` page queries Celery for data and Celery takes a long time to respond. This, by the way, begs the question: are the Celery workers and schedulers set up and running correctly?

**Comment by jalbrizio** [comment]
that's a good question. I'm not familiar with celery where can I go to find out?
Does a pip install celery install them and the bootstrap set them up properly?
 here is my ps results 

ps -ef| grep yeti
yeti      3648     1  0 Oct18 ?        00:29:02 python /opt/yeti/yeti.py webserver
yeti      3659     1  0 Oct18 ?        00:00:59 /usr/bin/python2 /bin/celery -A core.config.celeryctl.celery_app worker -Ofair -c 10 --purge -Q analytics -n analytics
yeti      3690     1  0 Oct18 ?        00:01:01 /usr/bin/python2 /bin/celery -A core.config.celeryctl.celery_app worker -Ofair -c 8 -Q exports -n exports --purge
yeti      3705     1  0 Oct18 ?        00:01:01 /usr/bin/python2 /bin/celery -A core.config.celeryctl.celery_app worker -Ofair -c 8 -Q feeds -n feeds --purge
yeti      3720     1  0 Oct18 ?        00:00:59 /usr/bin/python2 /bin/celery -A core.config.celeryctl.celery_app worker -c 4 -Q oneshot -n oneshot --purge
yeti      3748     1  0 Oct18 ?        00:01:50 /bin/uwsgi --socket 0.0.0.0:8000 -w yeti --callable webapp --processes 4 --threads 2 --stats 127.0.0.1:9191
yeti      3769  3748  0 Oct18 ?        00:00:00 /bin/uwsgi --socket 0.0.0.0:8000 -w yeti --callable webapp --processes 4 --threads 2 --stats 127.0.0.1:9191
yeti      3770  3748  0 Oct18 ?        00:00:00 /bin/uwsgi --socket 0.0.0.0:8000 -w yeti --callable webapp --processes 4 --threads 2 --stats 127.0.0.1:9191
yeti      3771  3748  0 Oct18 ?        00:00:00 /bin/uwsgi --socket 0.0.0.0:8000 -w yeti --callable webapp --processes 4 --threads 2 --stats 127.0.0.1:9191
yeti      3772  3748  0 Oct18 ?        00:00:00 /bin/uwsgi --socket 0.0.0.0:8000 -w yeti --callable webapp --processes 4 --threads 2 --stats 127.0.0.1:9191

**Comment by jalbrizio** [comment]
I found the fix. in centos you have to do a systemctl enable redis and systemctl start redis
then it works. thanks.
