### ISSUE TITLE
Search assistance

### ISSUE THREAD

**Issue by jalbrizio** [yeti-platform/yeti#307]
How can i search for anything that's in the feed source or analytics source? source=feed didn't find anything.
Can i use variables in an attribute search like not null or not equal to or if i have have multiple tags with similar names like tag=alien* ?
What's the attribute list i can use to query?

**Comment by tomchop** [comment]
You're almost there. You need to use mongo's dot notation to do that:

`context.source=HybridAnalysis` will bring up all observables that look like 

```json
{
 "value": "something.com",
 "context": {
    "source": "HybridAnalysis",
    "threatlevel_human": "malicious",
    ...
  }
}
```

Searching for `context.threatlevel_human=malicious` will also match the above document.

You can't use "variables", but you can use regular expressions in what you search for by checking the `Regex search`. So something like:

`context.threatlevel_human=malic\w+$`

There's a special shorthand for tags:

`tags=rat` will show all observables that are tagged with `rat`
`tags=rat,adlibraryjpush` will show all observables tagged `rat` **and** `adlibraryjpush`

Finally, all attributes in an observable are queryable. The most useful are often `context` attributes, which are represented in boxes in the observable detail page.

**Comment by tomchop** [comment]
Yup, you can do that by appending `__ne` at the end of the key to your query. So to exclude all observables tagged `tor` from results:

`tags__name__ne=tor` (in this case the `tags` shorthand doesn't work, so you need to specify the full path to what you want to search)

Also, just FYI, `context.source=\w+$` will return all observables added from a feed named `\w+$`, which is basically all feeds named with alphanumeric chars (which basically means all of them). Not sure if you were using this as an example or if you were trying to achieve something else :)

**Comment by jalbrizio** [comment]
Awesome, thanks, these are my examples I am documenting.

**Searching with tags and contexts**
context.source=AlienVaultIPReputation tags=tor

**searching with variables examples**
context.source=Alien\w+$
context.source=\w+$
tags=mycustomtag$ context.source=\w+$ 
tags=mycustomtag2$ context.source=\w+$ 

**to exclude all items taged with tor example**
tags__name__ne=tor
