### ISSUE TITLE
Misp feed fails

### ISSUE THREAD

**Issue by thevidocq** [yeti-platform/yeti#314]
Before opening an issue, please make do a quick search through the current issues
and the mailing list (https://groups.google.com/forum/#!forum/yeti-users) to see
if it hasn't been answered already.

### Description
MISP feed integration fail

### Environment

Ubuntu 18.04

### Steps to Reproduce

python testfeeds.py Misp-Feed

#### Expected behavior
MISP attributes on YETI

#### Actual behavior

root@host:~/yeti# python testfeeds.py Misp-Feed
DEBUG:root:Scheduler started
Running Misp-Feed...
DEBUG:root:Running Misp-Feed (ID: 5bf354872eec1859bdfca5e5)
DEBUG:root:Processing instance misp_1
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): misp.example.com:443
DEBUG:urllib3.connectionpool:https://misp.example.com:443 "GET /organisations/index/scope:all HTTP/1.1" 200 None
DEBUG:root:Getting all events for misp_1
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): misp.exame.com:443
DEBUG:urllib3.connectionpool:https://misp.example.com:443 "POST /events/restSearch HTTP/1.1" 200 None
ERROR:root:Traceback (most recent call last):
  File "/root/yeti/core/feed.py", line 42, in update_feed
    f.update()
  File "/root/yeti/plugins/feeds/public/misp.py", line 151, in update
    self.get_all_events(instance)
  File "/root/yeti/plugins/feeds/public/misp.py", line 131, in get_all_events
    for date_from, date_to, imported in self.week_events(instance):
  File "/root/yeti/plugins/feeds/public/misp.py", line 104, in week_events
    self.analyze(event['Event'], instance)
  File "/root/yeti/plugins/feeds/public/misp.py", line 177, in analyze
    galaxies = self.instances[instance]['galaxy_filter'].split(',')
AttributeError: 'NoneType' object has no attribute 'split'

ERROR:root:ERROR updating feed: 'NoneType' object has no attribute 'split'

**Comment by thevidocq** [comment]
MISP 2.4.97

Many thanks.

**Comment by viszsec** [comment]
> Yeti.conf misp conf
> 
> [misp]
> 
> ## Use this setting in order to specify a comma-separated list of MISP instances
> ## that should be taken into account by the MISP feed.
> instances = misp_1
> 
> [misp_1]
> 
> ## For each instance in the 'misp.instances' setting, you should specify a
> ## configuration block with this format, in order to specify at least the URL
> ## and the auth key.
> name = MISP_1
> url = https://misp.example.com
> key = validAPIkey

Hi thevidocq,

Do you where can i find those config in the latest misp version? Couldnt find those two config items. Yeti conf and misp conf.

Im trying to push feeds from MISP to Yeti. Many thanks.
