### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by hhiggins99** [yeti-platform/yeti#315]
### Description
I am attempting to install Yeti and am running into issues getting it installed.

### Environment

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 18.04 or 14

### Steps to Reproduce
1.sudo apt-get install build-essential git python-dev mongodb redis-server libxml2-dev libxslt-dev zlib1g-dev python-virtualenv wkhtmltopdf
2. curl -sSk https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
 - I had to add the "k" flag as I was getting SSL certificate errors
3. echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
4. sudo apt-get update && sudo apt-get install yarn
5. git clone https://github.com/yeti-platform/yeti.git
-FATAL: unable to access 'https://github.com/yeti-platform/yeti.git/': server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLFile:none

Thanks

**Comment by tomchop** [comment]
Looks like your system has trouble with x509 certificates. Try running `sudo dpkg-reconfigure ca-certificates` before running the install scripts.
