### ISSUE TITLE
Webserver SSL Support

### ISSUE THREAD

**Issue by motox1** [yeti-platform/yeti#323]
Does the current version of yeti support SSL for the webserver UI Interface ? If so how can I enable this feature?

**Comment by tomchop** [comment]
I'm not sure if the flask webserver handles TLS connections, but if SSL is something you want, you should follow the [prod setup](https://yeti-platform.readthedocs.io/en/latest/installation.html#production-use) procedures that uses nginx, and serve your SSL connections through there.
