### ISSUE TITLE
Docker Installation error 

### ISSUE THREAD

**Issue by taogoldi** [yeti-platform/yeti#324]
Hello Yeti Team,

I am getting the following error during a Docker compose-up command:

> st = 127.0.0.1/host = redis/' yeti.conf
>  ---> Running in 9c2554394ef8
> Exception:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
>     status = self.run(options, args)
>   File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 305, in run
>     wheel_cache
>   File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 291, in populate_requirement_set
>     requirement_set.add_requirement(req)
>   File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 224, in add_requirement
>     if not install_req.match_markers():
>   File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 823, in match_markers
>     return Marker(self.markers).evaluate()
>   File "/usr/share/python-wheels/packaging-16.6-py2.py3-none-any.whl/packaging/markers.py", line 278, in evaluate
>     return _evaluate_markers(self._markers, current_environment)
>   File "/usr/share/python-wheels/packaging-16.6-py2.py3-none-any.whl/packaging/markers.py", line 203, in _evaluate_markers
>     lhs_value = _get_env(environment, lhs.value)
>   File "/usr/share/python-wheels/packaging-16.6-py2.py3-none-any.whl/packaging/markers.py", line 185, in _get_env
>     "{0!r} does not exist in evaluation environment.".format(name)
> UndefinedEnvironmentName: 'extra' does not exist in evaluation environment.
> You are using pip version 8.1.1, however version 18.1 is available.
> You should consider upgrading via the 'pip install --upgrade pip' command.
> ERROR: Service 'yeti' failed to build: The command '/bin/sh -c pip  install -r requirements.txt &&         pip install uwsgi &&         yarn install &&         mv yeti.conf.sample yeti.conf &&         sed -i '9s/# host = 127.0.0.1/host = mongodb/' yeti.conf &&         sed -i '22s/# host = 127.0.0.1/host = redis/' yeti.conf' returned a non-zero code: 2
> 

Can you advise on how to fix please?

**Comment by tomchop** [comment]
Can you give us a bit more details on what platform & version of Docker you're using ? Also, the exact commands up to the error would be helpful :) Thanks!

**Comment by taogoldi** [comment]
yes sure. I used your instructions to download Yeti and run the following compose command:

> docker-compose up 

 The error above was produced during the installation process. 

Here is the docker information:

Version 2.0.0.0-mac81 (29211)
Engine: 18.09.0
Compose: 1.23.2

Let me know if you need anything else and I will be glad to assist. :)

**Comment by tomchop** [comment]
Have you tried running `docker-compose up -f docker-compose-full.yml`?

`docker-compose up` defaults to `docker-compose.yml`, which is the standalone Yeti web service (no mongo, no redis, which seems to be what is causing problems in your case)

**Comment by taogoldi** [comment]
The fix appear to have resolved this issue. Thank you Tom.

**Comment by tomchop** [comment]
No worries! Thanks for taking the time to report and test :)
