### ISSUE TITLE
Feeds are not updating

### ISSUE THREAD

**Issue by chenerlich** [yeti-platform/yeti#325]
### Description
Feeds are not updating.
Getting this on syslog logs:

> Jan  7 11:17:38 celery[1511]: [2019-01-07 11:17:38,792: ERROR/ForkPoolWorker-6] Task core.feed.update_feed[de978355-cebc-4b1d-a4d3-e965682014fa] raised unexpected: DoesNotExist('ScheduleEntry.Feed matching query does not exist.',)
Jan  7 11:17:38 celery[1511]: Traceback (most recent call last):
Jan  7 11:17:38 celery[1511]:   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
Jan  7 11:17:38 celery[1511]:     R = retval = fun(*args, **kwargs)
Jan  7 11:17:38 celery[1511]:   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
Jan  7 11:17:38 celery[1511]:     return self.run(*args, **kwargs)
Jan  7 11:17:38 celery[1511]:   File "/opt/yeti/core/feed.py", line 35, in update_feed
Jan  7 11:17:38 celery[1511]:     Feed.objects.get(id=feed_id).name))
Jan  7 11:17:38 celery[1511]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 276, in get
Jan  7 11:17:38 celery[1511]:     raise queryset._document.DoesNotExist(msg)
Jan  7 11:17:38 celery[1511]: Exception: ScheduleEntry.Feed matching query does not exist.

What should I do?

Thanks

**Comment by sebdraven** [comment]
Clear the redis. Clear the feed entry in mongo. Start yeti webserver connect to yeti, choose dataflows menu and start celery scheduled tasks

**Comment by chenerlich** [comment]
> Clear the redis. Clear the feed entry in mongo. Start yeti webserver connect to yeti, choose dataflows menu and start celery scheduled tasks

@sebdraven Can you show me the commands?

**Comment by chenerlich** [comment]
@sebdraven Help? It's production...

**Comment by tomchop** [comment]
Hey Chen. You can join our Yeti Slack channel [here](https://join.slack.com/t/yeti-platform/shared_invite/enQtNTIyMDQ2NDIzODQ2LWU0NTRmYmFjY2JhZmFhYzU1NWNjYTA3M2M4ZWEzZTFjODI3YTE5MjFmYzQ0NzViYzUzMjIyMzc4ZjQ5NGEyNGY)

**Comment by soulsf** [comment]
Hey Guys,

have the same problem - who do I clean the feed entry in mongodb ? Already flushed redis...

**Comment by tomchop** [comment]
@soulsf Please try this and see if it helps: https://github.com/yeti-platform/yeti/issues/88#issuecomment-308346437
