### ISSUE TITLE
Erratic behavior for import

### ISSUE THREAD

**Issue by tomchop** [yeti-platform/yeti#326]
When trying to import https://blog.yoroi.company/research/the-enigmatic-roma225-campaign/ in an investigation, an uncaught "invalid ipv6" exception is raised.

![image 1](https://user-images.githubusercontent.com/1257972/50989506-db553d00-150f-11e9-85d9-98f5a4695df2.png)

**Comment by doomedraven** [comment]
it fails on this url `https://minhacasaminhavidacdt.blogspot[.com/`
