### ISSUE TITLE
Web UI no working properly

### ISSUE THREAD

**Issue by motox1** [yeti-platform/yeti#328]
I have any issue getting the JS and CSS to run on the website. I have view the closed issue and it is about YARN being installed correctly. Mine is installed correctly but still not showing correctly. Please help as I need to resolve this ASAP.

![screenshot 2019-01-16 09 02 44](https://user-images.githubusercontent.com/46332330/51266057-0e178f00-196f-11e9-8bc9-bfbc4f5a0560.png)

yarn install v1.12.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.04s.

**Comment by gaelmuller** [comment]
Yarn must be installed on your system.

Then you have to run `yarn install` inside Yeti's directory and clear you browser cache.

**Comment by motox1** [comment]
Tried the

> 
> 
> Yarn must be installed on your system.
> 
> Then you have to run `yarn install` inside Yeti's directory and clear you browser cache.

I tried this but it still does not work...

/home/ubuntu/yeti# yarn install
yarn install v1.12.3
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.15s.

Please let me know what else I can try to get this to load correctly. I tried after clearing the cache also.

**Comment by xmstaring** [comment]
I met this problem too

**Comment by doomedraven** [comment]
Details?
