### ISSUE TITLE
XSS in Entities description field

### ISSUE THREAD

**Issue by fr33tux** [yeti-platform/yeti#329]
Hello;

### Description

The `Entities` description field is subject to XSS.

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | all version impacted.
| OS version       | Ubuntu 18.10, Windows 10
| Browser          | Latest Chrome, latest Firefox.

### Steps to Reproduce
1. Login to Yeti
2. Go to `Entities`, open one entity and edit the Description field.
3. insert `<script>prompt('XSS yeti', document.domain)</script>`, save and observe the prompt.

#### Expected behavior
Description fields should not render anything else than markdown and would leave the XSS unrendered.

#### Actual behavior
The XSS is executed.

Note than I haven't checked [TibetanBrownBear](https://github.com/yeti-platform/TibetanBrownBear) (yet?) to see if it's also valid there.

Thanks!

**Comment by gaelmuller** [comment]
This should now be fixed, thank you for reporting :sweat_smile:
