### ISSUE TITLE
Question:  Submit files via API

### ISSUE THREAD

**Issue by DigiAngel** [yeti-platform/yeti#33]
First, GREAT app...just what I've been looking for.  Second, in reading the API docs, is there a way to submit a file via API?  Thank you.

**Comment by tomchop** [comment]
Thanks! Depends on what you mean by a file. Do you want to submit several observables? Or are you trying to attach a file to an entity?

**Comment by DigiAngel** [comment]
Oh yea....helps if I you know....actually said what I meant 8-|  A file
proper....exe...doc...the whole gamut ☺.  Thank you!

**Comment by tomchop** [comment]
It's not currently possible to upload a full file (i.e. including file contents) via the API but you can achieve similar functionality by tracking the hashes alone. I understand this might be a big shortcoming; I'm opening an issue to track this.

**Comment by DigiAngel** [comment]
Awesome...thanks Thomas!
