### ISSUE TITLE
Add backscatter analytics / feed

### ISSUE THREAD

**Issue by tomchop** [yeti-platform/yeti#336]
IP scanners repo. Could be used as feeds or as analytics.

https://backscatter.io/
https://backscatter.io/developers

**Comment by 9b** [comment]
Happy to provide access here if an account is supplied. Is there anything needed on my side to move this along?

**Comment by tomchop** [comment]
@9b if we could have a test API key to access the platform and data, I'm sure that would be very helpful. Thanks!

**Comment by threathive** [comment]
The service was shutdown so its probably ok to close this issue out.
