### ISSUE TITLE
Import Entities

### ISSUE THREAD

**Issue by AntoninHL** [yeti-platform/yeti#339]
Hey!

I'm looking for a solution to import Entities.

For example, I have, in an other solution, more than 300 full qualified Actors, more than 100 full qualified campaigns, thousands of tools, malwares, signatures, TTPs... etc...

And it will be a coooooool idea if I was able to import them...

Thanks!

**Comment by tomchop** [comment]
You might want to have a look at [TibteanBrownBear](https://github.com/yeti-platform/TibetanBrownBear) which supports ingestion of TAXII feeds.

Otherwise the only way to import them is to create a script that will interact with whatever API your existing solution has and re-map entities to Yeti.

**Comment by Kirtar22** [comment]
@tomchop - I tried to connect to Yeti API ("entity") using "pyeti", but I could not get it working. I added a function/method in the "api.py" which takes the parameters as yeti expecting for "malware" and try to get them added like "observable_add" method but it is not working.  I am getting an API errorr (500). Can you please suggest?

**Comment by Kirtar22** [comment]
@tomchop  - API is working okay for observables (adding and fetching) AND I could fetch the Entity as per the "id"; but when I use the "entity" API for adding entity, it throws an error.

**Comment by sebdraven** [comment]
This pb is solved with pyeti, https://github.com/yeti-platform/pyeti/blob/master/pyeti/api.py#L81
