### ISSUE TITLE
yarn install error

### ISSUE THREAD

**Issue by PersonalizedFinances** [yeti-platform/yeti#346]
### Description
When I execute yarn install command I am getting the error SyntaxError: Unexpected token {

### Environment

| Question         | Answer
|------------------|--------------------
| OS version       | Ubuntu 16.04

### Steps to Reproduce
1. sudo apt-get install build-essential git python-dev mongodb redis-server libxml2-dev libxslt-dev zlib1g-dev python-virtualenv wkhtmltopdf
2. curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
3. echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
4. sudo apt-get update && sudo apt-get install yarn
5.git clone https://github.com/yeti-platform/yeti.git
6. cd yeti
7.pip install -r requirements.txt
8.yarn install
#### Expected behavior
I am expecting that yarn install command be executed without errors.

#### Actual behavior
/usr/share/yarn/lib/cli.js:45726
  let {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/share/yarn/bin/yarn.js:24:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

**Comment by tomchop** [comment]
Looks like there's something wrong with your install of Yarn. I am having no issues on Ubuntu 18.04.

```
tomchop@tomchop-1:/opt/yeti$ yarn install
yarn install v1.13.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.34s.
tomchop@tomchop-1:/opt/yeti$ yarn -v
1.13.0
```

What version of Yarn are you running?

**Comment by tomchop** [comment]
Actually: https://github.com/yarnpkg/yarn/issues/6914

It's an issue with yarn / nodejs dependencies. Please make sure to do an online Google search before opening issues here (especially if the error doesn't seem to be coming from Yeti directly)

Thanks!
