### ISSUE TITLE
24 Hour Feeds don't run

### ISSUE THREAD

**Issue by BitsOfBinary** [yeti-platform/yeti#349]
### Description
Feeds that are scheduled for every 24 hours (e.g. DynamicDomains, IPSpamList, etc.) don't run, even when manually toggled.

### Environment
| Question         | Answer
|------------------|--------------------
| Git commit       | 41a4a33a7006729a40f986768bfa57707ba56842
| OS version       | Ubuntu 16.04
| Browser          | Firefox 60.5.1esr (64-bit)

### Steps to Reproduce
1. Install Yeti
2. Go to Dataflows
3. Manually toggle feeds that run every 24 hours

#### Expected behavior
Feed should run after 24 hours.

#### Actual behavior
Feed is stuck with "Last Run - Never", and does not respond to being toggled.

**Comment by doomedraven** [comment]
i had similar issue, can you check /var/log/syslog for erros? in my case for some reason redis wasn't started

or just `systemctl status redis-server`, if there is `Loaded` means it not started

**Comment by BitsOfBinary** [comment]
Thank you for the suggestion. I just checked and redis is running as it is supposed to, looks like there are no errors.

Strangely enough, one of the 24 hour feeds has actually run now... The DynamicDomains one to be specific. I played around with its config and dropped it down to 23 hours and rebooted Yeti, so that perhaps helped somehow? The other 24 hour feeds aren't running though.

Also to be clear, all other feeds and running as scheduled.

**Comment by doomedraven** [comment]
what about `python testfeeds.py DynamicDomains`?

in my case im getting
```
DEBUG:root:Scheduler started
Running DynamicDomains...
DEBUG:root:Feed DynamicDomains is already running...`
```

but there no data from it

**Comment by BitsOfBinary** [comment]
I got these results for `DynamicDomains`
```
DEBUG:root:Scheduler started
Running DynamicDomains...
DEBUG:root:Running DynamicDomains (ID: 5c86b35915953803ca45795e)
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): mirror1.malwaredomains.com:80
DEBUG:urllib3.connectionpool:http://mirror1.malwaredomains.com:80 "GET /files/dynamic_dns.txt HTTP/1.1" 200 None
```

I tested `IPSpamList` and it successfully ran. But it doesn't look it it is running in the web interface... I also don't have any observables from the `IPSpamList` feed.

**Comment by BitsOfBinary** [comment]
Now everything appears to be running as it should, including the 24 hour feeds. Wish I could give more detail into why it's now working!

**Comment by tomchop** [comment]
Happy to know that everything is working. Thanks for helping out @doomedraven! Maybe the beats scheduler wasn't running correctly? Please do reopen this issue if you run into it again.

**Comment by doomedraven** [comment]
that is one of the thing to mention in quick intro, how to check them all :)

**Comment by BitsOfBinary** [comment]
Thanks all, will update if I figure out what was causing the problem!
