### ISSUE TITLE
Export not working as Export format dropdown is empty

### ISSUE THREAD

**Issue by mahesh557** [yeti-platform/yeti#35]
I am unable to do export as export format drop down box is empty and hence unable to save the export.

OS: Ubuntu 16.04
Browser: firefox, chrome

**Comment by gaelmuller** [comment]
You need to create at least a template first. Did you ?

You can see how in the documentation: http://yeti-platform.readthedocs.io/en/latest/getting-started.html#creating-a-blocklist

**Comment by mahesh557** [comment]
just found out. Thanks
