### ISSUE TITLE
open wiki to allow collaboration

### ISSUE THREAD

**Issue by doomedraven** [yeti-platform/yeti#350]
Hello guys, thanks for nice project, isn't issue itself, can you just open wiki so the community can help to elaborate the documentation to start with YETI?

for example i have done some quick notes for me so im pretty sure that will save time to newcomers

##### Plugins to work on data(observables)
* Plugins should be placed in: `plugins/analytics/(public|private)`
* The observable types can be found in `core/observables`
    - Example:  MacAddress, Hash, Url, Ip, Hash, Hostname, Email, Bitcoint, ...
    - `from core.observables import Hash, Url, Hostname, Ip, MacAddress, Email`

* How to extract iocs/observables from text:
    - from core.observables import Observable
    - observables = Observable.from_string(text)

* How to check observable type, for example Ip:
    - if isinstance(observable, Ip):

* To access config data:
    - `from core.config.config import yeti_config`
    - example: `yeti_config.redis.host`

### Extend web api
* Place your .py, use use `redis_api.py` as example in:
    * `core/web/api/redis_api.py`

* Add import and register to: `core/web/api/api.py`:
    * from core.web.api.redis_api import ManageRedisData
    * ManageRedisData.register(api)
        * you can use render to render html or render_json, for raw responses

**Comment by doomedraven** [comment]
or would it make sense to put it in docs/quick-intro.rst ? or something like that?

**Comment by tomchop** [comment]
Hey! That's definitely a great idea. And yeah, as you said, we don't use GitHub wikis because last time I checked it was hard for people to contribute. All the documentation should be in the `docs` folder, so a `docs/quick-intro.rst` makes perfect sense!

**Comment by doomedraven** [comment]
ok will move that, and we can make some quick tips/usage cases, to help newcomers :) will PR it

**Comment by tomchop** [comment]
Excellent! Thanks so much :) LMK if you want an invite to the Slack channel as well

**Comment by doomedraven** [comment]
would be great :) drop me invite to doommedraven[at]gmail[dot]com
thank you
