### ISSUE TITLE
duplicated related observables

### ISSUE THREAD

**Issue by doomedraven** [yeti-platform/yeti#355]
### Description
Duplicated observables in related, the same happens to the feed name, not sure if that is expected

<img width="860" alt="Captura de pantalla 2019-03-15 a las 15 40 09" src="https://user-images.githubusercontent.com/1856495/54439208-a5fbe400-4738-11e9-9c90-3855e0301de1.png">

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 41a4a33a7006729a40f986768bfa57707ba56842
| OS version       | Ubuntu 18.04

### Steps to Reproduce
Not sure why it duplicated, get_or_create should do the trick, the observable has the same id, maybe an set 

#### Expected behavior
[How are you expecting the application to behave?]

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]

**Comment by tomchop** [comment]
Hmm that's strange. I know @sebdraven was working on similar problems. We had this with URLs but never with hashes. Can you show us a sample of the line the hash was imported from?

**Comment by doomedraven** [comment]
the data is loaded from here
`https://sslbl.abuse.ch/blacklist/ja3_fingerprints.csv`

```
ja3_md5, First_Seen, lastseen, Family = line

        context = {}
        context['date_added'] = First_Seen
        context['source'] = self.name

        tags = []
        tags.append(Family.lower())

        hash_data = False
        try:
            if  ja3_md5:
                hash_data = Hash.get_or_create(value=ja3_md5)
                hash_data.add_context(context)
                hash_data.add_source("feed")
                hash_data.tag(tags)
        except ObservableValidationError as e:
            logging.error(e)
```

**Comment by sebdraven** [comment]
It's normal if you have the same context. You have to check if the hash_data.new is true or false If you don't want to have the same context many times.

**Comment by doomedraven** [comment]
ah ok, didn't know that, thanks a lot

**Comment by sebdraven** [comment]
But it could be interested to know if you have different sources on the same observable.

**Comment by doomedraven** [comment]
i think the best for this would be instead of source "feed" set the feed name, and then just check if name from which it executed is the same as source of ioc, so we could ignore it

**Comment by sebdraven** [comment]
yep :+1:
