### ISSUE TITLE
Feature Request: Virustotal API support

### ISSUE THREAD

**Issue by securitykitten** [yeti-platform/yeti#36]
### Description
Support the Virustotal public and private API, similar to the enrichment from PassiveTotal.

Public API documentation can be found here:
https://www.virustotal.com/en/documentation/public-api/

Private API documentation can be found here:
https://www.virustotal.com/en/documentation/private-api/

**Comment by k0rrupt** [comment]
Hi, just wondering if there's any news on when this might be implemented?

**Comment by tomchop** [comment]
We're having some trouble backlogging through the issues. Can you please explain how you'd want to use this? Would you want to leverage passive DNS exclusively? Or would you want to leverage samples, etc. as well?

**Comment by tomchop** [comment]
@securitykitten @k0rrupt We're having some trouble backlogging through the issues. Can you please explain how you'd want to use this? Would you want to leverage passive DNS exclusively? Or would you want to leverage samples, etc. as well?

**Comment by tomchop** [comment]
Good news! The contribution in #151 implements part of the API. Feel free to build on this if you want to add features (or let us know in another issue and we'll try to add them ourselves).
