### ISSUE TITLE
Can't logout

### ISSUE THREAD

**Issue by FafnerKeyZee** [yeti-platform/yeti#37]
Hello,

After adding some users on the system, it is not possible to logout of yeti account. So it is not possible to disable it from the panel.

Best regards,

**Comment by tomchop** [comment]
Thanks for the heads-up. Will fix that today.

**Comment by FafnerKeyZee** [comment]
Temporary fix (Thx @tomchop):
Run a mongo shell
`$ mongo`
Then update the base to disable the account :
```
use yeti 
db.user.update({username: "yeti"}, {$set: {enabled: false}})
```

It does the job until you fix it .]
