### ISSUE TITLE
Feodo Tracker Feed Issue

### ISSUE THREAD

**Issue by vitalisec** [yeti-platform/yeti#371]
ERROR updating feed: Space required after the Public Identifier, line 1, column 50 (line 1)

**Comment by threathive** [comment]
The script uses the feed url https://feodotracker.abuse.ch/feodotracker.rss is a 404 now. They replaced it with a new set of urls as you can see at https://feodotracker.abuse.ch/blocklist/ . So the feed import script probably will need a bit of a rewrite.

**Comment by threathive** [comment]
I made a pull request to replace this feed with two others. 
https://github.com/yeti-platform/yeti/pull/374
https://github.com/yeti-platform/yeti/pull/373
https://github.com/yeti-platform/yeti/pull/372

**Comment by tomchop** [comment]
PRs have been merged. Thanks for tackling this!
