### ISSUE TITLE
Unlock scheduled entries when worker starts Doesn't work

### ISSUE THREAD

**Issue by javimb02** [yeti-platform/yeti#382]
Hi,
Unlock scheduled entries when worker starts feature (https://github.com/yeti-platform/yeti/pull/137#issue-140170118) is not working, at least on my environment. After some testing I found out that this line in the unlock_scheduled_entries func is never updating anything:

`locked_entries[queue].objects(lock=True).update(lock=False, status='Unlocked')`

despite locked entries exist in db. This seems to be because Feed.objects() is not returning anything at this point, I sorted it out by invoking the Scheduler() or just the get_plugins() func before querying, by adding:

```
     from core.yeti_plugins import get_plugins
     get_plugins()

     for queue in queues:
        if queue in locked_entries:
            locked_entries[queue].objects(lock=True).update(lock=False, status='Unlocked')
```

but I'm not really sure if this is the right way to go, can you please confirm?

thanks

_Originally posted by @javimb02 in https://github.com/yeti-platform/yeti/pull/137#issuecomment-481257859_

**Comment by gaelmuller** [comment]
Thank you for investigating this issue. There is now a PR to fix this.
