### ISSUE TITLE
mongodb performance issues due to link queries not using the right index

### ISSUE THREAD

**Issue by javimb02** [yeti-platform/yeti#383]
Hi,
after experiencing some performance issues on mongodb, I found out that those are due to some link query doing a collscan and not using the right index:

> command yeti.link command: find { find: "link", filter: { src.$id: ObjectId('5caf020d563a6a99431ff371') } } planSummary: COLLSCAN keysExamined:0 docsExamined:686609 cursorExhausted:1 numYields:5364 nreturned:1 reslen:396 locks:{ Global: { acquireCount: { r: 10730 } }, Database: { acquireCount: { r: 5365 } }, Collection: { acquireCount: { r: 5365 } } } protocol:op_query 246ms

The problem seems to be that the "src" field in the link document is a DBRef to and observable doc, and the src.$id filter in the query doesn't use the existing index on "src" field. My solution is to create an index on "src.$id" this way: 

`> db.link.createIndex({"src.$id": 1})`

and now the query uses this index and problem disappears, but I'm not sure if this is the best way to go, and how this can be achieved in source code. In database.py we have this:

`meta = {"indexes": ["src", "dst"]}`

but this is creating the indexes just on "src" and "dst", not "src.$id" which is needed for the link query 

Thanks

**Comment by doomedraven** [comment]
@tomchop  wasn't it be just "src.id"? https://www.tutorialspoint.com/mongodb/mongodb_advanced_indexing.htm

**Comment by ftanida** [comment]
@tomchop 
link.src is reference to database (DBRefs) and document said src.$id can be also used.
https://docs.mongodb.com/manual/reference/database-references/#dbrefs

> $id
> The $id field contains the value of the _id field in the referenced document.

**Comment by doomedraven** [comment]
i just had the same problem on dst.$id, adding it to indexes solved performace issue

**Comment by clp-trap** [comment]
@doomedraven got same here with dst.$id, could you please tell how did you exactly add it to indexes? Like that?
db.link.createIndex({"dst.$id": 1})

**Comment by doomedraven** [comment]
@clp-trap  yes
