### ISSUE TITLE
yeti fails to start after upgrade

### ISSUE THREAD

**Issue by villain** [yeti-platform/yeti#385]
after doing a git pull, yeti syncdb etc, when I visit the yeti web page and see 'Internal Server Error'

looking at journal -xe i see 'no python application found'

Apr 15 08:34:44 host uwsgi[3697]: --- no python application found, check your startup logs for errors ---

**Comment by villain** [comment]
for future reference, there was a file in /var/log/yeti which the wrong permissions. removing that fixed the problem

**Comment by phutch11** [comment]
I am getting this exact problem after upgrading to v1.5 with the `no python application...` in log  and `Internal Server Error` on page load up.

Could you please elaborate on the permissions for the activity file required in the /var/log/yeti location? Nothing I try seems to resolve it.
