### ISSUE TITLE
CybercrimeAtmTracker feed is always returning an ERROR

### ISSUE THREAD

**Issue by joanrodriguezr** [yeti-platform/yeti#388]
### Description
CybercrimeAtmTracker is not running

### Environment

Master branch up to commit 3e85d9597799e49d6336ba88ac070d4ba05a33ec

### Steps to Reproduce

{my_yetu_url}/dataflows > Update feed CybercrimeAtmTracker or open http://atm.cybercrime-tracker.net/rss.php

#### Expected behavior
Status OK

#### Actual behavior
Status ERROR updating feed: Opening and ending tag mismatch: BR line 6 and FONT, line 7, column 8 (line 7)

#### Possible solution
I guess if the  server which contains http://atm.cybercrime-tracker.net/rss.php needs to be restarted or the feed needs to be republished or something similar.

Thanks in advance!

**Comment by doomedraven** [comment]
forwarded msg to server admin, that is source problem not yeti

**Comment by tomchop** [comment]
Fixed
