### ISSUE TITLE
Observable Charts/Graphs/Dashboard

### ISSUE THREAD

**Issue by kx499-zz** [yeti-platform/yeti#40]
It would be helpful to have some graphs representing metrics on the Observable/tags to give you an over of the data set over the last 7/30 days, I was thinking about the following:
1) Stacked bargraph showing observable counts by sources over time
2) Piechart showing data type distribution
3) Piechart showing tag distribution
4) Piechart showing feed source distribution
5) table with sparklines showing feed activity by feed name over time (quick way to eyeball failures or defunct feeds)

I would assume it would entail some aggregations of mongo data and maybe something like pygal. Don't mind taking a crack at it if it seems like a good idea, but looking for some suggestions on what to do the charts in, 

Another option would be to put together a Splunk app, but that would limit it to folks who had access to Splunk. I do, but not everyone does,

**Comment by tomchop** [comment]
I also got this request from other people. To be honest, I don't really grasp what use can come from knowing that there are N% domain names vs. n% URLs in the database, but needs can differ from org to org. ¯\_(ツ)_/¯ That being said, having the same stats over time (eg. we see an increase in things tagged "ransomware") would be more actionable metrics and I think it would be pretty awesome.

I was going to say that implementing this would be fairly straightforward even with basic mongoengine queries and some library like vis.js but it seems pygal has already got functions for exporting data to graphs. If you can submit a PR with that, that would be great.

A splunk app would also be a good idea. I have no idea how to write one, and maybe we need to get more people around the table to discuss what the would like to get out of it, but it definitely sounds like something people could really use. 

Thanks for the input!
