### ISSUE TITLE
mongoengine: remove references to deleted nodes

### ISSUE THREAD

**Issue by DigiAngel** [yeti-platform/yeti#41]
### Description
Just need to delete a saved investigation as I was just testing.

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 27ae09f83b0165c36c78297708b4a2e75c9a2dad
| OS version       | Debian stretch
| Browser          | Chrome 57.0.2987.133 (64-bit)

### Steps to Reproduce
1. Add new investigation via new malware
2. Attempt to delete the test investigation

#### Expected behavior
To be able to remove the investication

#### Actual behavior
There's no button or link or anything that allows removing an investigation.

**Comment by gaelmuller** [comment]
This should already be possible. When you go to the investigation page (not the graph - by clicking on the name of the investigation), you should have a red button "Delete":

![image](https://cloud.githubusercontent.com/assets/35897/24703127/2dce531a-1a02-11e7-9f87-3a6ad08636c9.png)

Could you confirm this is the case ?

**Comment by DigiAngel** [comment]
It is not...I do not have a delete button.  After deleting the Malware,
now I get an error:

**Comment by DigiAngel** [comment]
More information.  Is there a way I can just start over and delete everything?
![peek 2017-04-20 06-45](https://cloud.githubusercontent.com/assets/947191/25231437/18f256aa-2595-11e7-9b73-badcdeb62eb6.gif)

**Comment by gaelmuller** [comment]
We need to fix the fact that deleting a node breaks the investigation.

Since you cannot access the delete button, you can use the API to delete the investigation:

```
http -j DELETE http://YETI_URL/api/investigation/INVESTIGATION_ID
``` 

Or, directly in the mongo shell:

```
mongo
> use yeti
> db.investigation.remove({'_id': ObjectId('INVESTIGATION_ID')})
WriteResult({ "nRemoved" : 1 })
```

**Comment by DigiAngel** [comment]
Thanks..I ended up just dropping the entire investigation table and
readding it.

**Comment by doomedraven** [comment]
this can be closed i think, this is solved now
