### ISSUE TITLE
Unable to Start Yeti

### ISSUE THREAD

**Issue by KingKong189** [yeti-platform/yeti#44]
### Description
I run the quick install for Yeti and after all is back to command prompt, I then try to move to the next step.  
I have tried the pip install -r requirements.txt (no such file or directory)

Also, I cannot find yeti.py anywhere on my system.  I have done the grep and looked in every file and folder i can find.  I rebuilt my Ubuntu using 16.04 LTS in a virtual environment.

I ran the command
"sudo apt-get install build-essential git python-dev mongodb redis-server libxml2-dev libxslt-dev zlib1g-dev python-virtualenv"

Then "sudo pip install -r requirements.txt" it tells me no such file or directory

I skip that and try to run the "./yeti.py"  doesn't find anything.  I need some help.

Want to get this up and going, however, doesn't seem as easy as I was hoping.  
I'm a Linux novice, but though that the instructions were fairly simple.  
I suppose they are when they work.

**Comment by tomchop** [comment]
This is not explicitly mentioned in the documentation but you need to download Yeti separately. 
This should do the trick:

```
$ cd ~
$ git pull https://github.com/yeti-platform/yeti/
```

I'll add that step in the documentation.
