### ISSUE TITLE
How you expect to handle invalid certs?

### ISSUE THREAD

**Issue by doomedraven** [yeti-platform/yeti#444]
Hey as you don't like `verify=False`

just saw 
```
ERROR updating feed: HTTPSConnectionPool(host='malwareconfig.com', port=443): Max retries exceeded with url: /static/C2_24.csv (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
```

i would add false to be able to keep feeding user systems, but waiting for your response

**Comment by tomchop** [comment]
Probably really bad practice to set `verify=False` by default. Maybe we can add an option in the settings if users really want this behavior for feeds?

**Comment by doomedraven** [comment]
yes i know that is bad, but if no we can't grab iocs, which is worst, would be neat to have feed settings so far

**Comment by doomedraven** [comment]
as we have per feed verify we can fix it easilly :)
