### ISSUE TITLE
Time frequency of feeds/analytics not reflected properly in the UI

### ISSUE THREAD

**Issue by clp-trap** [yeti-platform/yeti#451]
### Description
Time frequency of feeds/analytics not reflected properly in the UI under "Runs every" column

### Steps to Reproduce
1. Change the frequency to your choice in any of the python feed files
2. Go to UI, the value in  "Runs every" column remains the same as yeti's default installation value

#### Expected behavior
"Runs every" to be updated with the actual updated value from the python files

#### Actual behavior
The value in  "Runs every" column remains the same as yeti's default installation value, even though has been changed in the python file.

**Comment by doomedraven** [comment]
did you restart systemd yeti_feeds? after change py code?

**Comment by doomedraven** [comment]
anyway i would suggest you to check out 

https://github.com/yeti-platform/yeti/pull/447
https://github.com/yeti-platform/yeti/pull/450

that will drastically decrease system loads, and improve performance

**Comment by clp-trap** [comment]
@doomedraven thanks, i did restart the service

**Comment by doomedraven** [comment]
maybe you need to update also uwsgi, try that with `python yeti.py webserver --debug` to see if that is propagated

**Comment by clp-trap** [comment]
Will do! Thanks for the suggestion

**Comment by doomedraven** [comment]
let us know if that works, i would try by myself but im adding new feeds :P

**Comment by clp-trap** [comment]
^That got to be more important:)

**Comment by doomedraven** [comment]
ok just checked that doesn't update

**Comment by doomedraven** [comment]
to change that you need to change that in mongo

```
use yeti
db.schedule_entry.find()
there you have all frequencies
```

**Comment by clp-trap** [comment]
Got it, so adjusting frequency in the feed’s python file didn’t really update it?

**Comment by doomedraven** [comment]
didn't, but should, somewhere it just doesn't reload data

**Comment by clp-trap** [comment]
@doomedraven btw, by running db.schedule_entry.find() i get a list among which are feeds that are not even turned on in the UI and on the other hand, some of the feeds that are turned on - don't appear in this list as well...is that a whole other issue or expected behavior? Shouldn't the output of the aforementioned command include all the "ui turned on" feeds?

**Comment by doomedraven** [comment]
well you got all bcz you don't pass any filter to it, you need check there other table with stuff so you need to search waht you exactly need

```
use yeti
show collections
```

```
analytics_results
entity
import_results
indicator
inline_analytics
internals
investigation
link
observable
one_shot_entry
schedule_entry
tag
user
```

**Comment by gaelmuller** [comment]
This is working as intended.

The frequency in the code will only be used as a default value when the feed is first imported. After that, the frequency can only be changed in the database. We are missing a view that would allow users to change that configuration from the Dataflows page.
