### ISSUE TITLE
yeti/docker x509 certification issues

### ISSUE THREAD

**Issue by vitoj23** [yeti-platform/yeti#459]
Hello,
I am attempting to install yeti via docker and am faced with this error message on step 10/15: 
I have been unsuccessful at fixing this issue. If anyone can provide some insight or possible remediation steps I would be very thankful. 
All the best.
![image](https://user-images.githubusercontent.com/51460062/59060804-8a9c0300-8867-11e9-8cd8-b2e48fbc6186.png)

**Comment by doomedraven** [comment]
could you please c&p that  githubusercontent link?

**Comment by vitoj23** [comment]
https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh

thanks

**Comment by doomedraven** [comment]
em there is no cert at all, could you give more details about this issues and how it happens to reproduce?

**Comment by vitoj23** [comment]
$ git clone https://github.com/yeti-platform/yeti
$ cd yeti/extras/docker
$ docker-compose up

Upon running the third command in the installation...everything begins to install fine until script in step 10 is called and a certification check is done on it. I honestly don't understanding why because
I am attempting to install yeti on an Ubuntu v18.04.2. VM (host computer Windows) and my friend followed the same steps on his Mac and everything worked fine.

**Comment by doomedraven** [comment]
no idea, i have installed everything on linux without docker

**Comment by vitoj23** [comment]
1. Thanks for trying to help.
2. Did you follow the steps exactly as they appear in the documentation? I run into various errors when attempting that. :/ It's actually why I went to docker.

**Comment by doomedraven** [comment]
i have used oneline installer 

```
curl https://raw.githubusercontent.com/yeti-platform/yeti/master/extras/ubuntu_bootstrap.sh | sudo /bin/bash

```

**Comment by vitoj23** [comment]
grrr, again faced with secure connection errors.
![image](https://user-images.githubusercontent.com/51460062/59061981-583fd500-886a-11e9-8bee-93ee3b8ff8ee.png)

**Comment by doomedraven** [comment]
chech your date and if no you can add -k option for insecure connection to ignore that

**Comment by vitoj23** [comment]
after adding -k option to bypass security check
![image](https://user-images.githubusercontent.com/51460062/59062339-34c95a00-886b-11e9-8993-7ef546aa296b.png)

**Comment by doomedraven** [comment]
ah it not downloaded it for you as you can see it forwarded you and you got only html not real code

**Comment by doomedraven** [comment]
```
# Install dependencies
export LC_ALL="en_US.UTF-8"

if [ -f "/usr/bin/apt" ]; then
   APT="/usr/bin/apt"
else
   APT="/usr/bin/apt-get"
fi

$APT update -y
$APT install dirmngr

curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

# https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4

# https://wiki.ubuntu.com/Releases
OS_CODENAME=`lsb_release -c --short`

if [ $OS_CODENAME == "bionic" ] || [ $OS_CODENAME == "artful" ] || [ $OS_CODENAME == "zesty" ] || [ $OS_CODENAME == "yakkety" ] || [ $OS_CODENAME == "xenial" ]; then
  echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.0.list
elif [ $OS_CODENAME == "wily" ] || [ $OS_CODENAME == "vivid" ] || [ $OS_CODENAME == "utopic" ] || [ $OS_CODENAME == "trusty" ]; then
  echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
else
  echo "[!] Installing on an unsupported or outdated version of Ubuntu, trying Trusty package for Mongo"
  echo "deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
fi

$APT update -y
$APT install build-essential git python-dev mongodb-org redis-server libcurl3 libxml2-dev libxslt-dev zlib1g-dev python-virtualenv python-pip nginx yarn -y

# Clone project
cd /opt
git clone https://github.com/yeti-platform/yeti.git

# Install requirements
cd /opt/yeti
pip install -r requirements.txt
pip install uwsgi
yarn install

# Configure services
useradd yeti
sudo mkdir /var/log/yeti
sudo chown yeti /var/log/yeti
cp extras/systemd/*.service /etc/systemd/system/
systemctl enable mongod.service
systemctl enable yeti_uwsgi.service
systemctl enable yeti_oneshot.service
systemctl enable yeti_feeds.service
systemctl enable yeti_exports.service
systemctl enable yeti_analytics.service
systemctl enable yeti_beat.service
systemctl daemon-reload
chown -R yeti:yeti /opt/yeti
chmod +x /opt/yeti/yeti.py

# Configure nginx
rm /etc/nginx/sites-enabled/default
cp extras/nginx/yeti /etc/nginx/sites-available/
ln -s /etc/nginx/sites-available/yeti /etc/nginx/sites-enabled/yeti
service nginx restart

# Start services
echo "[+] Starting services..."
systemctl start mongod.service
systemctl start yeti_oneshot.service
sleep 5
systemctl start yeti_feeds.service
systemctl start yeti_exports.service
systemctl start yeti_analytics.service
systemctl start yeti_beat.service
systemctl start yeti_uwsgi.service

echo "[+] Yeti succesfully installed. Webserver listening on tcp/80"
```


save it as file and execute

**Comment by vitoj23** [comment]
Thank you so much. I got it running. You were right :)

**Comment by doomedraven** [comment]
glad it worked, check PRs for feed improvements, that will improve performance, and check issue about mongo links, that isn't merged/fixed yet, but apart of that it works just fine :)
