### ISSUE TITLE
issue hybdrid analysis

### ISSUE THREAD

**Issue by sebdraven** [yeti-platform/yeti#467]
it's seem an logical error here and in my instance the feed of hybrid analysis is locked
```

 first_seen = parser.parse(item['analysis_start_time'])
            if self.last_run is not None:
                since_last_run = datetime.now() - self.frequency
            
           if since_last_run > first_seen:
                    return
```

it's more logical work en timedelta
```
         since_last_run= datetime.now() - self.first_seen
         if since_last_run <= self.frenquency:
             return
```

**Comment by sebdraven** [comment]
[2019-06-24 09:38:59,974: ERROR/ForkPoolWorker-4] Traceback (most recent call last):
  File "/home/sebdraven/sources/yeti/core/feed.py", line 49, in update_feed
    f.update()
  File "/home/sebdraven/sources/yeti/plugins/feeds/public/hybrid_analysis.py", line 32, in update
    self.analyze(item, first_seen)
NameError: global name 'first_seen' is not defined

[2019-06-24 09:38:59,974: ERROR/ForkPoolWorker-4] ERROR updating feed: global name 'first_seen' is not defined

**Comment by doomedraven** [comment]
feel free to PR it :)

**Comment by doomedraven** [comment]
ok now i was able to check this from pc, no there is no logical bug, the problem if you just care to not grab all old data, so by parts

1. `self.last_run` is used to grab all data on first run
2. the rest of logic checks to not grab old analysis `if last_run is not None`

**Comment by sebdraven** [comment]
The problem was fixed ;)
