### ISSUE TITLE
Docker errors in scheduler

### ISSUE THREAD

**Issue by jekil** [yeti-platform/yeti#472]
Scheduler and workers are not working in docker, due to a issue in systemd.
Actually this is prevented by how process are spawned in docker.

**Comment by tomchop** [comment]
Interesting. Maybe we should decouple the "installation" steps from Docker then and just have a special docker container for workers and scheduler. WDYT?

**Comment by naxonez** [comment]
Same problem here. There's some workarround?

**Comment by jekil** [comment]
There is no workaround, the architecture of how the initial process is spawned must be changed to allow systemctl to work (now it is spawned as first process and it is now allowed by systemctl)

**Comment by tomchop** [comment]
I think it's worth spending some time to create another docker image where only the workers are started. It doesn't make sense to use startup daemons in docker images (my mistake) :D

**Comment by tomchop** [comment]
@jekil Can you tell me which image you're using to run Yeti in docker? We don't seem to reference systemd in them.
