### ISSUE TITLE
Feed Update Errors: UTF-8 + Other

### ISSUE THREAD

**Issue by niallnsec** [yeti-platform/yeti#474]
### Description
I am having issues with a number of the feeds. A couple of them seem to be impacted by a similar issue, which appears to be around encoding UTF-8 text.

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 02bf6cd627b5b31e9e282a40785161e21a80d12c
| OS version       | Ubuntu 18.04
| Browser          | Chrome 75.0.3770.100 x64

### Steps to Reproduce
1. Setup yeti as documented for Ubuntu (with the systemd config)
2. Attempt to update feeds

#### Expected behavior
All the feeds to update successfully

#### Actual behavior
A number of feeds fail to update:
1. TorExitNodes:
```
Jul 17 17:57:04 scratch celery[11358]: [2019-07-17 17:57:04,444: ERROR/ForkPoolWorker-2] Traceback (most recent call last):
Jul 17 17:57:04 scratch celery[11358]:   File "/opt/yeti/core/feed.py", line 49, in update_feed
Jul 17 17:57:04 scratch celery[11358]:     f.update()
Jul 17 17:57:04 scratch celery[11358]:   File "/opt/yeti/plugins/feeds/public/tor_exit_nodes.py", line 33, in update
Jul 17 17:57:04 scratch celery[11358]:     feed = self._temp_feed_data_compare(feed_raw)
Jul 17 17:57:04 scratch celery[11358]:   File "/opt/yeti/core/feed.py", line 133, in _temp_feed_data_compare
Jul 17 17:57:04 scratch celery[11358]:     self._temp_save_feed_data(content)
Jul 17 17:57:04 scratch celery[11358]:   File "/opt/yeti/core/feed.py", line 102, in _temp_save_feed_data
Jul 17 17:57:04 scratch celery[11358]:     f.write(content)
Jul 17 17:57:04 scratch celery[11358]: UnicodeEncodeError: 'ascii' codec can't encode character u'\u0142' in position 318296: ordinal not in range(128)
Jul 17 17:57:04 scratch celery[11358]: [2019-07-17 17:57:04,444: ERROR/ForkPoolWorker-2] ERROR updating feed: 'ascii' codec can't encode character u'\u0142' in position 318296: ordinal not in range(128)
```
2. RansomwareTracker:
```
Jul 17 17:58:11 scratch celery[11358]: [2019-07-17 17:58:11,589: ERROR/ForkPoolWorker-4] Traceback (most recent call last):
Jul 17 17:58:11 scratch celery[11358]:   File "/opt/yeti/core/feed.py", line 49, in update_feed
Jul 17 17:58:11 scratch celery[11358]:     f.update()
Jul 17 17:58:11 scratch celery[11358]:   File "/opt/yeti/plugins/feeds/public/ransomware_tracker_blocklist.py", line 31, in update
Jul 17 17:58:11 scratch celery[11358]:     for line in self.update_csv(delimiter=',', quotechar='"'):
Jul 17 17:58:11 scratch celery[11358]:   File "/opt/yeti/core/feed.py", line 294, in update_csv
Jul 17 17:58:11 scratch celery[11358]:     for line in reader:
Jul 17 17:58:11 scratch celery[11358]:   File "/opt/yeti/core/feed.py", line 271, in utf_8_encoder
Jul 17 17:58:11 scratch celery[11358]:     yield line.encode('utf-8')
Jul 17 17:58:11 scratch celery[11358]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 106: ordinal not in range(128)
Jul 17 17:58:11 scratch celery[11358]: [2019-07-17 17:58:11,589: ERROR/ForkPoolWorker-4] ERROR updating feed: 'ascii' codec can't decode byte 0xc3 in position 106: ordinal not in range(128)
```
3. DynamicDomain (this one appears to be a different issue, wasn't sure if I should open a separate issue for it?)
```
Jul 17 18:26:31 scratch celery[11358]: [2019-07-17 18:26:31,200: ERROR/ForkPoolWorker-2] 'http://ponycc.home.local/gate.php' is not a valid 'Url'
Jul 17 18:26:32 scratch uwsgi[11587]: INFO:user_management:Default user logged in : yeti
Jul 17 18:26:32 scratch uwsgi[11587]: [pid: 11618|app: 0|req: 170/346] 217.44.28.240 () {44 vars in 719 bytes} [Wed Jul 17 18:26:32 2019] POST /api/feed/5d2f43749352ef126f12abbc/refresh => generated 34 bytes in 5 msecs (HTTP/1.1 200) 2 headers in 71 bytes (1 s
Jul 17 18:26:33 scratch celery[11358]: [2019-07-17 18:26:33,446: ERROR/ForkPoolWorker-5] Traceback (most recent call last):
Jul 17 18:26:33 scratch celery[11358]:   File "/opt/yeti/core/feed.py", line 49, in update_feed
Jul 17 18:26:33 scratch celery[11358]:     f.update()
Jul 17 18:26:33 scratch celery[11358]:   File "/opt/yeti/plugins/feeds/public/dynamic_dns.py", line 18, in update
Jul 17 18:26:33 scratch celery[11358]:     if line[0].startswith('#'):
Jul 17 18:26:33 scratch celery[11358]: IndexError: string index out of range
Jul 17 18:26:33 scratch celery[11358]: [2019-07-17 18:26:33,446: ERROR/ForkPoolWorker-5] ERROR updating feed: string index out of range
```

While scrolling through, I also noticed there are a lot of error messages such as:
```
Jul 17 18:26:14 scratch celery[11358]: [2019-07-17 18:26:14,417: ERROR/ForkPoolWorker-3] 'http://downloads44you.shop/mindll.exe' is not a valid 'Url'
```
which seem a bit odd as they are all for valid URLs.

**Comment by niallnsec** [comment]
It also seems that once an error has occured, I can not trigger a feed update again. If I try, the following error is generated:
```
Jul 17 18:50:38 scratch celery[13848]: [2019-07-17 18:50:38,510: ERROR/ForkPoolWorker-2] Task core.feed.update_feed[c2de2d3b-e346-46a4-a3ec-4424b42a3e91] raised unexpected: DoesNotExist('ScheduleEntry.Feed matching query does not exist.',)
Jul 17 18:50:38 scratch celery[13848]: Traceback (most recent call last):
Jul 17 18:50:38 scratch celery[13848]:   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
Jul 17 18:50:38 scratch celery[13848]:     R = retval = fun(*args, **kwargs)
Jul 17 18:50:38 scratch celery[13848]:   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
Jul 17 18:50:38 scratch celery[13848]:     return self.run(*args, **kwargs)
Jul 17 18:50:38 scratch celery[13848]:   File "/opt/yeti/core/feed.py", line 42, in update_feed
Jul 17 18:50:38 scratch celery[13848]:     Feed.objects.get(id=feed_id).name))
Jul 17 18:50:38 scratch celery[13848]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 276, in get
Jul 17 18:50:38 scratch celery[13848]:     raise queryset._document.DoesNotExist(msg)
Jul 17 18:50:38 scratch celery[13848]: Exception: ScheduleEntry.Feed matching query does not exist.
```

**Comment by sebdraven** [comment]
> It also seems that once an error has occured, I can not trigger a feed update again. If I try, the following error is generated:
> 
> ```
> Jul 17 18:50:38 scratch celery[13848]: [2019-07-17 18:50:38,510: ERROR/ForkPoolWorker-2] Task core.feed.update_feed[c2de2d3b-e346-46a4-a3ec-4424b42a3e91] raised unexpected: DoesNotExist('ScheduleEntry.Feed matching query does not exist.',)
> Jul 17 18:50:38 scratch celery[13848]: Traceback (most recent call last):
> Jul 17 18:50:38 scratch celery[13848]:   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
> Jul 17 18:50:38 scratch celery[13848]:     R = retval = fun(*args, **kwargs)
> Jul 17 18:50:38 scratch celery[13848]:   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 641, in __protected_call__
> Jul 17 18:50:38 scratch celery[13848]:     return self.run(*args, **kwargs)
> Jul 17 18:50:38 scratch celery[13848]:   File "/opt/yeti/core/feed.py", line 42, in update_feed
> Jul 17 18:50:38 scratch celery[13848]:     Feed.objects.get(id=feed_id).name))
> Jul 17 18:50:38 scratch celery[13848]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 276, in get
> Jul 17 18:50:38 scratch celery[13848]:     raise queryset._document.DoesNotExist(msg)
> Jul 17 18:50:38 scratch celery[13848]: Exception: ScheduleEntry.Feed matching query does not exist.
> ```

It's an error when two items with the same value are in mongo. We know the problem and the only work arround for the moment it's delete in mongo the item

**Comment by niallnsec** [comment]
Thanks for the feedback. I checked the mongo db but could not find any duplicates. Strangely enough, restarting everything caused the issue to resolve.

I was also able to fix the dynamic domains issue by adding the following to plugins/feeds/public/dynamic_dns.py before line 18:
```
            if len(line) == 0:
                continue
```
I was playing around with the Tor Exit Nodes one too, but I haven't got anywhere yet. Unfortunately I only have a tiny bit of experience with python.

**Comment by sebdraven** [comment]
Oh sorry I read too faster, forget my last answser. 
the work arround for your error, it's to stop cellery workers
delete in the collection schedule_entry. 
restart your webserver
log to the web UI
go to settings/Dataflow
when all feed are printed
you can restart cellery worker and you can start the feeds

**Comment by doomedraven** [comment]
@niallnsec check this you have fix there https://github.com/yeti-platform/yeti/pull/465/files and some of the feed related PRs, there are fixes but they still not merged, cc @tomchop 
for the incorrect url, you need to add `shop` tld to yeti.conf as extraction of tlds to handle
