### ISSUE TITLE
why feeds does not update

### ISSUE THREAD

**Issue by xmstaring** [yeti-platform/yeti#480]
Description
I have installed docker-yeti for 2days . But feeds never  updates.I exec testfeed.py  or click buttuon refresh ,it doesn't work

### Environment

| Question         | Answer
|------------------|--------------------
| OS version       |CentOS7
| Browser          | Firefox 60.0

#### Expected behavior
Let yeti update immediately!
![1563866511(1)](https://user-images.githubusercontent.com/40605666/61691250-b7e03a00-ad5d-11e9-92e4-c085df7cb81d.jpg)

**Comment by doomedraven** [comment]
check the `systemctl status yeti_feed.service`

**Comment by xmstaring** [comment]
#docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
6a2fa6da8ab8        yeti-platform       "docker-entrypoint..."   2 days ago          Up 11 hours         0.0.0.0:5000->5000/tcp   docker_yeti_1
96796deeb7ae        mongo:latest        "docker-entrypoint..."   2 days ago          Up 11 hours         27017/tcp                docker_mongodb_1
b20717ad29d2        redis:latest        "docker-entrypoint..."   2 days ago          Up 11 hours         6379/tcp                 docker_redis_1
There're 3 services in docker .I don't know whether yeti_feed.service is in yeti-platform . Whether need I  not  use  docker?

**Comment by doomedraven** [comment]
ah well if that is docker, you should search in issues before, that is already reported issue

**Comment by xmstaring** [comment]
OK,thanks very much !  I don't know whether my problem is related to this problem  "Docker errors in scheduler"
https://github.com/yeti-platform/yeti/issues/472
It seems that I have to install yeti normally

**Comment by doomedraven** [comment]
normal is without docker ;) 
as you could see in docker there is problem with feeds

**Comment by tomchop** [comment]
Yes, docker does not support systemd (which makes sense). We should create a dedicated container image for the Yeti workers.

**Comment by tomchop** [comment]
It looks like you're using docker-compose to spin up your docker images? `docker-compose.yaml` will only spin up the webserver, redis server, and mongo database. If you want all the feed, analytics, import workers etc. you should use `docker-compose-full.yaml`.

**Comment by zetahoq** [comment]
I am using Docker and everything appears to be working that I am aware of.  I think the issue is like tomchop said, not running the proper docker-compose file.
