### ISSUE TITLE
Non-admin user is unable to edit existing observable/entiy

### ISSUE THREAD

**Issue by ftanida** [yeti-platform/yeti#488]
Before opening an issue, please make do a quick search through the current issues
and the mailing list (https://groups.google.com/forum/#!forum/yeti-users) to see
if it hasn't been answered already.

### Description
Normal user is unable to either add or edit entities / observable

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | f7911cf2e3b6401c49230f93d22f7cff46eeebe9
| OS version       | Cent OS 7.6
| Browser          | Chrome for mac  75.0.3770.100

### Steps to Reproduce
1. Add new entity or observable by non-admin user
2. save it
3. tap edit button to edit saved one

#### Expected behavior
even though non-admin user, registered entity and observable should be edited
non-admin user is able to edit investigation but not entity and observable.

#### Actual behavior
Server responds 403 (forbidden)
![screenshot](https://user-images.githubusercontent.com/51103517/62423100-e401a080-b6f7-11e9-887a-d7a4f52c3fc2.png)

**Comment by doomedraven** [comment]
you can change that in `core/web/frontend/generic.py`
removing lines 81 and 101

```
if current_user.username != getattr(obj, 'created_by', None) and not current_user.has_role('admin'):
            abort(403)
```

**Comment by doomedraven** [comment]
the best solution would be to add `created_by` to entities no @tomchop ? https://github.com/yeti-platform/yeti/blob/master/core/entities/entity.py

**Comment by tomchop** [comment]
Adding created_by to entities is a bigger change, so I did a quick patch for this.
