### ISSUE TITLE
error: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by zahid1121** [yeti-platform/yeti#489]
Periodically getting the exception even while doing nothing

> ----------------------------------------
> ----------------------------------------
> Exception happened during processing of request from ('127.0.0.1', 42644)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
>     self.finish()
>   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "/usr/lib/python2.7/socket.py", line 283, in close
>     self.flush()
>   File "/usr/lib/python2.7/socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 32] Broken pipe
> ----------------------------------------
> ----------------------------------------
> Exception happened during processing of request from ('127.0.0.1', 42646)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
>     self.finish()
>   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "/usr/lib/python2.7/socket.py", line 283, in close
>     self.flush()
>   File "/usr/lib/python2.7/socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 32] Broken pipe
> ----------------------------------------
> ----------------------------------------
> Exception happened during processing of request from ('127.0.0.1', 42650)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
>     self.finish()
>   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "/usr/lib/python2.7/socket.py", line 283, in close
>     self.flush()
>   File "/usr/lib/python2.7/socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 32] Broken pipe
> ----------------------------------------
> ----------------------------------------
> Exception happened during processing of request from ('127.0.0.1', 42652)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
>     self.finish()
>   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "/usr/lib/python2.7/socket.py", line 283, in close
>     self.flush()
>   File "/usr/lib/python2.7/socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 32] Broken pipe
> ----------------------------------------
> ----------------------------------------
> Exception happened during processing of request from ('127.0.0.1', 42654)
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/lib/python2.7/SocketServer.py", line 654, in __init__
>     self.finish()
>   File "/usr/lib/python2.7/SocketServer.py", line 713, in finish
>     self.wfile.close()
>   File "/usr/lib/python2.7/socket.py", line 283, in close
>     self.flush()
>   File "/usr/lib/python2.7/socket.py", line 307, in flush
>     self._sock.sendall(view[write_offset:write_offset+buffer_size])
> error: [Errno 32] Broken pipe
> ----------------------------------------
>

**Comment by tomchop** [comment]
This doesn't seem related to Yeti. Please re-open an issue filling in the issue template as requested.
