### ISSUE TITLE
FR | Exclude know URLs\IPs when importing text/from url

### ISSUE THREAD

**Issue by chenerlich** [yeti-platform/yeti#490]
### Description
When importing a blog post or text, exclude URLs\IPs of known websites (such as twitter.com, google.com and etc), to evade tagging them as malicious after the import
helpful list: https://ahrefs.com/blog/most-visited-websites/

**Comment by tomchop** [comment]
This a tricky question. How do you suggest we maintain such list? I think it should be left for users to decide which site to include in this list or not. As mentioned on slack, one possibility is to use whatever observables are tagged `whitelisted` (or any other tag). WDYT?

**Comment by chenerlich** [comment]
```whitelisted``` sounds nice. I do think tho a strict list of URLs can be added pretty quickly and be excluded from IOCs.
