### ISSUE TITLE
MongoDB: Celery can't create indexes

### ISSUE THREAD

**Issue by xme** [yeti-platform/yeti#495]
Environment: latest git repo
MongoDB installed with auth enabled.
Credentials added in yeti.conf. Yeti works but feeds don't.
I get the following error:

Aug 13 15:06:51 ip-10-0-0-54 celery[31236]: OperationFailure: command createIndexes requires authentication

I changed the user and added "ReadWrite" & "dbAdmin" to the user. Any idea?

**Comment by tomchop** [comment]
I assume deactivating the auth (just to debug) makes the problem go away? Does MongoDB give more detailed logs about the credentials that are actually being used to carry out this operation?

**Comment by xme** [comment]
I'd like to keep it enabled because I'm sharing the instance with other apps...
The last log from MongoDB side:

2019-08-13T15:33:11.377+0000 I NETWORK  [listener] connection accepted from 127.0.0.1:52868 #303 (95 connections now open)
2019-08-13T15:33:11.377+0000 I NETWORK  [conn303] received client metadata from 127.0.0.1:52868 conn303: { driver: { name: "PyMongo", version: "3.8.0" }, os: { type: "Linux", name: "Ubuntu 18.04 bionic", architecture: "x86_64", version: "4.15.0-1043-aws" }, platform: "CPython 2.7.15.final.0" }

From Yeti:

Aug 13 15:35:21 ip-10-0-0-54 celery[31236]: [2019-08-13 15:35:21,455: ERROR/ForkPoolWorker-13] Signal handler <function connect_mongo at 0x7fe678545230> raised: OperationFailure(u'command createIndexes requires authentication',)
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]: Traceback (most recent call last):
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:   File "/usr/local/lib/python2.7/dist-packages/celery/utils/dispatch/signal.py", line 288, in send
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:     response = receiver(signal=self, sender=sender, **named)
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:   File "/opt/yeti/core/config/celeryctl.py", line 59, in connect_mongo
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:     celeryimports.loaded_modules = get_plugins()
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:   File "/opt/yeti/core/yeti_plugins.py", line 31, in get_plugins
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:     entry = obj.get_or_create(name=obj.default_values['name'])
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:   File "/opt/yeti/core/database.py", line 90, in get_or_create
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:     r = cls.objects(**select_dict).modify(upsert=True, **update_dict)
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/manager.py", line 37, in __get__
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:     queryset = queryset_class(owner, owner._get_collection())
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 208, in _get_collection
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:     cls.ensure_indexes()
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 888, in ensure_indexes
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:     collection.create_index(fields, background=background, **opts)
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1971, in create_index
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:     self.__create_index(keys, kwargs, session, **cmd_options)
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 1873, in __create_index
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:     session=session)
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:   File "/usr/local/lib/python2.7/dist-packages/pymongo/collection.py", line 252, in _command
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:     user_fields=user_fields)
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:   File "/usr/local/lib/python2.7/dist-packages/pymongo/pool.py", line 584, in command
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:     user_fields=user_fields)
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:   File "/usr/local/lib/python2.7/dist-packages/pymongo/network.py", line 158, in command
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:     parse_write_concern_error=parse_write_concern_error)
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:   File "/usr/local/lib/python2.7/dist-packages/pymongo/helpers.py", line 155, in _check_command_response
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]:     raise OperationFailure(msg % errmsg, code, response)
Aug 13 15:35:21 ip-10-0-0-54 celery[31236]: OperationFailure: command createIndexes requires authentication

**Comment by xme** [comment]
Confirmed working on a test mongod instance with auth disabled... :(

**Comment by tomchop** [comment]
I assume this starts as soon as you launch the celery workers? I tried adding authentication to mongodb and reproducing the error, but the config (e.g. username and password) does seem to be taken into account by celery to connect to mongo. 

This is the command I used to create the user auth:

```
use yeti;
db.createUser({user: "yetiadmin", pwd: "yetipassword", roles: [ { role: "dbOwner", db: "yeti" }]})
```

Then specifying `yetiadmin` and `yetipassword` in the `yeti.conf` file seems to do the trick. Can you please try again and let me know? Thanks!

**Comment by xme** [comment]
I reinstalled from scratch and it seems to be better now. Tx!
