### ISSUE TITLE
Investigation list and creation errors

### ISSUE THREAD

**Issue by thomaschillipepper** [yeti-platform/yeti#497]
### Description
An internal server error occurs by trying to create a new investigation from a new created observable. 
In addition, no investigations are showing after creating new ones, even though they exist in the database. 

### Environment
Lastest git repo
Virtualenv with the installed modules from the requirements.txt
MongoDB
Error occurs both on debug environment (port: 5000) and production. 

| Question         | Answer
|------------------|--------------------
| Git commit       | 195ce40t
| OS version       | Ubuntu 18.04

#### Expected behavior
Expected to be able to view the created investigations, and to create a new investigation from a new observable. 

#### Actual behavior
Internal errors: 
INFO:_internal:192.168.60.1 - - [19/Aug/2019 05:53:47] "POST /api/investigationsearch/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lab/venv/lib/python2.7/site-packages/flask_classy.py", line 200, in proxy
    response = view(**request.view_args)
  File "/home/lab/yeti/core/web/api/crud.py", line 53, in post
    data = self.search(query)
  File "/home/lab/yeti/core/web/api/investigation.py", line 40, in search
    return list(investigations)[page * rng:(page + 1) * rng]
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/queryset/queryset.py", line 51, in __len__
    list(self._iter_results())
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/queryset/queryset.py", line 99, in _iter_results
    self._populate_cache()
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/queryset/queryset.py", line 118, in _populate_cache
    self._result_cache.append(six.next(self))
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 1492, in __next__
    only_fields=self.only_fields)
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/base/document.py", line 722, in _from_son
    else field.to_python(value))
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/base/fields.py", line 350, in to_python
    for key, item in value.items()}
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/base/fields.py", line 350, in <dictcomp>
    for key, item in value.items()}
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/fields.py", line 687, in to_python
    return self.document_type._from_son(value, _auto_dereference=self._auto_dereference)
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/base/document.py", line 733, in _from_son
    raise InvalidDocumentError(msg)
InvalidDocumentError: Invalid data to create a `InvestigationEvent` instance.
nodes - type object 'Node' has no attribute 'id'
Traceback (most recent call last):
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lab/venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lab/venv/lib/python2.7/site-packages/flask_classy.py", line 200, in proxy
    response = view(**request.view_args)
  File "/home/lab/yeti/core/web/api/crud.py", line 53, in post
    data = self.search(query)
  File "/home/lab/yeti/core/web/api/investigation.py", line 40, in search
    return list(investigations)[page * rng:(page + 1) * rng]
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/queryset/queryset.py", line 51, in __len__
    list(self._iter_results())
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/queryset/queryset.py", line 99, in _iter_results
    self._populate_cache()
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/queryset/queryset.py", line 118, in _populate_cache
    self._result_cache.append(six.next(self))
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/queryset/base.py", line 1492, in __next__
    only_fields=self.only_fields)
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/base/document.py", line 722, in _from_son
    else field.to_python(value))
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/base/fields.py", line 350, in to_python
    for key, item in value.items()}
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/base/fields.py", line 350, in <dictcomp>
    for key, item in value.items()}
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/fields.py", line 687, in to_python
    return self.document_type._from_son(value, _auto_dereference=self._auto_dereference)
  File "/home/lab/venv/lib/python2.7/site-packages/mongoengine/base/document.py", line 733, in _from_son
    raise InvalidDocumentError(msg)
InvalidDocumentError: Invalid data to create a `InvestigationEvent` instance.

Traceback error message when selecting from the web UI --> Investigations --> List

**Comment by tomchop** [comment]
This sounds like a bug indeed, but I can't seem to reproduce it. This is what I've done:

* Add new observable using `Observables > Search & Add`
* Go to the newly added observable page
* Click on "New investigation"

Everything seems to work fine. Can you please give a bit more details on how to reproduce this bug? Thanks!

**Comment by xme** [comment]
I've the same error when trying to import data
Investigations > Import > Load data > Review observables > Click on "Import"
Get this in the logs:

Aug 21 21:19:21 fame uwsgi[26137]: ERROR:app:Exception on /api/investigationsearch/ [POST]
Aug 21 21:19:21 fame uwsgi[26137]: Traceback (most recent call last):
Aug 21 21:19:21 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
Aug 21 21:19:21 fame uwsgi[26137]:     response = self.full_dispatch_request()
Aug 21 21:19:21 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
Aug 21 21:19:21 fame uwsgi[26137]:     rv = self.handle_user_exception(e)
Aug 21 21:19:21 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
Aug 21 21:19:21 fame uwsgi[26137]:     reraise(exc_type, exc_value, tb)
Aug 21 21:19:21 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
Aug 21 21:19:21 fame uwsgi[26137]:     rv = self.dispatch_request()
Aug 21 21:19:21 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
Aug 21 21:19:21 fame uwsgi[26137]:     return self.view_functions[rule.endpoint](**req.view_args)
Aug 21 21:19:21 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/flask_classy.py", line 200, in proxy
Aug 21 21:19:21 fame uwsgi[26137]:     response = view(**request.view_args)
Aug 21 21:19:21 fame uwsgi[26137]:   File "./core/web/helpers.py", line 39, in inner
Aug 21 21:19:21 fame uwsgi[26137]:     return f(*args, **kwargs)
Aug 21 21:19:21 fame uwsgi[26137]:   File "./core/web/api/crud.py", line 53, in post
Aug 21 21:19:21 fame uwsgi[26137]:     data = self.search(query)
Aug 21 21:19:21 fame uwsgi[26137]:   File "./core/web/api/investigation.py", line 40, in search
Aug 21 21:19:21 fame uwsgi[26137]:     return list(investigations)[page * rng:(page + 1) * rng]
Aug 21 21:19:21 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/queryset.py", line 51, in __len__
Aug 21 21:19:21 fame uwsgi[26137]:     list(self._iter_results())
Aug 21 21:19:21 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/queryset.py", line 99, in _iter_results
Aug 21 21:19:21 fame uwsgi[26137]:     self._populate_cache()
Aug 21 21:19:21 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/queryset.py", line 118, in _populate_cache
Aug 21 21:19:21 fame uwsgi[26137]:     self._result_cache.append(six.next(self))
Aug 21 21:19:21 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 1492, in __next__
Aug 21 21:19:21 fame uwsgi[26137]:     only_fields=self.only_fields)
Aug 21 21:19:21 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/document.py", line 722, in _from_son
Aug 21 21:19:21 fame uwsgi[26137]:     else field.to_python(value))
Aug 21 21:19:21 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/fields.py", line 350, in to_python
Aug 21 21:19:21 fame uwsgi[26137]:     for key, item in value.items()}
Aug 21 21:19:21 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/fields.py", line 350, in <dictcomp>
Aug 21 21:19:21 fame uwsgi[26137]:     for key, item in value.items()}
Aug 21 21:19:21 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/fields.py", line 687, in to_python
Aug 21 21:19:21 fame uwsgi[26137]:     return self.document_type._from_son(value, _auto_dereference=self._auto_dereference)
Aug 21 21:19:21 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/document.py", line 733, in _from_son
Aug 21 21:19:21 fame uwsgi[26137]:     raise InvalidDocumentError(msg)
Aug 21 21:19:21 fame uwsgi[26137]: InvalidDocumentError: Invalid data to create a `InvestigationEvent` instance.
Aug 21 21:19:21 fame uwsgi[26137]: nodes - type object 'Node' has no attribute 'id'

**Comment by xme** [comment]
I just realized that I've the same error when trying to build a graph:

https://yeti.xameco.net/investigation/graph/observable/<indicator>

```
Aug 26 21:26:14 fame uwsgi[26137]: ERROR:app:Exception on /investigation/graph/observable/5d64324d235e9665ffe5b7ff [GET]
Aug 26 21:26:14 fame uwsgi[26137]: Traceback (most recent call last):
Aug 26 21:26:14 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2446, in wsgi_app
Aug 26 21:26:14 fame uwsgi[26137]:     response = self.full_dispatch_request()
Aug 26 21:26:14 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1951, in full_dispatch_request
Aug 26 21:26:14 fame uwsgi[26137]:     rv = self.handle_user_exception(e)
Aug 26 21:26:14 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in handle_user_exception
Aug 26 21:26:14 fame uwsgi[26137]:     reraise(exc_type, exc_value, tb)
Aug 26 21:26:14 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1949, in full_dispatch_request
Aug 26 21:26:14 fame uwsgi[26137]:     rv = self.dispatch_request()
Aug 26 21:26:14 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1935, in dispatch_request
Aug 26 21:26:14 fame uwsgi[26137]:     return self.view_functions[rule.endpoint](**req.view_args)
Aug 26 21:26:14 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/flask_classy.py", line 200, in proxy
Aug 26 21:26:14 fame uwsgi[26137]:     response = view(**request.view_args)
Aug 26 21:26:14 fame uwsgi[26137]:   File "./core/web/helpers.py", line 39, in inner
Aug 26 21:26:14 fame uwsgi[26137]:     return f(*args, **kwargs)
Aug 26 21:26:14 fame uwsgi[26137]:   File "./core/web/frontend/investigations.py", line 47, in graph_node
Aug 26 21:26:14 fame uwsgi[26137]:     investigation.add([], [node])
Aug 26 21:26:14 fame uwsgi[26137]:   File "./core/investigation.py", line 124, in add
Aug 26 21:26:14 fame uwsgi[26137]:     self._node_changes('add', self.add_to_set, links, nodes)
Aug 26 21:26:14 fame uwsgi[26137]:   File "./core/investigation.py", line 121, in _node_changes
Aug 26 21:26:14 fame uwsgi[26137]:     self.modify(push__events=event, updated=datetime.utcnow())
Aug 26 21:26:14 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/document.py", line 295, in modify
Aug 26 21:26:14 fame uwsgi[26137]:     updated = self._qs(**query).modify(new=True, **update)
Aug 26 21:26:14 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/queryset/base.py", line 657, in modify
Aug 26 21:26:14 fame uwsgi[26137]:     result = self._document._from_son(result, only_fields=self.only_fields)
Aug 26 21:26:14 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/document.py", line 722, in _from_son
Aug 26 21:26:14 fame uwsgi[26137]:     else field.to_python(value))
Aug 26 21:26:14 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/fields.py", line 350, in to_python
Aug 26 21:26:14 fame uwsgi[26137]:     for key, item in value.items()}
Aug 26 21:26:14 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/fields.py", line 350, in <dictcomp>
Aug 26 21:26:14 fame uwsgi[26137]:     for key, item in value.items()}
Aug 26 21:26:14 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/fields.py", line 687, in to_python
Aug 26 21:26:14 fame uwsgi[26137]:     return self.document_type._from_son(value, _auto_dereference=self._auto_dereference)
Aug 26 21:26:14 fame uwsgi[26137]:   File "/usr/local/lib/python2.7/dist-packages/mongoengine/base/document.py", line 733, in _from_son
Aug 26 21:26:14 fame uwsgi[26137]:     raise InvalidDocumentError(msg)
Aug 26 21:26:14 fame uwsgi[26137]: InvalidDocumentError: Invalid data to create a `InvestigationEvent` instance.
Aug 26 21:26:14 fame uwsgi[26137]: nodes - type object 'Node' has no attribute 'id'
```

**Comment by zetahoq** [comment]
I think the fix is pretty easy. At least it seemed to solve a lot of issues I was having.

Change this
```class InvestigationEvent(EmbeddedDocument):
    kind = StringField(required=True)
    links = ListField(EmbeddedDocumentField(InvestigationLink))
    nodes = ListField(ReferenceField('Node'))
    datetime = DateTimeField(default=datetime.utcnow)```

to this 
```
class InvestigationEvent(EmbeddedDocument):
    kind = StringField(required=True)
    links = ListField(EmbeddedDocumentField(InvestigationLink))
    nodes = ListField(ReferenceField('Node', dbref=True))
    datetime = DateTimeField(default=datetime.utcnow)
```
Changed the nodes line

**Comment by tomchop** [comment]
@xme I just pushed https://github.com/yeti-platform/yeti/tree/fix-497, could you please check it out and let me know if this fixes your issue? I can't reproduce on my side... (could you also give me an output of `pip freeze`?)

**Comment by tomchop** [comment]
Update: I finally was able to reproduce (I reinstalled a fresh virtualenv from requirements.txt instead of Pipfile). I'll try to update the libraries to their latest version and sync pipfile with requirements.txt.

**Comment by xme** [comment]
Does not seem better :(
Applied the fix suggested by zetahoq & performed a git pull (running the latest code now)
