### ISSUE TITLE
"Please wait for the import process to finish ..." forever...

### ISSUE THREAD

**Issue by xme** [yeti-platform/yeti#499]
I just reinstalled a fresh Yeti instance and started to play with it.
I'm trying to import some content but it does not work... The server just says "Please wait for the import process to finish ...".
Tried an URL and a file.

PS: For the file, I had to create manually the directory <YETIHOME>/storage/

Any idea?
Nothing relevant in the logs...

**Comment by gaelmuller** [comment]
Is the oneshot worker running ? Can you paste its logs ?

Le mer. 21 août 2019 à 21:03, Xavier Mertens <notifications@github.com> a
écrit :

**Comment by xme** [comment]
It wasn't indeed... I created the user *after* starting workers for the 1st time and had to restart them. Stupid me! Tx for the hint!
