### ISSUE TITLE
General Error - ' cloud.googleupdating.net' is not a valid 'Hostname'

### ISSUE THREAD

**Issue by sebdraven** [yeti-platform/yeti#502]
the validator of insert a new observable in the view investigation returns this error. 

if I use the lib validators, true is returned.

**Comment by tomchop** [comment]
There's a space before the ` cloud` part. Maybe we could add a `trim()` call to the validator? Or use lib validators and be done with it

**Comment by doomedraven** [comment]
thats is a global issue, not only in hostnames, the same in here https://github.com/yeti-platform/yeti/pull/353 so you need trim everything

**Comment by tomchop** [comment]
Maybe we should definitely stop validating things ourselves and use validators instead. @sebdraven  can you fix this? @doomedraven do you think validators could be used for Urls as well?

**Comment by doomedraven** [comment]
Which validators do you mean?
