### ISSUE TITLE
Source overload on observables

### ISSUE THREAD

**Issue by chenerlich** [yeti-platform/yeti#503]
### Description
Some observables can have an overload of the same source.
I think it should be downsized to 1 per source.
![image](https://user-images.githubusercontent.com/17673075/63686113-c365cb80-c809-11e9-863e-40b2ea8282c4.png)

**Comment by doomedraven** [comment]
open that observable and post image from there, there should be different context or something like that

**Comment by chenerlich** [comment]
@doomedraven - Yeah it updates the first seen.
Maybe in the frontend side it can be fixed by "..." or something.
![image](https://user-images.githubusercontent.com/17673075/63686844-a92ced00-c80b-11e9-983a-0a82d364f7c2.png)

**Comment by doomedraven** [comment]
the easier fix is to remove first_seen from context

**Comment by doomedraven** [comment]
thats all what you need to do https://github.com/yeti-platform/yeti/pull/504

**Comment by sebdraven** [comment]
this issue is resolved with PR #504
