### ISSUE TITLE
Analytics not work

### ISSUE THREAD

**Issue by Lichtsinnig** [yeti-platform/yeti#509]
I have no tasks in the section:
YETI-> Admin-> Analytics
The page contains only:

Scheduled
One-shot
Inline

screenshot
https://dropmefiles.com/VpMLg

**How can I run analytics jobs?**

**Comment by sebdraven** [comment]
could you check the dataflow view please ?

**Comment by Lichtsinnig** [comment]
How can i do this?

**Comment by sebdraven** [comment]
Yeti  -> Settings -> Dataflow

**Comment by Lichtsinnig** [comment]
https://dropmefiles.com/oMxzE

**Comment by sebdraven** [comment]
Have you launch the worker for analytics ?

**Comment by Lichtsinnig** [comment]
I have a default installation. Additionally, I did not configure anything.

**Comment by sebdraven** [comment]
Ok so follow the documentation to getting start

**Comment by Lichtsinnig** [comment]
I added data, but enrichment does not occur.
How can I start enrichment?


I use documentation https://yeti-platform.readthedocs.io. There I did not see how I can tune the launch of the Scheduled jobs

**Comment by sebdraven** [comment]
you have all in https://yeti-platform.readthedocs.io/en/latest/installation.html in section Quick & dirty or Install systemd services

**Comment by Lichtsinnig** [comment]
https://dropmefiles.com/mwDCm

**Comment by sebdraven** [comment]
Ok, try to restart the web service

**Comment by Lichtsinnig** [comment]
reboot does not help :(

**Comment by Lichtsinnig** [comment]
data feed are added.
But there is no enriching information. for example

https://dropmefiles.com/IOhgU

**Comment by 0xRet** [comment]
Hello,
I can't see the initial screenshots but I have the same problem with analytics when using Firefox on MacOS. 
Failure while loading js : /staticfiles/yeti/js/analytics.js 

Try changing your web browser (safari or chrome) works fine, Firefox on Windows too.
Hope that helps !

**Comment by sebdraven** [comment]
Ok check  if you have an ublock or add block

**Comment by sebdraven** [comment]
Cause, I've no answer I consider it's good !
