### ISSUE TITLE
Running Yeti in a virtualenv: no Python application found

### ISSUE THREAD

**Issue by smclinden** [yeti-platform/yeti#510]
### Description
Running UWSGI  with a virtualenv (Python 2.7) build of Yeti I get "no python application found" errors. The configuration followed the installation instructions and I added a -H to the uwsgi command to specify the path to the venv.

Running ./yeti.py works without errors.

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 35c4388c982042d764bfe0834a9bf72ecbb65a65

| OS version       | Ubuntu 19.04
| Browser          | Chrome 76.0.3809.132

### Steps to Reproduce
1. git clone the repo
2. cd yeti
3. virtualenv -p /usr/bin/python2.7 venv2.7
4. source venv2.7/bin/activate
5. pip install -r requirements.txt
6. pip install uwsgi
7. Copied extras/systemd to /lib/systemd/system
8. Enabled services and started them

[Unit]
Description=Yeti UWSGI server
After=mongodb.service redis.service

[Service]
Type=simple
User=yeti
WorkingDirectory=/opt/yeti
ExecStart=/usr/bin/uwsgi -H /opt/yeti/venv2.7 --socket 127.0.0.1:8000 -w yeti --callable webapp --processes 4 --
threads 2 --stats 127.0.0.1:9191
Restart=always
KillSignal=SIGQUIT
Type=notify
StandardError=syslog
NotifyAccess=all

[Install]
WantedBy=multi-user.target

#### Expected behavior
I'm expecting it to work.

#### Actual behavior
Sep  9 15:06:53 docker uwsgi[2411]: --- no python application found, check your startup logs for errors ---
Sep  9 15:06:53 docker uwsgi[2411]: [pid: 3071|app: -1|req: -1/19] 127.0.0.1 () {50 vars in 855 bytes} [Mon Sep  9 15:06:53 2019] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 1)
Sep  9 15:06:53 docker uwsgi[2411]: --- no python application found, check your startup logs for errors ---
Sep  9 15:06:53 docker uwsgi[2411]: [pid: 3064|app: -1|req: -1/20] 127.0.0.1 () {50 vars in 804 bytes} [Mon Sep  9 15:06:53 2019] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)

**Comment by sebdraven** [comment]
Have you correct the pb ?
