### ISSUE TITLE
Feeds shows duplicate data

### ISSUE THREAD

**Issue by s-shubh** [yeti-platform/yeti#512]
### Description
I have created **custom** **feeds** **script** which processes IPs from Emerging Threats Feeds to their threat score and threat category. YETI is integrated with cortex and the hive and querying of observable is working properly as expected. 

But recently I faced a problem as while searching for IP, I found its past values along with new entries. Please help me to prevent older data to be persisted in the YETI database. 

### Environment

| Question         | Answer
|------------------|--------------------
| OS version       | CentOS 7
| Browser          | Chroms

**Comment by dumprop** [comment]
Any data can be useful in one way or another. 
If you need to search only for up-to-date data, then you need to look at the state of the tag (expired or not)
Also, you can set custom value at the script
https://github.com/yeti-platform/yeti/blob/master/plugins/analytics/public/expire_tags.py#L21
