### ISSUE TITLE
Where to set the otx_key for OTXAlienvault feeds

### ISSUE THREAD

**Issue by davanitz** [yeti-platform/yeti#518]
> yeti/plugins/feeds/public/otx_alienvault.py", line 40, in update
> assert otx_key and number_page

**Comment by doomedraven** [comment]
looks like it missed in yeti.conf. you can add that section checking how it parsed in otx_alientvault.py

**Comment by tomchop** [comment]
You need to add sections like this:

```
[otx]
otx_key = blah
number_page = 1

**Comment by YuningMiao** [comment]
So I added my credential to /opt/yeti/yeti.conf, /opt/yeti/yeti.conf.sample, and had the server rebooted, I still get the same error message, did I modify the wrong file?

**Comment by phutch11** [comment]
Don't think you did anything wrong - I also updated the repo saw the section for OTX and Abuse in the .conf - filled them in. Abuse works fine now - OTX still returns "Detail : Authentication required". Copying and pasting the API link using my key directly into a browser also returns the same error. Dont think it's YETI related. I have disabled OTX for now.
