### ISSUE TITLE
Empty Analytics 

### ISSUE THREAD

**Issue by cyberpewpewpew** [yeti-platform/yeti#519]
Git: commit 35c4388c982042d764bfe0834a9bf72ecbb65a65

Analytics is empty. All yeti workers are active and running though.
Feeds are running fine. What could be the issue here? Thanks.

![image](https://user-images.githubusercontent.com/55482903/65224783-71595280-daf6-11e9-9694-f1203bd61e78.png)

**Comment by 0xRet** [comment]
Hello,
I have the same problem when using Firefox on MacOS. 
Failure while loading js : /staticfiles/yeti/js/analytics.js 

Try changing your web browser (safari or chrome) works fine, Firefox on Windows too.

**Comment by tomchop** [comment]
This definitely sounds like an ad blocker. Maybe analytics.js is not the best name to use here...
