### ISSUE TITLE
Can anyone suggest a simply way to reset the yeti user password from Mongo shell?

### ISSUE THREAD

**Issue by smclinden** [yeti-platform/yeti#520]
### Description
Credentials not working for Yeti

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 35c4388c982042d764bfe0834a9bf72ecbb65a65
| OS version       | Centos 7
| Browser          | Any

### Steps to Reproduce

Reset password for user "yeti" no longer works or is not remembered.

**Comment by tomchop** [comment]
the most user-friendly way I can think of is creating a new user with admin privileges and use the web interface for revoking / changing credentials of another user. 

An alternative (if you're completely locked out) would be to remove this check (https://github.com/yeti-platform/yeti/blob/f7911cf2e3b6401c49230f93d22f7cff46eeebe9/core/auth/local/user_management.py#L95) and edit your own user profile to reset your password.
