### ISSUE TITLE
constant redirect to login screen

### ISSUE THREAD

**Issue by phate1** [yeti-platform/yeti#529]
### Description
after logging into the web ui it keeps logging me out randomly and very often and will then get into loops of kicking me straight to the login page after logging in despite the logs showing that I logged in.

the server is on an OpenStack server and the client is connecting through an OpenVPN connection

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | commit a3405bc9974652816a130ccb3915bc56c4f6f85c
| OS version       | Ubuntu 18.04 (yeti running in docker)
| Browser          | 77.0.3865.90 (Official Build) (64-bit) just tried with edge and don't seem to be able to log in at all

### Steps to Reproduce
1. build docker using instructions
1. connect client via OpenVPN (UDP and TCP tried)
1. log into server
1. click throu a few pages and get signed out

#### Expected behavior
not to sign me out

#### Actual behavior
keep getting thrown back to the login page

not too sure where to go from here the docker logs show me logging in and no other issues I can see any suggestions on how to get this working appreciated.

**Comment by phate1** [comment]
stright install on the system seems to be working must be something dodgy with my docker setup have been having all sorts of mtu issue maybe something to do with that ill just use outside docker

**Comment by tomchop** [comment]
If you ever experience this behavior again, please reopen this issue and paste the HTTP request / response headers that you get - will be very helpful for debugging. Thanks! :)

**Comment by mikewiacek** [comment]
Getting the same thing!  Also using docker. Commit f220d15f9a075238bc4ee07369dfd0e3d34cfe9e

It's very weird. From the sign in page, I will hit the button to sign in, and then I end up on the sign in page. I do it again, same thing. Fourth time, I get to an actual page. After that, any action takes me back to the sign in page. A few attempts, and then I'm back in again.  

I've attached an HAR file. I've removed the domain of my instance, replacing it with example.com and any other sensitive values. As this is a test instance, the account password is in the doc but it's not sensitive.

[reqs_har.txt](https://github.com/yeti-platform/yeti/files/4345891/reqs_har.txt)

**Comment by mikewiacek** [comment]
Figured this out. Yeti is using flask for login. I'm running yeti behind GCP's load balancer which has each request come in on  random IP addresses. Flask's basic session protection is enabled by default, which includes a hash of the remote IP in the session cookie. This breaks if requests are coming from different IPs (from the perspective of yeti/flask).  Thus some requests work, some don't, when the IPs match up.

**Comment by tomchop** [comment]
Hey @mikewiacek, thanks for digging into this, and great catch! I read through flask-login's [documentation](https://flask-login.readthedocs.io/en/latest/#session-protection) and it seems that this is related to the session protection somehow. After some digging, it seems like I never implemented the remember-me mechanism 😅 

Can you checkout the `remember` branch and let me know if this fixes your problem?

**Comment by phate1** [comment]
hey

couple of years late but finally come back to yeti and hitting the same issue. I figure the remember branch is a little dated now but from what I could see it was just adding the additional arguments to `login_user` in the 3 lines of code. I've manually added them and performed a docker-compose build and docker-compose up and still getting the same issues with logins taking multiple attempts and random logouts.

caught the header info when I clicked on useradmin and it booted my back to the login screen in case its useful copied that below:

```
Request URL: http://192.168.2.195:8080/useradmin/
Request Method: GET
Status Code: 302 FOUND
Remote Address: 192.168.2.195:8080
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 241
Content-Type: text/html; charset=utf-8
Location: /login?next=%2Fuseradmin%2F
Set-Cookie: session=eyJfZmxhc2hlcyI6W3siIHQiOlsibWVzc2FnZSIsIlBsZWFzZSBsb2cgaW4gdG8gYWNjZXNzIHRoaXMgcGFnZS4iXX1dfQ.YwiiuA.lkwl-AiFMimDR-SDFCmo2UbY7xE; HttpOnly; Path=/
Vary: Cookie
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Connection: keep-alive
Cookie: session=.eJwljjtuAzEMBe-iOgV_IkVfxqAoEkm7jqsgd88C6V7xZjA_49lXvT7H4_t618d4fp3xGGQWbrCtlvIizyjm3gAuysZEZZ1aGQYsK4QO8a6eJ2btHbMLARRVBHLNMgxqa_B2cDVsub2xSzuQJWuiqvBKzHSkzTrukPerrv8aVVgqWMJUoTcKtEkx7iFrLgc5SlMmI_oRrhW9oJ22yFl4VtquqiPiRfcheE1Ok5zHtmTbOaKOurHQqKjkSKfDzaq6Qo3fP_5OUIk.YwiiqA.SEaK_CQuAMLtbnQV2ijxLWl9AXw
Host: 192.168.2.195:8080
Referer: http://192.168.2.195:8080/observable/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36


Request URL: http://192.168.2.195:8080/login?next=%2Fuseradmin%2F
Request Method: GET
Status Code: 200 OK
Remote Address: 192.168.2.195:8080
Referrer Policy: strict-origin-when-cross-origin
Content-Length: 3290
Content-Type: text/html; charset=utf-8
Set-Cookie: session=eyJfZnJlc2giOmZhbHNlfQ.YwiiuA.k7QewpIeudJ_kQBfY9lwvi5CiD0; HttpOnly; Path=/
Vary: Cookie
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8
Connection: keep-alive
Cookie: session=eyJfZmxhc2hlcyI6W3siIHQiOlsibWVzc2FnZSIsIlBsZWFzZSBsb2cgaW4gdG8gYWNjZXNzIHRoaXMgcGFnZS4iXX1dfQ.YwiiuA.lkwl-AiFMimDR-SDFCmo2UbY7xE
Host: 192.168.2.195:8080
Referer: http://192.168.2.195:8080/observable/
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
```

let me know if there is anything else I can provide to help on this one.

Pete
