### ISSUE TITLE
Domain Name Import Fails with Underscores

### ISSUE THREAD

**Issue by johnfromthefuture** [yeti-platform/yeti#53]
### Description
From what I can tell, importing domain names when those names have an underscore character does not work. Here are some samples (replaced the periods to prevent people from clicking on potentially malicious domain links...):

```
ERROR:root:Invalid hostname: gb_validateapplecareassitancesecurelog_in(dot)verfiction1(dot)link
ERROR:root:Invalid hostname: gb_validateapplecareassitancesecurelog_in(dot)vrfied1(dot)link
ERROR:root:Invalid hostname: gb_validateapplecareassitancesecurelog_in(dot)vrify1(dot)link
ERROR:root:Invalid hostname: hack_king10(dot)net23(dot)net
```

My initial thought is this may be related to the tldexport package used to split up the hostname for validation but I haven't had time to fully run through it.

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 37f154d212ea5440e8350c86bb4f1de13339dec8
| OS version       | Not relevant
| Browser          | Chrome 56.0.2924.87

### Steps to Reproduce
Import hostname observable with an underscore via a feed script.

#### Expected behavior
No, don't die.

#### Actual behavior
Death to domains with underscores.

**Comment by johnfromthefuture** [comment]
Seems to be related to idna...
```
>>> idna = unicode(idna.encode(domain.lower()))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/idna/core.py", line 354, in encode
    result.append(alabel(label))
  File "/usr/lib/python2.7/dist-packages/idna/core.py", line 275, in alabel
    check_label(label)
  File "/usr/lib/python2.7/dist-packages/idna/core.py", line 252, in check_label
    raise InvalidCodepoint('Codepoint {0} at position {1} of {2} not allowed'.format(_unot(cp_value), pos+1, repr(label)))
idna.core.InvalidCodepoint: Codepoint U+005F at position 3 of u'gb_validateapplecareassitancesecurelog_in' not allowed
```

Reference: https://github.com/kjd/idna/issues/17

**Comment by johnfromthefuture** [comment]
I wonder if the best approach would be to separate domains into a separate observable that doesn't apply this check?

**Comment by tomchop** [comment]
This is annoying. Underscores are valid in subdomains, but not in domains, and I think the author of idna is mixing both up.

I see two solutions:

* Forking IDNA and patching it (with an appropriate PR), referencing our version in Yeti's `requirements.txt`
* Adapting Yeti's logic to the faults in idna, doing extra checks if the hostnames contain underscores. 

I think the second solution adds a lot of complexity to the code for a relatively incomplete solution. I would rather go for the first one.

**Comment by tomchop** [comment]
Turns out underscores are not tolerated in IDNA, but accepted in subdomains. Changed the code to reflect that.
