### ISSUE TITLE
ExpireTags on Analytics page in ERROR state

### ISSUE THREAD

**Issue by hyperbaba** [yeti-platform/yeti#531]
After some time after installation this showed up on my analytics page in Scheduled part. Tried to restart workers with no change. Can't debug it because i don't know where to look. Can anyone help please?

**Comment by 0xRet** [comment]
Hello, I currently have the same problem, it seems to be related to a unicode emoji character: 
Observable was created successfully but it seems to be not considered not valid when trying to call expire_tag

[2019-10-31 01:48:04,758: ERROR/ForkPoolWorker-1] Error running Analytics ExpireTags: 'https://🐮.co.pe/~vacacope/cgi-bin/WELLS/red2.html' is not a valid 'Url'

**Comment by hyperbaba** [comment]
Looks like the process fails when the observable string has non latin chars. For me fails on some url  with indian letters. The error in the log said "Not a valid url"

**Comment by tomchop** [comment]
That 🐮 URL is giving problems to many users, heh. We're working on a fix. Thanks!

**Comment by martinr103** [comment]
Had the same issue.
There are a lot more characters, that break the ExpireTags job.
For example something like the Thai characters:   http://เทคนิคการเล่นบาคาร่า.net

Don't you want to consider using pythons 'regex' module instead of the 're' module (in general) ?
The former has apparently a much better unicode support.
https://pypi.org/project/regex/

**Comment by hyperbaba** [comment]
Did someone pinpoint to the problem above so we can fix it?

**Comment by martinr103** [comment]
I have currently applied a fix in our local installation, by changing the line #4 in core/observables/observable.py, from:
import re
to
import regex as re

Evaluating if it "behaves" well.
So far it looks promising.  The ERROR in the Analytics ExpireTags has disappeared.

The 'regex' module is said to be backward compatible with 're' ... so hopefully all will work fine.
But at the same time the observable.py is a core class - so who knows if there can be side effects. (?)

Maybe one of the Yeti devs could confirm, if the change from 're' to 'regex' is ok - or will it likely cause problems elsewhere?

**Comment by hyperbaba** [comment]
That's great, it worked for me too. Thank You very much.

**Comment by martinr103** [comment]
And why is this completed ?

**Comment by tomchop** [comment]
Good question, no idea why it was marked as "completed". We're declaring issue bankruptcy, since we're launching a completely redesigned version of Yeti in the days to come.
