### ISSUE TITLE
Being able to tag /24 IP ranges

### ISSUE THREAD

**Issue by frenchbox** [yeti-platform/yeti#542]
I'd like to be able to tag whole IP ranges. For blocklisting or else. 192.168.254.0/24

Please add this feature if you would.

P.S. Crocodiles are lazy animals and like limiting their movements.

**Comment by frenchbox** [comment]
I'd like to be able to tag whole IP ranges. For blocklisting or else. 192.168.254.0/24

Please add this feature if you would. 

P.S. Crocodiles are lazy animals and like limiting their movements.

**Comment by tomchop** [comment]
You can select many IPs by searching for a regular expression that matches: `192\.168\.254\.[0-9]{1,3}` would do the trick.

Please refer to the book below for more information on how to regex:

![image](https://user-images.githubusercontent.com/1257972/70731924-df817000-1d07-11ea-90f7-71e9b440c1a7.png)

**Comment by frenchbox** [comment]
Thanks for swift attention to my amphibian needs. And the ORLY reference - they are the best. 
I particularly liked the one below. 

![image](https://user-images.githubusercontent.com/5182951/70743954-11eb9700-1d21-11ea-8db3-b13c4e6e69b1.png)

You'll forgive my reptilian brain, which is probably not very keen at explaining use-cases. 

What I intended to do is blacklisting full ranges of known bulletproof hosters by adding an appropriate tag to a given IP range. When I try doing it using your regex hack, I get an error message:

"Type guessing failed for 1 observables. Try setting it manually."

So, to put it down in green and white: I want to be able to associate a specific blacklist (or blocklist) tag to an IP range. 


Muchas gracias

**Comment by frenchbox** [comment]
To close down the issue, a Lazy Lizard Solution :

<img width="1438" alt="Lazy Lizard" src="https://user-images.githubusercontent.com/5182951/71266864-935aaf00-2349-11ea-8480-40a8f8aeebeb.png">

found in:

<img width="327" alt="copypaste" src="https://user-images.githubusercontent.com/5182951/71266943-be450300-2349-11ea-86c4-fbf781bbb779.png">

Thank you very much!
