### ISSUE TITLE
Cant update some feeds

### ISSUE THREAD

**Issue by h0n3yc4k3** [yeti-platform/yeti#546]
Before opening an issue, please make do a quick search through the current issues
and the mailing list (https://groups.google.com/forum/#!forum/yeti-users) to see
if it hasn't been answered already.

### Description
[Please provide a description of the issue encountered]

### Environment
| Question         | Answer
|------------------|--------------------
| Git commit       | 481044a862846b622b30c454b4cc8a91c9b00228
| OS version       | Ubuntu 18.04

### Steps to Reproduce
git clone and install yeti
click to update openfish feed

#### Expected behavior
Update the feed 

#### Actual behavior
Each symbol is new line
![unknown](https://user-images.githubusercontent.com/34004367/72875891-5007ad80-3d06-11ea-8a81-7cc20f9a72f0.png)

**Comment by h0n3yc4k3** [comment]
I changed back `return '\n'.join(list(new_data_set)) ` to `return list(new_data_set)` and it solved my problem

**Comment by tomchop** [comment]
Thanks for flagging! This should be fixed by #547, closing out.
