### ISSUE TITLE
Would love to delete links in investigation graph

### ISSUE THREAD

**Issue by gamelinux** [yeti-platform/yeti#55]
### Description
Some times Im clumsy and ad a link between two nodes that should not be there. Then I get sad when I cant delete it. Solution for has been to delete on of the nodes, reload the webpage, add the node and re-add new links. If I dont reload the webpage, it will add the old links if you try to add the node again.

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 0ece661ab7b37c7f95a63302a28cba19051b8adf
| OS version       | Ubuntu 16.04.2
| Browser          | Firefox 52.0.2

### Steps to Reproduce
1. In investigation, add two nodes.
2. Add a link between the nodes
3. No way to delete the link, help :)

#### Expected behavior
Some button or way to delete just the link, without doing the long hack of deleting the node and all its link.
#### Actual behavior
No way to delete links :(

**Comment by mthlvt** [comment]
+1

**Comment by DigiAngel** [comment]
+1

**Comment by axpatito** [comment]
+1
