### ISSUE TITLE
Add observable type JA3

### ISSUE THREAD

**Issue by dumprop** [yeti-platform/yeti#550]
JA3 is a method for creating SSL/TLS client fingerprints that should be easy to produce on any platform and can be easily shared for threat intelligence

More info: https://github.com/salesforce/ja3

Can it be helpful for yeti?

**Comment by tomchop** [comment]
Yes, definitely! It would be nice to add it as an observable type. Where would you say we would get the "source data" from?

**Comment by h0n3yc4k3** [comment]
Abuse have a ja3 feed: https://sslbl.abuse.ch/blacklist/ja3_fingerprints.csv
