### ISSUE TITLE
Centos 7 - yeti.py syncdb - Error : no module named mongoengine

### ISSUE THREAD

**Issue by 3lacksku77** [yeti-platform/yeti#556]
This is the first time I'm installing YETI. after a long struggle I managed to come upto last stage of the installation guide (OS is CentOS 7). Now while running yeti.py Its thowing error "no module named mongoengine". I have tried uninstalling the module and uprading it to latest. I'm able to import the same module inside python interpreter. sharing the screenshot for better clarity. Any help is appreciated.

![image](https://user-images.githubusercontent.com/12095514/75603436-38d19200-5af4-11ea-84d9-6ca5bc4e2e63.png)

**Comment by 3lacksku77** [comment]
`
[yetiuser@myeti yeti]$
[yetiuser@myeti yeti]$ sudo python yeti.py syncdb
Traceback (most recent call last):
  File "yeti.py", line 7, in <module>
    from core.web import webapp
  File "/opt/yeti/core/__init__.py", line 2, in <module>
    from core.exports import Export
  File "/opt/yeti/core/exports/__init__.py", line 1, in <module>
    from core.exports.export import ExportTemplate
  File "/opt/yeti/core/exports/export.py", line 10, in <module>
    import mongoengine
ImportError: No module named mongoengine
[yetiuser@myeti yeti]$
[yetiuser@myeti yeti]$
[yetiuser@myeti yeti]$ python
Python 2.7.5 (default, Aug  7 2019, 00:51:29)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mongoengine
>>>
[yetiuser@myeti yeti]$

`

**Comment by tomchop** [comment]
Hello! I'm sorry to hear you had a hard time with the installation. Feel free to open another issue to discuss this.

Here, it seems that the `sudo` command is loading root's python environment, where mongoengine is not installed. Is there any particular reason you're running the command through `sudo`? How did you install the dependencies?

**Comment by 3lacksku77** [comment]
Hi @tomchop,

I changed the ownership of the yeti's root folder (/opt/yeti in my case) and the /var/log/yeti/user_activity.log file from root to the user account and it worked.

Thank you for the tip.
