### ISSUE TITLE
Update documentation wrt bootstrap

### ISSUE THREAD

**Issue by StefanKelm** [yeti-platform/yeti#56]
There are several links to https://raw.githubusercontent.com/yeti-platform/yeti/master/extras/bootstrap.sh

These should be updated to centos_bootstrap.sh and ubuntu_bootstrap.sh, respectively.

(also at http://yeti-platform.readthedocs.io/en/latest/installation.html)

**Comment by gaelmuller** [comment]
I believe this was fixed.
