### ISSUE TITLE
/core/feed.py run error

### ISSUE THREAD

**Issue by hadenxx** [yeti-platform/yeti#561]
Traceback (most recent call last):
  File "yeti.py", line 7, in <module>
    from core.web import webapp
  File "/root/yeti/core/__init__.py", line 5, in <module>
    from core.feed import Feed
  File "/root/yeti/core/feed.py", line 354
    r = self._make_request(method=method, headers=headers, auth=auth, params=params, data=data verify=verify)

**Comment by sebdraven** [comment]
Hi !
could you past all the TarceBack please :) 

Thank a lot !

**Comment by tomchop** [comment]
Should be fixed in https://github.com/yeti-platform/yeti/commit/f5e78957e049570561d694834613d9aa70a9d655

I blame @doomedraven :P

**Comment by doomedraven** [comment]
ups, sorry O:-)

**Comment by hadenxx** [comment]
Another at  /core/feed.py line 354 ,  data Undefined and “,” missing
r = self._make_request(method=method, headers=headers, auth=auth, params=params, data=data verify=verify)

**Comment by doomedraven** [comment]
fix is here https://github.com/yeti-platform/yeti/pull/562
