### ISSUE TITLE
Cannot Launch yeti - ImportError: No module named mongoengine

### ISSUE THREAD

**Issue by ichintu** [yeti-platform/yeti#566]
Hello, I am unable to launch yeti. Seeing the error below. I have verified that mongoengine is installed and i can manually import it in python with no issues. I am running the current git version and I have installed requirements.txt with no issues. Running in Ubuntu 16.04 inside virtualenv. I have checked its not a permission issue like in issue 556. I am not running it as sudo user.

Thanks

`yeti@yeti:/opt/yeti$ source venv/bin/activate
(venv) yeti@yeti:/opt/yeti$ ./yeti.py syncdb
Traceback (most recent call last):
  File "./yeti.py", line 7, in <module>
    from core.web import webapp
  File "/opt/yeti/core/__init__.py", line 1, in <module>
    from mongoengine import *
ImportError: No module named mongoengine
`

**Comment by sebdraven** [comment]
the lib mongengine is installed in virtualenv ?
