### ISSUE TITLE
Can someone explain why there are two kind of timestamps like first/last seen and created/tagged. Which one of them is the timestamp of the source before the acquisition

### ISSUE THREAD

**Issue by AnthonyK95** [yeti-platform/yeti#567]
Before opening an issue, please make do a quick search through the current issues
and the mailing list (https://groups.google.com/forum/#!forum/yeti-users) to see
if it hasn't been answered already.

### Description
[Please provide a description of the issue encountered]

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log | head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3
| Browser          | Chrome 56.0.2924.87

### Steps to Reproduce
1. git clone the repo
1. cd yeti
1. pip install -r
1. observe stacktrace

#### Expected behavior
[How are you expecting the application to behave?]

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]

**Comment by tomchop** [comment]
That's first seen. If there's no timestamp in the source, then the first_seen will be the date at which the observable is entedered in the DB.

**Comment by AnthonyK95** [comment]
And how are we suppose to know if the observable has a timestamp from the source?

**Comment by tomchop** [comment]
You can check the source directly. Or if the first_seen is the same as created_at, there are big changes that there's no source timestamp :)
