### ISSUE TITLE
Docker - yeti_beat not loading due missing python lib

### ISSUE THREAD

**Issue by asucrews** [yeti-platform/yeti#568]
### Description
Docker - yeti_beat not loading due missing python lib

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       |  138613b1956828e0b403689ddd3104b8ff39b91d
| docker              |  19.03.8
| dcoker-compse | 1.25.5, build 8a1c60f6
| OS version        |  ubuntu 20.03
| Browser            | Version 80.0.3987.163 (Official Build) (64-bit)

### Steps to Reproduce
1. git clone the repo
1. cd yeti/extra/docker
1. docker-compse up

#### Expected behavior
Yeti to run

#### Actual behavior

yeti-beat_1       | wait-for-it.sh: mongodb:27017 is available after 0 seconds
yeti-beat_1       | wait-for-it.sh: waiting 15 seconds for redis:6379
yeti-beat_1       | wait-for-it.sh: redis:6379 is available after 0 seconds
yeti-beat_1       | Traceback (most recent call last):
yeti-beat_1       |   File "/usr/local/bin/celery", line 8, in <module>
yeti-beat_1       |     sys.exit(main())
yeti-beat_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 16, in main
yeti-beat_1       |     _main()
yeti-beat_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 322, in main
yeti-beat_1       |     cmd.execute_from_commandline(argv)
yeti-beat_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 496, in execute_from_commandline
yeti-beat_1       |     super(CeleryCommand, self).execute_from_commandline(argv)))
yeti-beat_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 298, in execute_from_commandline
yeti-beat_1       |     return self.handle_argv(self.prog_name, argv[1:])
yeti-beat_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 488, in handle_argv
yeti-beat_1       | celery beat v4.3.0 (rhubarb) is starting.
yeti-beat_1       |     return self.execute(command, argv)
yeti-beat_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 420, in execute
yeti-beat_1       |     ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
yeti-beat_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 302, in run_from_argv
yeti-beat_1       |     sys.argv if argv is None else argv, command)
yeti-beat_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 386, in handle_argv
yeti-beat_1       |     return self(*args, **options)
yeti-beat_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 252, in __call__
yeti-beat_1       |     ret = self.run(*args, **kwargs)
yeti-beat_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/beat.py", line 109, in run
yeti-beat_1       |     return beat().run()
yeti-beat_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/apps/beat.py", line 81, in run
yeti-beat_1       |     self.start_scheduler()
yeti-beat_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/apps/beat.py", line 100, in start_scheduler
yeti-beat_1       |     print(self.banner(service))
yeti-beat_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/apps/beat.py", line 122, in banner
yeti-beat_1       |     c.reset(self.startup_info(service))),
yeti-beat_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/apps/beat.py", line 132, in startup_info
yeti-beat_1       |     scheduler = service.get_scheduler(lazy=True)
yeti-beat_1       |   File "/usr/local/lib/python2.7/dist-packages/celery/beat.py", line 627, in get_scheduler
yeti-beat_1       |     lazy=lazy,
yeti-beat_1       |   File "/opt/yeti/core/scheduling.py", line 61, in __init__
yeti-beat_1       |     self.load_entries()
yeti-beat_1       |   File "/opt/yeti/core/scheduling.py", line 79, in load_entries
yeti-beat_1       |     self.loaded_entries = get_plugins()
yeti-beat_1       |   File "/opt/yeti/core/yeti_plugins.py", line 30, in get_plugins
yeti-beat_1       |     for obj in get_plugin_classes():
yeti-beat_1       |   File "/opt/yeti/core/yeti_plugins.py", line 18, in get_plugin_classes
yeti-beat_1       |     module = importlib.import_module(name)
yeti-beat_1       |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
yeti-beat_1       |     __import__(name)
yeti-beat_1       |   File "/opt/yeti/plugins/import_methods/pdf.py", line 2, in <module>
yeti-beat_1       |     from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter
yeti-beat_1       | ImportError: No module named pdfminer.pdfinterp

**Comment by tomchop** [comment]
I couldn't reproduce this. We did remangle most of the Docker container things, so please take a look at the new changes and let us know if it happens again.
