### ISSUE TITLE
Use code formatters

### ISSUE THREAD

**Issue by ninoseki** [yeti-platform/yeti#574]
How about using [black](https://github.com/psf/black), [autoflake](https://github.com/myint/autoflake), [isort](https://github.com/timothycrosley/isort), etc with [pre-commit](https://github.com/pre-commit/pre-commit)?
I think it will improve the basic quality of the YETI's codebase.

**Comment by tomchop** [comment]
You are totally right, it really deserves a good pass of linter and formatter. We wanted to finish off the python3 migration before we tackle this.

**Comment by sebdraven** [comment]
Now we use black to format the code, and it was integrated in check github
