### ISSUE TITLE
After creating a template, it does not show up in exports  (page reload needed)

### ISSUE THREAD

**Issue by gamelinux** [yeti-platform/yeti#58]
### Description
After creating a template, it does not show up in Exports tab in the drop down menu for templates in New export. Reloading the page populates the drop down menu.

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 0ece661ab7b37c7f95a63302a28cba19051b8adf
| OS version       | Ubuntu 16.04.2
| Browser          | Firefox 52.0.2

### Steps to Reproduce
1. Add new template (/dataflows#export-templates)
2. Click on the Export tab
3. Make a new export. The new template is missing.

#### Expected behavior
New template should be there.

#### Actual behavior
New template is not there.

**Comment by gaelmuller** [comment]
Agree that this is misleading, we need to fix this.
