### ISSUE TITLE
Attempting to edit observable returns 500 internal server error

### ISSUE THREAD

**Issue by theotheryuri** [yeti-platform/yeti#589]
### Description
Attempting to edit an observable returns an Internal Server error.

### Environment
OS Version:           Ubuntu 20.04 LTS
Git commit:          0f919f8
Browser:               Firefox 76.0.1 (64 bit) and Chrome 81.0.4044.138  (64 bit)
Mongo version:   3.6.8

Note this is a new/fresh install. 

### Steps to Reproduce
1. Browse to the Search and Add page
1. Add an observable (type doesn't seem to matter) and tag it to an existing actor entity
1. Click the 'Value' hyperlink to go to the observable
1. Click the "Edit" button.  Receive an Internal Server Error page.

##### Browser
I've grabbed the network headers from via Chrome's Developer Tools network tab:

Request URL: http://localhost:5000/observable/edit/5ec891335700301fdb7f58b5
Request Method: GET
Status Code: 500 INTERNAL SERVER ERROR
Remote Address: 127.0.0.1:5000
Referrer Policy: no-referrer-when-downgrade

##### Logs
    yeti-test uwsgi[984]: INFO:user_management:Default user logged in : yeti
    yeti-test uwsgi[984]: ERROR:app:Exception on /observable/edit/5ec891335700301fdb7f58b5 [GET]
    yeti-test uwsgi[984]: Traceback (most recent call last): 
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2446, in wsgi_app 
    yeti-test uwsgi[984]:     response = self.full_dispatch_request()
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1951, in full_dispatch_request
    yeti-test uwsgi[984]:     rv = self.handle_user_exception(e)
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1820, in handle_user_exception
    yeti-test uwsgi[984]:     reraise(exc_type, exc_value, tb)
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    yeti-test uwsgi[984]:     raise value 
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    yeti-test uwsgi[984]:     rv = self.dispatch_request()
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    yeti-test uwsgi[984]:     return self.view_functions[rule.endpoint](**req.view_args)
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/flask_classy.py", line 200, in proxy
    yeti-test uwsgi[984]:     response = view(**request.view_args)
    yeti-test uwsgi[984]:   File "./core/web/helpers.py", line 39, in inner
    yeti-test uwsgi[984]:     return f(*args, **kwargs)
    yeti-test uwsgi[984]:   File "./core/web/frontend/generic.py", line 90, in edit 
    yeti-test uwsgi[984]:     return render_template(
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 137, in render_template
    yeti-test uwsgi[984]:     return _render(
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/flask/templating.py", line 120, in _render
    yeti-test uwsgi[984]:     rv = template.render(context)
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 1090, in render
    yeti-test uwsgi[984]:     self.environment.handle_exception()
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/jinja2/environment.py", line 832, in handle_exception
    yeti-test uwsgi[984]:     reraise(*rewrite_traceback_stack(source=source))
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/jinja2/_compat.py", line 28, in reraise
    yeti-test uwsgi[984]:     raise value.with_traceback(tb)
    yeti-test uwsgi[984]:   File "/opt/yeti/core/web/frontend/templates/observable/edit.html", line 2, in top-level template code
    yeti-test uwsgi[984]:     {% import "macros/generic.html" as macros %}
    yeti-test uwsgi[984]:   File "/opt/yeti/core/web/frontend/templates/base.html", line 191, in top-level template code
    yeti-test uwsgi[984]:     {% block main %}
    yeti-test uwsgi[984]:   File "/opt/yeti/core/web/frontend/templates/observable/edit.html", line 44, in block "main"
    yeti-test uwsgi[984]:     {{ macros.render_field(field) }}
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/jinja2/runtime.py", line 679, in _invoke
    yeti-test uwsgi[984]:     rv = self._func(*arguments)
    yeti-test uwsgi[984]:   File "/opt/yeti/core/web/frontend/templates/macros/generic.html", line 78, in template 
    yeti-test uwsgi[984]:     {% set _kwargs = {"class_": "tagfield form-control input-sm", "data-choices": url_for(field.endpoint) }%}
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/wtforms/fields/core.py", line 155, in __call__ 
    yeti-test uwsgi[984]:     return self.meta.render_field(self, kwargs)
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/wtforms/meta.py", line 56, in render_field
    yeti-test uwsgi[984]:     return field.widget(field, **render_kw)
    yeti-test uwsgi[984]:   File "/usr/local/lib/python3.8/dist-packages/wtforms/widgets/core.py", line 181, in __call__ 
    yeti-test uwsgi[984]:     kwargs['value'] = field._value()
    yeti-test uwsgi[984]:   File "./core/database.py", line 21, in _value
    yeti-test uwsgi[984]:     return ','.join([d for d in self.data]) 
    yeti-test uwsgi[984]: TypeError: sequence item 0: expected str instance, ObservableTag found
    yeti-test uwsgi[984]: [pid: 984|app: 0|req: 38/164] 127.0.0.1 () {52 vars in 1142 bytes} [Sat May 23 13:04:12 2020] GET /observable/edit/5ec891335700301fdb7f58b5 => generated 290 bytes in 29 msecs (HTTP/1.1 500) 4 headers in 284 bytes (1 switches on core 0)

**Comment by tomchop** [comment]
Thanks again for the detailed report! It was super useful in quickly locating the bug

**Comment by theotheryuri** [comment]
Again, working wonderfully!  Thanks again for your effort @tomchop.  :)
