### ISSUE TITLE
relating observables to actor

### ISSUE THREAD

**Issue by villain** [yeti-platform/yeti#604]
running the latest version of yeti; if i tag observables with a tag, before relating that tag to the actor (so the tag exists before its associated to an actor), the observables do not show up in the $ACTOR - > Observables list

editing the observable after the actor has been associated with the tag, making no changes and clicking save shows the actor in the 'Related entities' section

**Comment by sebdraven** [comment]
Yep, it's normal. The link between observables and entities is made at the insert of the observable.
