### ISSUE TITLE
Suggestion: Official docker image on DockerHub

### ISSUE THREAD

**Issue by DannyBen** [yeti-platform/yeti#606]
I believe people would benefit from an official docker image on DockerHub. This way, users who want to use the docker compose, do not need to build the image or clone the repository.

If there is already one, then the docker instructions and docker-compose should be changed to reflect it.

**Comment by kale1d0code** [comment]
I agree. I can already see I might have some problems setting this up on portainer or for someone without shell access.
does anyone have a tarball of the image?

**Comment by kale1d0code** [comment]
oh just noticed this is based on ubuntu so may as well build an alpine version
