### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by ojaschauhan44** [yeti-platform/yeti#609]
After installing with the given command i am getting the statement as server running on tcp/80
but when i goto the address it says internal server error

**Comment by ojaschauhan44** [comment]
The directory '/home/ubuntu/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/ubuntu/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: uwsgi in /usr/local/lib/python3.6/dist-packages
yarn install v1.22.4
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.13s.
useradd: user 'yeti' already exists
mkdir: cannot create directory ‘/var/log/yeti’: File exists
rm: cannot remove '/etc/nginx/sites-enabled/default': No such file or directory
ln: failed to create symbolic link '/etc/nginx/sites-enabled/yeti': File exists
[+] Starting services...
[+] Yeti succesfully installed. Webserver listening on tcp/80

getting this after running the command

but after this when i goto browser i get internal server error

**Comment by sebdraven** [comment]
have you got logs on web service of yeti ?

**Comment by Firesphere** [comment]
Getting the same error, nothing in the logs but the access error:
`10.0.2.2 - - [11/Oct/2020:21:53:03 +0000] "GET / HTTP/1.1" 500 32 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:82.0) Gecko/20100101 Firefox/82.0"`
