### ISSUE TITLE
Add the concept of TLP

### ISSUE THREAD

**Issue by gamelinux** [yeti-platform/yeti#61]
### Description
Reference: https://www.first.org/tlp

This is probably a long shot for a major release in the future, as it would evolve around the concept of groups, users and permissions. I don't know if that though has been build into the core of yeti or has been thought about or if it is even wanted by the project.

1) The yeti-platform might be used by two or more organizations. Having one organization insert information that is TLP:AMBER and can't be shared with the other organizations, there would be a need to implement some sort of access control to enforce that.

2) A user might insert information that is TLP:RED and should not be accessible for others users or groups that dont have permissions to access it (two or more persons might have gotten the same info), and if possible, not for the sysadmins to.

This probably needs a fair amount of thoughts :)

**Comment by gaelmuller** [comment]
I agree this is something that needs to be discussed. This is indeed a long shot, but we would need to have several opinions on what should be done and how.

One important question is knowing on what kind of information the TLP needs to be applied ? I would argue that the TLP does not apply on the observable itself but on the description, contexts, tags, links, etc...
