### ISSUE TITLE
404 error on FeodoTrackerBinaries feed

### ISSUE THREAD

**Issue by dumprop** [yeti-platform/yeti#619]
### Description
404 error on FeodoTrackerBinaries feed

### Steps to Reproduce
go to FeodoTrackerBinaries - https://feodotracker.abuse.ch/downloads/malware_hashes.csv

#### Expected behavior
feed data

#### Actual behavior
404 error
<img width="558" alt="image" src="https://user-images.githubusercontent.com/34004367/98003389-c1c96780-1dff-11eb-82fb-1a27a13d3d59.png">

**Comment by sebdraven** [comment]
this feed has been removed by abuse.ch and remove here https://github.com/yeti-platform/yeti/commit/45d87816d1d993d8abad968f80eca5830fc0e353
