### ISSUE TITLE
API example

### ISSUE THREAD

**Issue by 4n6analist** [yeti-platform/yeti#62]
### Description
While testing API, it is unclear what params should be such as 
id (ObjectID) – Element ID

This works:
http://10.9.9.144/api/tag

This doesn't:
http://10.9.9.144/api/tag?id=crimeware

I have looked through the docs and it isn't clear what the params represent.  If this is common knowledge then a pointer to the information would be helpful.

**Comment by gaelmuller** [comment]
Could you please detail what you are trying to achieve so that I can provide you with the best answer ? What kind of results are you expecting ?

You can request information about a single tag this way:

```
http -j 'http://localhost:5000/api/tag/590afb9b53f2991a407fa5c0'
HTTP/1.0 200 OK
Content-Length: 220
Content-Type: application/json
Date: Thu, 04 May 2017 10:11:07 GMT
Server: Werkzeug/0.12.1 Python/2.7.11

{
    "count": 50,
    "created": "2017-05-04T09:59:55.158000",
    "default_expiration": 7776000.0,
    "default_expiration_str": "90 days, 0:00:00",
    "id": "590afb9b53f2991a407fa5c0",
    "name": "crimeware",
    "produces": [],
    "replaces": []
}
```

I don't think you can get this information by name currently.

**Comment by gaelmuller** [comment]
Closing this issue since there was no answer to last comment. Do not hesitate to reopen if needed.
