### ISSUE TITLE
404 error on HostsFile feeds

### ISSUE THREAD

**Issue by dumprop** [yeti-platform/yeti#620]
### Description
404 error on HostsFile feeds (HostsFileEMD, HostsFileEXP, HostsFileFSA, HostsFilePSH)
hosts-file.net redirects to malwarebytes.com

### Steps to Reproduce
go to any HostsFile feed (ie https://hosts-file.net/emd.txt )

#### Expected behavior
feed data

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]
<img width="348" alt="image" src="https://user-images.githubusercontent.com/34004367/98003699-17057900-1e00-11eb-89c8-67387f03c86f.png">

**Comment by fr33tux** [comment]
As far as I know, this feed hasn't been maintained for more than a year, so I think it's fine to discard it completely.

**Comment by dumprop** [comment]
> As far as I know, this feed hasn't been maintained for more than a year, so I think it's fine to discard it completely.

I think it too

**Comment by sebdraven** [comment]
It's fixed here https://github.com/yeti-platform/yeti/commit/6c67a91c197cdec68796dfd899a524e6fd1dd47d
