### ISSUE TITLE
Trouble with onion domains in out of the box installation

### ISSUE THREAD

**Issue by dumprop** [yeti-platform/yeti#627]
BenkowTracker contains onion domains, which cant be added to yeti
![image](https://user-images.githubusercontent.com/34004367/98508059-d8dcdf00-226f-11eb-8fe7-3593825334ef.png)
I found this issue on #558, but I still have this problem (installed from repo yeti 1.5.2, not docker), so documentation for a non-docker installation needs to be updated for that

**Comment by sebdraven** [comment]
if you launch,  tldextract --update have you got the issue yet ?

**Comment by dumprop** [comment]
Currently I can't check that, but I think that no
It's more for documentation update tip, as I remember
