### ISSUE TITLE
EXPORTING AND IMPORTING ISSUE 

### ISSUE THREAD

**Issue by hemanthnani11** [yeti-platform/yeti#630]
Before opening an issue, please make do a quick search through the current issues
and the mailing list (https://groups.google.com/forum/#!forum/yeti-users) to see
if it hasn't been answered already.

### Description
ARTER IMPORTING THE FUR CACHE IN NEW FILE 
GROOM IS NOT MOVING WITH THE MESH 

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log | head -n1` to find out
| OS version       | ,Windows 10
| Browser          | Chrome 56.0.2924.87

### Steps to Reproduce
1. git clone the repo
1. cd yeti
1. pip install -r
1. observe stacktrace

#### Expected behavior
[How are you expecting the application to behave?]

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]

**Comment by sebdraven** [comment]
have you got some logs ?

**Comment by dumprop** [comment]
More info, plz
