### ISSUE TITLE
Webserver displays plain text 

### ISSUE THREAD

**Issue by mfiedler144** [yeti-platform/yeti#637]
### Description
After installation, I start the webserver and it shows the website in plain text only. I tried reinstalling and using different browser without any pop-up blocker etc. 

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | commit c6bd7246c5472c02112564af2e294b9b0a9d12a9
| OS version       | Ubuntu 18.04
| Browser          | Version 87.0.4280.141 (Official Build) (64-bit)

### Steps to Reproduce
1. install yeti (steps in documentation)
2. cd yeti
3. start the webserver ./yeti.py webserver
4. go to http://0.0.0.0:5000/

#### Expected behavior
Connection to Yeti webserver

#### Actual behavior
Connection to Yeti webserver, but it displays in plain text. 

![Screenshot from 2021-01-08 11-21-43](https://user-images.githubusercontent.com/45007380/104004303-e0533280-51a3-11eb-9099-e90e24f6775c.png)
![Screenshot from 2021-01-08 11-21-51](https://user-images.githubusercontent.com/45007380/104004307-e1845f80-51a3-11eb-9a71-5187290c74b6.png)

**Comment by mfiedler144** [comment]
I forgot to add that I followed the tutorial to the point starting the webserver and I did not bootstrap or anything. Just the developer environment.

**Comment by dumprop** [comment]
Looks like you skipped yarn installation
You should also enter smthg like that:
$ curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
$ echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
$ sudo apt-get update && sudo apt-get install yarn
$ [sudo] pip install -r requirements.txt
$ yarn install

**Comment by mfiedler144** [comment]
This fixed it! Thank you a lot. I really appreciate it.
