### ISSUE TITLE
Yeti Config after Installation

### ISSUE THREAD

**Issue by jan4401** [yeti-platform/yeti#640]
Hi guys,

thanks for this great project.
I have got running Yeti on Ubuntu 18.04, now I would like to make some changes to the configuration.

Unfortunately I didn't find information about the location of the config file in the documentation.
I assume the path is /opt/yeti/yeti.conf, so i copied /opt/yeti/yeti.conf.sample to yeti.conf in the same location.
Afterwards I added the MISP Feed configuration to the config file and restarted all Yeti services.
When I go to the webinterface - > settings -> dataflows -> feeds -> Misp feed , the link to the misp instance still points to the IP address of yeti.

It would be great to have some documentation on how to make config changes.

Best Regards

**Comment by sebdraven** [comment]
Hi,

you have to restart web service, to load the configuration and restart celery feeds services after. 

And you can check if the data are downloaded from MISP.

**Comment by jan4401** [comment]
Thanks

**Comment by sebdraven** [comment]
It's works ?

**Comment by sebdraven** [comment]
sp, we don't have any answer, we close the issue
