### ISSUE TITLE
Add Threatview.io

### ISSUE THREAD

**Issue by sebdraven** [yeti-platform/yeti#650]
https://threatview.io/

**Comment by Malwar3Ninja** [comment]
Hi @sebdraven Thank you. Machine readable format is also available, just incase you want it. https[://]threatview.io/Downloads/High-Confidence-CobaltstrikeC2_IP_feed.txt

**Comment by sebdraven** [comment]
I prefere this 'https://threatview.io/Downloads/High-Confidence-CobaltStrike-C2%20-Feeds.txt' 

But the csv is not correct, you use a delim in the field


for example there is a comma  in field beacon config, "comecal.com,/ml.js,rexagi.com,/ml.js "

you can change the format of your feed ? on json or change the separator for the fields
