### ISSUE TITLE
Deprecated VirusTotal API endpoint 

### ISSUE THREAD

**Issue by plusvic** [yeti-platform/yeti#655]
I've noticed that this project is using the following endpoint:

https://www.virustotal.com/intelligence/hunting/notifications-feed

The endpoint is being used in:
 https://github.com/yeti-platform/yeti/blob/master/plugins/feeds/public/virustotal_hunting.py

But it looks like the project is already prepared for the deprecation and have an alternative:
https://github.com/yeti-platform/yeti/blob/master/plugins/feeds/public/virustotal_apiv3.py

This issue is only a reminder that this endpoint is scheduled to be shutdown in October 1st, 2021.

**Comment by sebdraven** [comment]
Hi ! Thank for the reminder ! We delete this feed the 1st October :)

**Comment by dumprop** [comment]
Resolved in #734 :)
