### ISSUE TITLE
Invalid feed DynamicDomains/MalwareDomainsDotCom

### ISSUE THREAD

**Issue by dumprop** [yeti-platform/yeti#664]
ERROR updating feed: http://mirror1.malwaredomains.com/files/dynamic_dns.txt returns code: 404

**Comment by sebdraven** [comment]
Yep this feed is deprecated, we delete it for the next version !

**Comment by sebdraven** [comment]
![image](https://user-images.githubusercontent.com/1478484/127004587-c90a7aef-9000-4518-823e-7625c3ecf509.png)

**Comment by dumprop** [comment]
Hm, interesting 
Anyway some feed update in needed then 
Unfortunately I have no subscription 🥲

**Comment by sebdraven** [comment]
I try to have a subcription but the format of the phone is not matched with french number phone

**Comment by dumprop** [comment]
Seems that they only for US customers :(

**Comment by sebdraven** [comment]
Ok doki so I can delete this feed and fixe this issue ?

**Comment by dumprop** [comment]
I think yes, it doesn't matter for me because I have no access to them
