### ISSUE TITLE
Deprecated feed Obtemoslab 

### ISSUE THREAD

**Issue by dumprop** [yeti-platform/yeti#668]
![image](https://user-images.githubusercontent.com/34004367/127124745-1525e884-45f5-458e-99d7-606b824aabeb.png)

**Comment by sebdraven** [comment]
The last data is published in 2019 so you can delete this feed .

**Comment by dumprop** [comment]
https://github.com/yeti-platform/yeti/commit/60b17be7eed52c70fdc9d16b0d5d3c985c7b86aa
Already deleted
