### ISSUE TITLE
Some problem w/ UrlHausPayloads feed

### ISSUE THREAD

**Issue by dumprop** [yeti-platform/yeti#669]
Ubuntu 18.04, yeti 1.7.0

#### Actual behavior
![image](https://user-images.githubusercontent.com/34004367/127127228-1eec29d8-3064-44e9-9daa-e5f9003d63e8.png)

**Comment by sebdraven** [comment]
Have you more logs ? In my instance, this feed is disabled

**Comment by dumprop** [comment]
![image](https://user-images.githubusercontent.com/34004367/127132723-c0ea95f2-4616-41e5-9429-84bfab68e762.png)
I will try w/ more RAM (currently I have 4gb)

**Comment by sebdraven** [comment]
Ok I have to fixe this. I have to stream unzip csv. Here I try to unzip the full file in RAM and it doesn't work

**Comment by sebdraven** [comment]
the unarchived file csv is 2 GB. So Write on disk and read it, it seem too late. So we're going on like that and add a Warning on the web UI if users wants to activate it

**Comment by dumprop** [comment]
OK
But I think its not such problem because is enough to update the feed only once per day
