### ISSUE TITLE
virusign deprecation

### ISSUE THREAD

**Issue by dumprop** [yeti-platform/yeti#671]
![image](https://user-images.githubusercontent.com/34004367/127133462-a2ee9b9b-14ae-44fe-a4b0-e3b130514651.png)
![image](https://user-images.githubusercontent.com/34004367/127133484-0fa1bbd8-cace-467a-a9b4-737b0d440978.png)

**Comment by sebdraven** [comment]
I delete it in the 1.8.0 branches !
