### ISSUE TITLE
Auth is broken when running web server with uwsgi

### ISSUE THREAD

**Issue by mbonino** [yeti-platform/yeti#676]
Before opening an issue, please make do a quick search through the current issues
and the mailing list (https://groups.google.com/forum/#!forum/yeti-users) to see
if it hasn't been answered already.

### Description

I'm testing release 1.8.0 in Docker before upgrading a production instance. 
Running the webserver with ``uwsgi`` is paramount. 

Everything seems to be working fine when the default user ``yeti`` is the only user. After creating another admin user the UI is completely useless.

Login fails most of the time. When login finally succeed, clicking on the menus brings you back to the login page.

Maybe unrelated, all API calls from the UI are refused with ``401 Unauthorized``.   Screenshots below.

<img width="1346" alt="Screenshot 2021-08-06 at 10 00 41" src="https://user-images.githubusercontent.com/42541934/128484553-57733631-e012-4584-90b4-f07b5f123fb2.png">
<img width="1507" alt="Screenshot 2021-08-06 at 09 58 40" src="https://user-images.githubusercontent.com/42541934/128484755-0c8acbda-09c7-4c22-98a1-07bd24fc0956.png">
<img width="923" alt="Screenshot 2021-08-06 at 09 58 55" src="https://user-images.githubusercontent.com/42541934/128484621-9ddc5da5-9355-41ab-80ba-c0845637ef30.png">
<img width="912" alt="Screenshot 2021-08-06 at 10 03 32" src="https://user-images.githubusercontent.com/42541934/128484641-9fe7c308-9322-438e-843f-9106162fd90c.png">
### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | `e0b37d21e6673a4ec9467710f7384ac0e8a26f5a`
| OS version       | Docker image based on `ubuntu:20.04`
| Browser          | Chrome 92.0.4515.107, Safari 14.1.2 (16611.3.10.1.3)

### Steps to Reproduce
1. git clone --branch 1.8.0 https://github.com/yeti-platform/yeti.git
1. cd yeti
1. docker-compose -p yeti -f extras/docker/dev/docker-compose.yaml run -p 8080:8080 yeti /docker-entrypoint.sh uwsgi-http
1. open http://localhost:8080/
1. create an admin user
1. login as the new user
1. click on the menus
1. check the HTTP request and response codes. You should see some `401 Unauthorized` before the Yeti kicks you out.
2. go back to 6

#### Expected behavior

Users other than the default one should be able to use the UI.
The session cookie should authorize API calls.

#### Actual behavior

Login fails often. When finally in, navigating the menus brings you back to the login page.
API calls from the UI always fail.

**Comment by sebdraven** [comment]
It's very strange because we don't modify the process of auth. And in my instance on docker, I don't have this issue.  Can you test with an another

**Comment by mbonino** [comment]
I believe the issue is cause by [this assignement](https://github.com/yeti-platform/yeti/blob/fcd3ee3d3d064df772d0392c20c22aad2bc4c8e6/core/web/webapp.py#L21).

I changed it to:
`webapp.secret_key = b'A_fixed_pregenerated_random_value'`
and I don't have login issues anymore.
