### ISSUE TITLE
Feature Request: Support multiple hash values linked for a single Observable 

### ISSUE THREAD

**Issue by alexander-hanel** [yeti-platform/yeti#69]
### Description

When adding Observables, only a single hash type (MD5, SHA1, SHA256, etc.) value can be added for a single entry. For example the SHA1 hash of `f2260f801c37118b7f9945628d414d09cd1f7c8d` is the the first entry of observable values in the following table.  

```
Value	Tags	Context	Creation date
f2260f801c37118b7f9945628d414d09cd1f7c8d         2017-05-03 16:08
47d2c4b0fba7b9cb5093ad31b5269349bf2ebcaa       2017-05-03 16:08
```
This value could also have a hash of MD5, SHA256, etc.  If the user was searching for a MD5 hash, they will need to retrieve the SHA1 hash and then search for the file. Since different vendors use different hashes in their reports, it would be useful to add the ability so observable hash values can have multiple hash values linked to a single observable value.  This would make searching for a specific hash (no matter the hashing algorithm) much easier. The current option is to have multiple hashes for a single file which can add a lot of observable values.

**Comment by gaelmuller** [comment]
I agree that this makes more sense to have a single "File" observable which could contain different fields for hashes and / or even the file contents.

I think this requires some important changes though, so I am not sure when we would be able to get there.
