### ISSUE TITLE
Add more information in documentation / scripts / installation

### ISSUE THREAD

**Issue by dumprop** [yeti-platform/yeti#690]
Doc needs some style fixes
![image](https://user-images.githubusercontent.com/34004367/130029662-a93c92f3-d7e8-4ad8-b2c5-927b886dbfba.png)
New OS support (currently seems that this script works correctly on my ubuntu 18.04, but 20.04 - ?)
![image](https://user-images.githubusercontent.com/34004367/130029841-81356cb1-2f98-4f04-86e0-f938eae60d2c.png)
4 years ago?
![image](https://user-images.githubusercontent.com/34004367/130398222-6488569a-6fa3-4a5f-a6fe-86f3de77afc9.png)
yeti.py fails without arguments, probably help information would be more useful
![image](https://user-images.githubusercontent.com/34004367/130030418-0969eac5-771a-45ed-bdd3-93759809b5aa.png)
Also possible features:
MacOS/[Yunohost](https://yunohost.org/#/)/[caprover](https://caprover.com/) installation?

**Comment by sebdraven** [comment]
Now, we'll support only docker install I think. It's more simple
