### ISSUE TITLE
Feodo_tracker Trace - KeyError: 'E'

### ISSUE THREAD

**Issue by tk-hendrik** [yeti-platform/yeti#72]
### Description
[Please provide a description of the issue encountered]

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | d02ebef34ec9100a0fd34a07db1ee7df58cecd0c
| OS version       | Ubuntu 16.04

### Steps to Reproduce
1. git clone the repo
1. cd yeti
1. pip install -r
1. observe stacktrace 

#### Expected behavior
Successfully updating the feed

#### Actual behavior
```
[2017-05-04 14:19:41,169: ERROR/PoolWorker-2] Traceback (most recent call last):
  File "/data/yeti/core/feed.py", line 35, in update_feed
    f.update()
  File "/data/yeti/plugins/feeds/public/feodo_tracker.py", line 31, in update
    self.analyze(dict)
  File "/data/yeti/plugins/feeds/public/feodo_tracker.py", line 45, in analyze
    context['description'] = FeodoTracker.descriptions[g['version']]
KeyError: 'E'
```

Mai 04 14:19:41 emsrvlnx6685 celery[967]: [2017-05-04 14:19:41,169: ERROR/PoolWorker-2] Traceback (most recent call last):
Mai 04 14:19:41 emsrvlnx6685 celery[967]:   File "/data/yeti/core/feed.py", line 35, in update_feed
Mai 04 14:19:41 emsrvlnx6685 celery[967]:     f.update()
Mai 04 14:19:41 emsrvlnx6685 celery[967]:   File "/data/yeti/plugins/feeds/public/feodo_tracker.py", line 31, in update
Mai 04 14:19:41 emsrvlnx6685 celery[967]:     self.analyze(dict)
Mai 04 14:19:41 emsrvlnx6685 celery[967]:   File "/data/yeti/plugins/feeds/public/feodo_tracker.py", line 45, in analyze
Mai 04 14:19:41 emsrvlnx6685 celery[967]:     context['description'] = FeodoTracker.descriptions[g['version']]
Mai 04 14:19:41 emsrvlnx6685 celery[967]: KeyError: 'E'

**Comment by gaelmuller** [comment]
Fixed in https://github.com/yeti-platform/yeti/commit/ae134b5ecfbbf6c44ecf6a25dbe0844660f1b8d8
