### ISSUE TITLE
Abandoned library flask-classy

### ISSUE THREAD

**Issue by dumprop** [yeti-platform/yeti#726]
This library was last updated in 2014 ( https://github.com/apiguy/flask-classy ). 
Due to changes in the internal api of the Werkzeug, it does not allow the Yeti to start now.

At the moment, there is a fork of it: https://github.com/teracyhq/flask-classful

Also there will soon be support for the latest version of flask/Werkzeug
https://github.com/teracyhq/flask-classful/issues/144

After that, I think it's worth switching to it

**Comment by tomchop** [comment]
Yeah, this is a pain. Also for TBB, I considered migrating the whole thing to FastAPI: https://fastapi.tiangolo.com/
