### ISSUE TITLE
Install new modules after update

### ISSUE THREAD

**Issue by cvdsouza** [yeti-platform/yeti#73]
### Description
Enabling Analytics requiring API keys with Yeti 

Hi ,
I've recently installed YETI and am playing with it. 
Currently I'm facing two issues : 

-> Not sure where to input the API keys for PT, DT, Shodan
-> After performing a git pull to pulldown shodan , and restarting YETI, the analytics section is not displaying the updated Shodan One Shot. 

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | ae134b5ecfbbf6c44ecf6a25dbe0844660f1b8d8
| OS version       | Ubuntu 16.04
| Browser          | Chrome 57.0.2987.133

### Steps to Reproduce
1. cd /opt/yeti
1. git pull
1. systemctl restart yeti_analytics.service
1. service nginx restart

#### Expected behavior
New Analytics ( i.e. Shodan) should appear. 

#### Actual behavior
Analytics screen is not refreshed with new data.

**Comment by tk-hendrik** [comment]
Hi,
did you remember to re-run `pip install -r requirements` or alternative `pip install shodan`.

**Comment by gaelmuller** [comment]
When updating, you have to make sure you install new requirements using `pip install -r requirements.txt`.

New modules (feeds, analytics, etc.) will only be taken into account after a restart of the Scheduler (`sudo systemctl restart yeti_beat` in production).

I will keep this issue open because we need to find a better way or at least improve documentation to make that clear.

**Comment by cvdsouza** [comment]
Hi, 
Thank you very much. 
Restarted yeti_beat and nginx and shodan shows up now. 

Could you also advice on the second point of my query : 
Adding of the API keys for the One-Shot analytics, could you please direct me to where I would place these API keys ? 

I tried placing them in the code : 
 settings = {
        "shodan_api_key": {
            "name": "XXXXXXXXXXXXXXXXXX",
            "description": "API Key provided by Shodan.io."
        }
    }
But I don't think this was correct, as the UI still shows (This plugin requires settings that are not yet defined) : 

![image](https://cloud.githubusercontent.com/assets/1090828/25742779/103bd7fe-315f-11e7-827b-5dc6235d51c6.png)

**Comment by gaelmuller** [comment]
You can define these settings on your profile page (click on "profile" in the top right corner).

**Comment by cvdsouza** [comment]
Oh yes.. My apologies, didn't notice it earlier. Thank you very much.
