### ISSUE TITLE
Question: Pyeti as separate project?

### ISSUE THREAD

**Issue by tk-hendrik** [yeti-platform/yeti#74]
Hi,

I just saw some code useful for clients using the yeti API as a python module. Great and thumbs up.

Are there any thoughts to separate this code out to an own project?

Benefits I would see:

- Possibility to distribute/install it via pip
- Be able to install the module to different systems without a 'fat' yeti installation
- May be some nifty future command line tools?
- or just rule the whole world ^^

Regards,
Hendrik

**Comment by gaelmuller** [comment]
I agree. We need to give it its own repository under yeti-platform and a setup.py / Pypi package.

**Comment by tk-hendrik** [comment]
Just an offer - create an empty repository which can be forked under yeti-platform and the PRs will come :)

**Comment by gaelmuller** [comment]
There it is: https://github.com/yeti-platform/pyeti 😄

**Comment by tk-hendrik** [comment]
First steps were taken, feel free to adjust the things like you want or need.

**Comment by tomchop** [comment]
Thanks for your efforts! This is done in 6c3ceb64e1771ee0e6bf6742e5c2cbdf4481fc53
