### ISSUE TITLE
Dependencies missing 

### ISSUE THREAD

**Issue by g33kroid** [yeti-platform/yeti#748]
### Description
Running `pip3 install -r requirements.txt` can't find all dependencies 

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | afdac8cc5596a4c9b92caea56005781ac697c29c
| OS version       | Ubuntu 18.04
| Browser          | Firefox

#### Expected behavior
No Version found for PowerDNS Python3 

#### Actual behavior
```
Collecting python3-pdns (from -r requirements.txt (line 40))
  Could not find a version that satisfies the requirement python3-pdns (from -r requirements.txt (line 40)) (from versions: )
No matching distribution found for python3-pdns (from -r requirements.txt (line 40))
```

**Comment by mxamusic** [comment]
Even the Docker Image can't run because of missing dependencies. I tried the base OS: `Ubuntu 18.04` and `CentOS 8`

![image](https://user-images.githubusercontent.com/16447622/209452290-393f6bb0-e476-4774-bac8-aadcbb7d3a73.png)

**Comment by dumprop** [comment]
The problem is that the powerdns package requires a python version of at least 3.8
werkzeug is a know issue #731

**Comment by geovanidps** [comment]
dependência python3-pdns foi substituído pelo pip dnssync

**Comment by dumprop** [comment]
> dependência python3-pdns foi substituído pelo pip dnssync

You can just remove python3-pdns from packages, it used only for specific feed
