### ISSUE TITLE
No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by psychomad** [yeti-platform/yeti#754]
Before opening an issue, please make do a quick search through the current issues
and the mailing list (https://groups.google.com/forum/#!forum/yeti-users) to see
if it hasn't been answered already.

### Description
When i try to install from one command (curl etc) i got this
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### Environment
ubuntu 20

| Question         | Answer
|------------------|--------------------
| Git commit       | Type `$ git log | head -n1` to find out
| OS version       | Ubuntu 16.04, Windows 10, macOS 10.12.3
| Browser          | Chrome 56.0.2924.87

### Steps to Reproduce
1. git clone the repo
1. cd yeti
1. pip install -r
1. observe stacktrace

#### Expected behavior
install yeti from single command bash

#### Actual behavior
can't find requirements.txt

**Comment by dumprop** [comment]
Currently there poetry (pyproject.toml) instead of requirements.txt is used...

**Comment by psychomad** [comment]
I see, so need to update the single install script, thanks for the answer!

**Comment by sebdraven** [comment]
A big warning this branch has been refactored. The best way is to use the release versions. A new version is coming
