### ISSUE TITLE
Documentation overhaul

### ISSUE THREAD

**Issue by tomchop** [yeti-platform/yeti#759]

**Comment by TQPS** [comment]
Thanks for the updates.

Looking forward to a revised version of the Ubuntu_bootstrap script.

I don't docker.

**Comment by tomchop** [comment]
Unfortunately, we won't be maintaining a version of the `ubuntu_bootstrap.sh` script. The idea behind using docker is to be able to provide a setup mechanism that works for everyone regardless of which platform they're using, easing the documentation / sysadmin burden on us. 

However, having a look at the Dockerfile and docker-compose scripts should give you a solid enough idea on how to write a bootstrap script that's best suited to your platform (a contribution we'd gladly accept!)

**Comment by TQPS** [comment]
Thanks. I'll have a play with trial and error. 

Our prod version of Yeti has been in play for over 6 years and no matter the method of upgrading with all the recent changes - which also requires Ubuntu upgrade - it breaks. The amount of data in there ... 

I'll look at the Docker script and try a workaround for Ubuntu. If anyone else happens to have successfully upgraded a Prod Ubuntu version, please reach out.

**Comment by tomchop** [comment]
I moved the discussion to #773. I'm a bit concerned that you're unable to confidently upgrade the instance without anything breaking... even more so that future changes will introduce a new database system, and migration will probably be even trickier. 

FWIW, I am happy to spend some hands-on time helping you make sure that your data is fully migrated and to come up with a reliable system to do these upgrades in the future (see #773)
