### ISSUE TITLE
Confusion on graph link

### ISSUE THREAD

**Issue by DigiAngel** [yeti-platform/yeti#76]
### Description
I'm trying to accomplish a linked chain going from top down.

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 27ae09f83b0165c36c78297708b4a2e75c9a2dad
| OS version       | Debian stretch
| Browser          | Chrome 57.0.2987.133 (64-bit)

### Steps to Reproduce
1.  New Malware
2.  Add observables

#### Expected behavior

I'm not sure :)  I'd like to disconnect from the mail entity and allow a chain not all pointing to one entity to have something like a flow 1 -> 2 -> 3 -> and so on.

#### Actual behavior

![2017-05-11 15_16_29-the yeti - yeti](https://cloud.githubusercontent.com/assets/947191/25972372/fd4c89c4-365c-11e7-9e87-e92c03060b6b.jpg)

**Comment by gaelmuller** [comment]
This is actually a debate that we had at some point. Because of tags, all elements are directly linked to the malware.

At the moment, the investigation graph will always display all available links (this is meant to help you) but sometimes I feel this is not the representation that you want. I am interested to have additional feedback on this one: should we be able to select only certain links to be displayed on the graph ?

**Comment by DigiAngel** [comment]
Well...since I opened the ticket imma say yes :D  I love the fact that all elements point to a single malware...and I think given several different campaigns this is absolutely the way to go.  I also think it would be nice to have the ability to show a "chain of events" type view... email->link->zip->javascript->exe->c2 that kind of thing.  Maybe have one more option...a "free form" mode where all elements are available, but we are able to pick and chose which elements are on the graph, and how they relate and link.  So I vote yes :)

**Comment by tomchop** [comment]
Links between nodes can be manually created in the investigation interface. We still need to implement a way to delete them. This is being tracked in #55.

**Comment by axpatito** [comment]
Hi @tomchop both this and #55 are closed. This is not solved yet. Can we reopen, pls?

**Comment by tomchop** [comment]
#55 is still open (you only see the reference to this issue, which is closed)
