### ISSUE TITLE
Docker-compose failing

### ISSUE THREAD

**Issue by DigiAngel** [yeti-platform/yeti#776]
### Description
[Please provide a description of the issue encountered]

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 1.8.5 tarball download
| OS version       | Ubuntu 22
| Browser          | Chrome 56.0.2924.87

### Steps to Reproduce
1. extract the 1.8.5 tarball
1. cd yeti/extras/docker/dev
1. docker-compose up

#### Expected behavior
compile and go

#### Actual behavior
Stuck at:
~~~
[+] Building 2813.0s (11/14)
~~~
no cpu usage...last line is:

~~~
 => ERROR [yeti  7/10] RUN pip3 install -r requirements.txt &&         yarn install &&         mv yeti.conf.sample yeti.conf &&         sed -i '35s/# host = 127.0.0.1/host = mongodb/' yeti.conf &&         sed -i '49s/# host = 127.0.0.1/  112.0s
~~~

**Comment by DigiAngel** [comment]
Closed due to lack of developer interest.

**Comment by sebdraven** [comment]
not a lack of developer interest but lack of time

**Comment by sebdraven** [comment]
Have you got some logs ? because like that it's difficult to debug.

**Comment by sebdraven** [comment]
you add build-essential \
        python3-dev \
        libssl-dev \ 

in part of #Python in the Dockerfile  and the build is ok

don't forget to fixe the version of werzeug

**Comment by DigiAngel** [comment]
Gotcha..thank you.

**Comment by DigiAngel** [comment]
Confirming making the mods to Dockerfile (or...you know...git cloning as per the full instructions :D) worked.  Thank you!
