### ISSUE TITLE
Investigations not visible?

### ISSUE THREAD

**Issue by khalavak** [yeti-platform/yeti#777]
### Description
After installation via docker and accessing the Yeti webpage and logging in, there is no button for the Investigations as can be seen in the documentation. Not sure why and if I'm doing something wrong but according to documentation it should be possible to start investigations?

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | yeti-2.0-Alpha.zip
| OS version       | docker
| Browser          | Chrome Version 114.0.5735.198

### Steps to Reproduce
1. git clone the repo
1. cd yeti/extras/docker/dev
1. docker-compose up -d

#### Expected behavior
Investigations visible in the UI

#### Actual behavior
No Investigations menu visible in the UI

<img width="2200" alt="Screenshot 2023-07-19 at 15 04 50" src="https://github.com/yeti-platform/yeti/assets/2081902/f226c977-b6ed-4222-b8cf-2f483d49090d">

**Comment by sebdraven** [comment]
In the new version we have removal the investigation part https://github.com/yeti-platform/yeti/releases

**Comment by khalavak** [comment]
Ah look at that...was to eager to try newest version...any particular reason for removing the investigation feature?

**Comment by sebdraven** [comment]
yes many bugs and very difficult to maintain this part, we focus on core system, and we have developed maltego transform to a better investigation :)

**Comment by sebdraven** [comment]
yes many bugs and very difficult to maintain this part, we focus on core system and we have developed maltego transform to a better investigation :)
