### ISSUE TITLE
Reanalyzing a node in an investigation does not work

### ISSUE THREAD

**Issue by gamelinux** [yeti-platform/yeti#85]
![latest-screenshot](https://cloud.githubusercontent.com/assets/53898/26763549/00b04afa-4955-11e7-9187-c974c54efd3a.png)
### Description
In an Investigation, graph->Analytics, when I enrich a node, then leave the Investigation and come back to it, I can not enrich the node once more with the Analytics that I have already used. When clicking the node, then "Analytics", the enricher I used is just displaying "Loading ...". Does not help to wait days. Seems that its stuck. I have the same behavior on two yeti installs. Using both Firefox and Chrome produces the same result. I run all in DEBUG, but it yields no hints to things going wrong.

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | commit 241a7d643730b4f79f1e4a01a3ebb0e3559f0cd5
| OS version       | Ubuntu 16.04.2 LTS
| Browser          | Version 58.0.3029.81 (64-bit)

### Steps to Reproduce
1. Assuming you have a working Yeti up and running...
2. Make a new investigation of say an IP
3. Enrich the IP with "PassiveTotal Passive DNS"
4. Add one of the discovered domains to the graph
5. Leave the investigation (Click Observables->Browse)
6. Reenter the investigation you just made (Click Investigations, then Unnamed, then pick the first one, should be it).
7. Click on the IP you earlier enriched. "PassiveTotal Passive DNS" should now just display "Loading ..." and will never finish.

#### Expected behavior
7. Clicking on the IP you earlier enriched should display the "two arrow Run button". That way, if you are revisiting an investigation done last month, you can update from passive DNS sources if there are new data.

#### Actual behavior
I've found, that clicking on different nodes, and coming back to the node I want to rerun the enrichment, might work in the sense that the "two arrow Run button" shows again. But clicking it makes it spin forever... Looking at the logs, the enrichment is done in the background, and browsing "Observables->Browse" might add new Observables to the system etc.

**Comment by gamelinux** [comment]
Running Chrome console, only error displaying, might be related?:

Uncaught TypeError: Cannot read property 'id' of undefined
    at graph.js:682
    at Array.forEach (<anonymous>)
    at Investigation.saveAnalyticsResults (graph.js:679)
    at Object.callback (graph.js:590)
    at fire (jquery.js:3048)
    at Object.fireWith [as resolveWith] (jquery.js:3160)
    at done (jquery.js:8235)
    at XMLHttpRequest.callback (jquery.js:8778)

**Comment by gaelmuller** [comment]
Should be fixed now.
