### ISSUE TITLE
Yeti Feeds MalwareDomainsDotCom Stuck

### ISSUE THREAD

**Issue by JohnSmith94** [yeti-platform/yeti#86]
### Description
My feed MalwareDomainsDotCom seems stuck on updating. All the others have went to ok. I had an issue where multiple got stuck on updating. So i stopped my yeti removed the stuck ones and was planning on adding them back in one by one. Once i Added in the Malwaredomains one it is stuck on updating. If i run a testfeeds it just exits without success message or any errors. Any help or ideas would be greatly appreciated. 

### Environment
Git Commit - commit 0ece661ab7b37c7f95a63302a28cba19051b8adf
OS version - Ubuntu 16.04.2 LTS

#### Expected behavior
Expected testfeeds to return a success and for the Dataflow to show ok message in web gui. 

#### Actual behavior
Dataflow in Webgui stuck on updating. And testfeed doesn't return success just closes out.

**Comment by tomchop** [comment]
Did you find what was causing this? I know MalwareDomains is a very large feed and it can take a while to import them all.
