### ISSUE TITLE
Help Json Feed for MHN

### ISSUE THREAD

**Issue by JohnSmith94** [yeti-platform/yeti#87]
Can anyone help with an Json feed for the MHN api. I tried to look at the feeds and none of them used the json helper. Sorry if this is a simple question still new to all this.

**Comment by tomchop** [comment]
Sure, can you please share the feed source here?

**Comment by JohnSmith94** [comment]
http://52.34.252.176/api/session/?api_key=9f374f684ff14d2ab1e2b7f4658e6d5f&hours_ago=1

there is a sample setup i stood up. Thank you again.

**Comment by DeweyCheetum** [comment]
Could use some assistance with this exact scenario as well.

**Comment by tomchop** [comment]
Something like this should to it:

```
class Test(Feed):

    default_values = {
        "frequency": timedelta(hours=1),
        "name": "Test",
        "source": "http://52.34.252.176/api/session/?api_key=9f374f684ff14d2ab1e2b7f4658e6d5f&hours_ago=200",
        "description": "Nothing to see here",
    }

    def update(self):
        full_dict = self.update_json():
        self.analyze(d)

    def analyze(self, dict):
        # do something with the dict
```

**Comment by JohnSmith94** [comment]
Awesome thanks that worked perfectly.

**Comment by tomchop** [comment]
Closing this as OP has their problem solved. Please reopen if need be.
