### ISSUE TITLE
Feeds stuck in 'updating' state

### ISSUE THREAD

**Issue by WArurrt** [yeti-platform/yeti#88]
### Description
On the Dataflows > Feeds page, there are multiple feeds frozen in an 'updating' status. I'm pretty new to this, so any help would be amazing! Thanks! 

### Environment
| Question         | Answer
|------------------|--------------------
| Git commit       |  d24f60ba8703adb91e7f16271ed8ad1dffd30798
| OS version       | Ubuntu 16.04
| Browser          | Chrome 58.0.3029

### Steps to Reproduce
1. Navigate to Dataflows > Feeds page
2. Scroll through list, see HostsFileFSA, HostsFilePSH, MalwareDomainsDotCom, and RansomwareTracker are in a status of updating with no change. 
3. Hitting feed refresh button does nothing

#### Expected behavior
Feeds to update and complete with a green line. 

#### Actual behavior
Stuck in an updating state. Screenshot: [here](http://imgur.com/f6BagVS)

**Comment by JohnSmith94** [comment]
I have one stuck on updating as well alternatively if I try to run a testfeeds on that one I never get a success. 
`$ python ./testfeeds.py RansomwareTracker
Running RansomwareTracker...
XXXXXXXX:/opt/yeti$ `

**Comment by JohnSmith94** [comment]
I have one stuck in updating status as well. Also appears that the ResolveHostnames analytic is also stuck as "Running" Not sure if these two things are related or not. 

<img width="1397" alt="screen shot 2017-06-12 at 6 18 28 am" src="https://user-images.githubusercontent.com/29146862/27029638-2f325110-4f37-11e7-91dd-eec8b6e5c717.png">

**Comment by tomchop** [comment]
Are they really stuck, or just very slow? (both are a problem, I know) What happens if you just leave them running for a long time?

**Comment by JohnSmith94** [comment]
Unsure of the OP's time but mine has been running for approx. 6 hours and is still in updating. along the same time frame the Analytics has been running. Mine was in OK status prior and I haven't seen no new observables come in from this feed in the past 6 hours.

**Comment by tomchop** [comment]
Thanks. Do you encounter this on the same feeds than the OP? (HostsFileFSA, HostsFilePSH, MalwareDomainsDotCom)

**Comment by JohnSmith94** [comment]
Mine is stuck on only the MalewareDomains. I encountered an error on the HostsFile ones (See below) so i have them toggled off.

ERROR updating feed: HTTPSConnectionPool(host='hosts-file.net', port=443): Max retries exceeded with url: /emd.txt (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f46f2d52f50>: Failed to establish a new connection: [Errno 110] Connection timed out',)).

**Comment by tomchop** [comment]
As the error suggests, looks like this is more a timeout issue when attempting to contact `hosts-file.net`. The feed will automatically retry later so you mostly don't have to worry about those.

As a side note, since some feeds have lots of observables of dubious quality, we're thinking of adding a "confidence" rating to them, and maybe disabling them all by default so that the user can pick those to enable after running Yeti. WDYT?

**Comment by WArurrt** [comment]
Mine are still in an 'Updating' state, but I'm going to wait longer and see what happens. Had to rebuild my server as it appeared I was out of space. Expecting it to work fine this time, but keep you posted. Thanks for the quick replies all!

**Comment by JohnSmith94** [comment]
I think having them diabled by default would be great. Especially given as you said some of the dubious quality of some of the feeds.

To the Feeds stuck in updating..Mine has been stuck in updating for over 20 hours still no new observables from that feed (MalwareDomainsDotCom) also the Resolve Hostnames analytic still seems to be stuck on running.

**Comment by WArurrt** [comment]
Looks like my feeds are still stuck - been about 20 hours. Any thoughts?

**Comment by tomchop** [comment]
OK, let's try resetting the feeds an analytics. Kill your worker processes for **feeds** and **analytics** (either through `systemd` or Ctrl+C if you ran them on a shell) and run the following command in your terminal.

Span a mongo shell. From a terminal, type:
```
$ mongo
```
Type in the following commands:
```
use yeti
db.schedule_entry.update({lock: true}, {$set :{lock:false}}, {multi:true})
```

This situation (having "locked" feeds when there are no workers to unlock them once they're done) should not happen unless you killed the workers _while_ they were working on something. Do you recall doing that? (could happen often while testing)

**Comment by JohnSmith94** [comment]
That did the trick for me. Not sure how i managed to lock them in the first place i dont remember killing the workers for anything but all seems right in the world now.

**Comment by tomchop** [comment]
OK. We still need to work on automating the resolution when this happens. Thanks for your feedback!

**Comment by jwroberts** [comment]
Sorry to jump in a bit late but I just noticed this thread.  You may want to consider adding a timeout to your requests.get calls.  Requests has the unfortunate default of blocking forever whenever it gets stuck trying to fetch something. It may be better to give it a liberal timeout and deal with whatever exception gets raises in those cases when it does timeout.

**Comment by soulsf** [comment]
> As the error suggests, looks like this is more a timeout issue when attempting to contact `hosts-file.net`. The feed will automatically retry later so you mostly don't have to worry about those.
> 
> As a side note, since some feeds have lots of observables of dubious quality, we're thinking of adding a "confidence" rating to them, and maybe disabling them all by default so that the user can pick those to enable after running Yeti. WDYT?

A rating systems for feeds/observables would be great ! One could even consider the rating when exporting. Thumbs up for feature.
