### ISSUE TITLE
API Log and Example

### ISSUE THREAD

**Issue by WArurrt** [yeti-platform/yeti#89]
Help Request:

I'm having some issues trying to use the API - receiving 500 error replies. By chance, is there a log in yeti with details on why it failed? Also, is there an example request pyeti request? Filled out this with my key and correct hostname (https://github.com/yeti-platform/pyeti/blob/master/pyeti/api.py), with no luck. 

Thanks again!

**Comment by tomchop** [comment]
We cover the API in our documentation, but given all the questions we have about it it seems it's not that clear. Check out #62 for a short example. If you started Yeti with systemd, you can check out the logs with `systemctl status yeti_uwsgi.service` or `journalctl -xe`. For all debuging purposes we recommend running yeti from the command line `./yeti.py webserver`. This will throw logs to stdout.

**Note: We changed the way Yeti is launched in the latest commits so make sure you update your systemd scripts accordingly.**

We plan to have some example usages of `pyeti` (this will come pretty soon) as well as including example HTTP requests in the API documentation for more clarity.

**Comment by tomchop** [comment]
We have udpated the pyeti repo with additional functionalities and some examples. Feel free to check it out and reopen this should you run into trouble!
