### ISSUE TITLE
Docker compose not working

### ISSUE THREAD

**Issue by muhammadnaumanmustafa** [yeti-platform/yeti#896]
Before opening an issue, please make do a quick search through the current issues.

### Description
[Please provide a description of the issue encountered]

### Environment

| Question                  | Answer
|---------------------------|--------------------
| Yeti release              |
| Yeti-frontend release     |
| OS version                | Ubuntu 22.04, Windows 11, macOS 13.6.2
| Browser                   | Chrome 119.0.6045.123

### Steps to Reproduce

[Please explain how to reproduce the issue.]

#### Expected behavior
[How are you expecting the application to behave?]

#### Actual behavior
[How is the application behaving? (include any stacktraces, logs, screenshots, etc.)]

**Comment by tomchop** [comment]
No issue description, closing

**Comment by muhammadnaumanmustafa** [comment]
Hello, upon running the docker-compose.yml file only two containers named "yeti-arangodb-1" and "yeti-redis-1" are created only as opposed to the 6 containers mentioned in the readme file. Thus the application cannot be accessed on port 5000

**Comment by tomchop** [comment]
Can you tell us which instructions you're following? Which platform you're on? What commands you're using to reproduce this?

**Comment by muhammadnaumanmustafa** [comment]
> Can you tell us which instructions you're following? Which platform you're on? What commands you're using to reproduce this?

I am following the https://github.com/yeti-platform/yeti/blob/main/extras/docker/README.md instructions to clone and the git repository and using "docker compose -p yeti -f extras/docker/dev/docker-compose.yaml up -d" command to start up yeti on a linux/ubuntu platform.

**Comment by tomchop** [comment]
Those instructions were outdated, sorry (and thanks for the catch!) please head to the official docs at https://yeti-platform.io/docs/getting-started/ to get a Yeti instance up and running.
