### ISSUE TITLE
Add Yara "hash" module

### ISSUE THREAD

**Issue by ghost** [yeti-platform/yeti#90]
Possible to add compatibility for the yara hash module? Currently adding any rules with "import hash" defined will return a "General Error - Yara compilation error: line 2: unknown module "hash""

Thank you!

**Comment by tomchop** [comment]
This mostly sounds like a python-yara limitation. Can you run `$ pip freeze` and `$ yara -v`and paste the output here?

**Comment by WArurrt** [comment]
user@yeti:~$ pip freeze
Babel==2.4.0
Cheetah==2.4.4
Flask==0.12.2
Flask-Classy==0.6.10
Flask-Login==0.4.0
Flask-Negotiation==0.1.9
Flask-WTF==0.14.2
Jinja2==2.9.6
Landscape-Client==14.12
MarkupSafe==1.0
PAM==0.4.2
PyYAML==3.10
Pygments==2.2.0
Sphinx==1.6.2
Twisted-Core==13.2.0
Twisted-Names==13.2.0
Twisted-Web==13.2.0
WTForms==2.1
Werkzeug==0.12.2
alabaster==0.7.10
amqp==2.1.4
apt-xapian-index==0.45
argparse==1.2.1
billiard==3.5.0.2
blinker==1.4
celery==4.0.2
certifi==2017.4.17
chardet==3.0.4
click==6.7
click-plugins==1.0.3
cloud-init==0.7.5
colorama==0.2.5
configobj==4.7.2
dnspython==1.15.0
docutils==0.13.1
flask-mongoengine==0.9.3
geoip2==2.5.0
html5lib==0.999
idna==2.5
imagesize==0.7.1
iotop==0.6
ipaddr==2.1.11
ipaddress==1.0.18
iptools==0.6.1
ipwhois==0.15.1
itsdangerous==0.24
jsonpatch==1.3
jsonpointer==1.0
kombu==4.0.2
lxml==3.8.0
maxminddb==1.3.0
mongoengine==0.13.0
oauth==1.0.1
prettytable==0.7.2
psutil==5.2.2
pyOpenSSL==0.13
pycrypto==2.6.1
pycurl==7.19.3
pymongo==3.4.0
pyserial==2.6
python-apt==0.9.3.5ubuntu2
python-debian==0.1.21-nmu2ubuntu2
python-magic==0.4.13
pythonwhois==2.4.3
pytz==2017.2
redis==2.10.5
requests==2.17.3
requests-file==1.4.2
shodan==1.6.9
simplejson==3.10.0
six==1.5.2
snowballstemmer==1.2.1
sphinx-rtd-theme==0.2.4
sphinxcontrib-httpdomain==1.5.0
sphinxcontrib-websupport==1.0.1
ssh-import-id==3.21
tldextract==2.1.0
typing==3.6.1
urllib3==1.21.1
urlnorm==1.1.4
vine==1.1.3
virtualenv==1.11.4
wheel==0.24.0
wsgiref==0.1.2
yara-python==3.6.1
zope.interface==4.0.5

user@yeti:~$ yara -v
The program 'yara' is currently not installed. To run 'yara' please ask your administrator to install the package 'yara'

**Comment by doomedraven** [comment]
for that you need to compile it with hash support

```
    echo '[+] Installing Yara'
    apt-get install libtool libjansson-dev libmagic1 libmagic-dev -y
    cd /tmp/ || return
    yara_info=$(curl -s https://api.github.com/repos/VirusTotal/yara/releases/latest)
    yara_version=$(echo $yara_info |jq .tag_name|sed "s/\"//g")
    yara_repo_url=$(echo $yara_info | jq ".zipball_url" | sed "s/\"//g")
    wget -q $yara_repo_url
    unzip $yara_version
    #wget "https://github.com/VirusTotal/yara/archive/v$yara_version.zip" && unzip "v$yara_version.zip"
    directory=`ls | grep "VirusTotal-yara-*"`
    cd $directory || return
    ./bootstrap.sh
    ./configure --enable-cuckoo --enable-magic --enable-dotnet --enable-profiling
    make -j"$(getconf _NPROCESSORS_ONLN)"
    yara_version =
    checkinstall -D --pkgname="yara-$yara_version" --pkgversion="$yara_version|cut -c 2-" --default
    ldconfig
    cd ..
    rm "VirusTotal-yara-*.zip"
    git clone --recursive https://github.com/VirusTotal/yara-python
    cd yara-python || return
    python setup.py build
    python setup.py install
```
