### ISSUE TITLE
Bulk delete Observables

### ISSUE THREAD

**Issue by luckyb56** [yeti-platform/yeti#91]
### Bulk delete observable
If one associates all the observable with any entity (e.g Campaign), and the entity is deleted, how can one bulk delete all the observables?

**Comment by gaelmuller** [comment]
Observables cannot be deleted (one by one or in bulk) at this point. I am not sure this is something that we would want.

Why do you want to delete these observables ?

If you want your observables to disappear from a feed for example, you could go to the tags page (Settings > Tags) and delete the tag associated with this campaign.

**Comment by luckyb56** [comment]
Deleting it one by one is possible as I was able to do by:
DELETE /api/observable/<observable-id>

I had bulk added, then realised I wanted to add in three different parts with different tags. Going to each and editing one by one for tags would be difficult.

**Comment by tomchop** [comment]
This was added in the latest pyeti version. It's still not possible to do it by bulk, but pyeti has a function you can now call.
