### ISSUE TITLE
Failed to install yeti

### ISSUE THREAD

**Issue by tomgross** [yeti-platform/yeti#924]
Before opening an issue, please make do a quick search through the current issues.

### Description
The installation of yeti fails. 

### Environment

| Question                  | Answer
|---------------------------|--------------------
| Yeti release              | master
| Yeti-frontend release     | ?
| OS version                | macOS 14.1
| Browser                   | -
| Poetry                   | 1.7.1

 

### Steps to Reproduce

Try to install yeti (like it is done in the Docker yeti-docker recipe. The same error happens on docker build too.)

1. Clone yeti repo & create virtual env of python 3.10
2. poetry install --with plugins

#### Expected behavior
Installation works

#### Actual behavior
Installation fails with the following warnings & errors

```bash
% bin/poetry install --with plugins
Installing dependencies from lock file
Warning: poetry.lock is not consistent with pyproject.toml. You may be getting improper dependencies. Run `poetry lock [--no-update]` to fix it.
...
The current project could not be installed: No file/folder found for package yeti
If you do not want to install the current project use --no-root
```

#### Analysis

I asume the that the layout of the package does no longer work with the current version(s) of poetry. As the error message and the documentation indicates there needs to be a folder called `yeti`. See https://python-poetry.org/docs/cli/#new

**Comment by tomchop** [comment]
> The same error happens on docker build too.

Does it though? It builds correctly in the GitHub action: https://github.com/yeti-platform/yeti/actions/runs/7061723034/job/19223997061

I tried running some tests, and indeed I can reproduce your error message... however, it's not an error message but a warning - the libs install just fine and you can still import and launch the webapp. You can bypass this warning by doing `poetry install --no-root` (which I will add to the unittests / dockerfiles too)

If we want to get rid of this error we should essentially rename `core` to `yeti`, which I will try to do, but it might break a lot of things. However, without this, the `scripts` defined in the pyproject.toml file won't be installed.

**Comment by tomchop** [comment]
That's what I meant by the scripts won't be installed. Maybe it's best to remove them for now. You can always call yetictl by doing `poetry run python yetictl/cli.py` (that's how the docker entrypoint calls it)

I opened https://github.com/yeti-platform/yeti/issues/928 to track this. Thanks for bringng it up!
