### ISSUE TITLE
user_account observable

### ISSUE THREAD

**Issue by tomchop** [yeti-platform/yeti#937]
The `user_account` observable would have much more fields than just a `value` (see https://github.com/yeti-platform/yeti/pull/895 for an example). How do we add such an observable? 

Currently the API endpoint accepts tags, value, type. We could have it accept a richer type of observable in an `observable` field:

```
{ observable: {value: blah, attrib1: blah}, type: user_account, tags: [tag1, tag2] }
```

**Comment by udgover** [comment]
This issue is now resolved by https://github.com/yeti-platform/yeti/pull/949. Should we close this issue?

**Comment by tomchop** [comment]
We still need https://github.com/yeti-platform/yeti/pull/957 to be merged
