### ISSUE TITLE
Unable to access webgui after git pull

### ISSUE THREAD

**Issue by JohnSmith94** [yeti-platform/yeti#94]
Did a "git pull" to update yeti. After that I copied backover the systemd scripts and tried to run it appears the server starts right however travesing to the IP just yeilds a "internal server error" . I've copied the screenshots my journalctl -xe output below. The second screen shot shows the attempts to access the webgui in journalctl -xe. 

EDIT: After some digging i'm able to run the service yeti_web* just fine and am able to go to http://localhost:5000 to see the web gui. Upon startup manually uwsgi throws this error. Which leads me to believe its an import problem with webapp.
`unable to load app 0 (mountpoint='') (callable not found or import error)
`

Thanks 

<img width="1003" alt="screen shot 2017-06-14 at 11 21 54 am" src="https://user-images.githubusercontent.com/29146862/27140622-0464b48c-50f4-11e7-80d5-457e52071d17.png">
<img width="1329" alt="screen shot 2017-06-14 at 11 22 17 am" src="https://user-images.githubusercontent.com/29146862/27140621-0463aaf6-50f4-11e7-905e-7317780963b6.png">

**Comment by tomchop** [comment]
When you say

> After some digging i'm able to run the service yeti_web* just fine and am able to go to http://localhost:5000 to see the web gui. 

You mean when launching the webui from `$ ./yeti.py webserver`?

**Comment by JohnSmith94** [comment]
I can successfully run `./yeti.py webserver` and navigate to `localhost:5000` and that works.
Also can run the systemd for `yeti_web.service` and navigate to `localhost:5000` and that works.
The only one that doesn't work...that worked before the git pull is the `yeti_uwsgi.service `

**Comment by tomchop** [comment]
OK, so this seems to come from `yeti.py` where the statement `from core.web import webapp` is inside a function. Placing it back outside the function (e.g. on line 8) should fix the problem. A fix in master is under way.

**Comment by JohnSmith94** [comment]
Can confirm this worked for me. Thanks.
