### ISSUE TITLE
Observable Feeds Overwriting Instead of Updating

### ISSUE THREAD

**Issue by benmontour** [yeti-platform/yeti#947]
### Description
Running into an issue with observables brought in from the built in feeds are unable to be modified as they will just be replaced the next time the feed runs. 
Working through a project where I'm adding context or tags to some observables via enrichment from other sources, like geo-ip information for example. 
This all works great until the next time the feed runs and then the observable object appears to be overwritten with the source feed data, rather than just bringing down changes from the source.

### Environment

| Question                  | Answer
|---------------------------|--------------------
| Yeti release              | 2.0.4
| Yeti-frontend release     | latest

### Steps to Reproduce

Import observables via built in feed, like `blocklistdeSSH`. Add tags or context to said observable manually or via API. Rerun sync from source feed and check observables for your changes.

#### Expected behavior
The source feed should check for any delta since the last time the feed ran and update rather than overwrite any new data.

#### Actual behavior
The source feed is overwriting all local changes to an observable each time the feed runs, rather than only updating on the changes that have been made since it's last run.

**Comment by benmontour** [comment]
another place where this comes up is if an observable is brought in from multiple feeds. Only context from the last feed to run that included that observable is maintained. The information that an observable is present on multiple feeds is useful information in its own right. I'm not sure the right answer in this case, but would welcome some ideas.

**Comment by tomchop** [comment]
>  The information that an observable is present on multiple feeds is useful information in its own right. 

Absolutely, and this is how we intend things to be reflected in the db for sure. Observables that are brought in my multiple feeds should look something like:

```
"context": [
  {
    "source": "Feed1",
    "feed1_key": "blah"
  },
  {
    "source": "Feed2",
    "feed2_key": "foo"
  }
]
```

By default `add_context` tries to look for a context element with the same source as the one it's adding, and if found will do a comparison on some fields, and if all are identical, not overwrite results. You can also pass in a list of keys to ignore in that comparison (which is useful if your feed is providing a real-time "last-seen" element for example. Passing this will mean that the context from that feed will get updated instead of a new one appended)

**Comment by benmontour** [comment]
Just want to make sure I clarify as I may have made this seem like a context overwrite issue only. From what I'm seeing it appears that the entire observable object is being overwritten each time a feed runs, not just the context data contained within.

**Comment by tomchop** [comment]
Haven't had the change to repro today, but I'll definitely try tomorrow or over the weekend. Will keep this issue updated with findings. Thanks for clarifying!
