### ISSUE TITLE
Arangodb Core Dump 

### ISSUE THREAD

**Issue by ag100** [yeti-platform/yeti#948]
Hello,

It has been quite a while since I installed or used yeti, but went to install this morning and ran into some issues.

### Description
After installation, when starting the containers, yet-arangodb appears to crash.

~/yeti-docker/prod$ docker compose up
[+] Running 6/6
 ✔ Network yeti_network     Created                                                                                                                                                  0.1s
 ✔ Container yeti-redis     Created                                                                                                                                                  1.0s
 ✔ Container yeti-arangodb  Created                                                                                                                                                  1.1s
 ✔ Container yeti-api       Created                                                                                                                                                  0.9s
 ✔ Container yeti-tasks     Created                                                                                                                                                  1.1s
 ✔ Container yeti-frontend  Created                                                                                                                                                  1.1s
Attaching to yeti-api, yeti-arangodb, yeti-frontend, yeti-redis, yeti-tasks
yeti-arangodb  | Initializing root user...Hang on...
yeti-arangodb  | Initializing database...Hang on...
yeti-arangodb  | Illegal instruction (core dumped)

That error is followed by a bunch of:
yeti-redis     | 1:C 13 Dec 2023 15:45:35.995 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.

yeti-api       | WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f31a42f33a0>: Failed to establish a new connection: [Errno 111] Connection refused')': /_db/_system/_api/database
yeti-tasks     | WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa43d189e70>: Failed to establish a new connection: [Errno 111] Connection refused')': /_db/_system/_api/database

Then finally:

yeti-arangodb  | ArangoDB didn't start correctly during init
yeti-arangodb  | cat: can't open '/tmp/init-log': No such file or directory
yeti-arangodb exited with code 1

### Environment

| Question                  | Answer
|---------------------------|--------------------
| Yeti release              | 2.04 (latest from the git clone command)|
| OS version                | Ubuntu 22.04.2 LTS

### Steps to Reproduce

Followed instructions here:  https://yeti-platform.io/docs/getting-started/

#### Expected behavior
All containers should have started

#### Actual behavior
DB appears to crash.

Please let me know what additional information I can provide to help.  Thanks!

**Comment by sebdraven** [comment]
Hi !

You use Virtualbox ?

**Comment by ag100** [comment]
Hey!  No, but it is a client on a Proxmox server.  Thanks.

**Comment by sebdraven** [comment]
OK. You need tag arangodb version in docker

Take a look to this https://github.com/arangodb/arangodb/issues/16519

**Comment by ag100** [comment]
Awesome, thanks very much!  I'll take a look.

**Comment by ag100** [comment]
I'm a dope.  Changed the CPU type to host as it supports avx, and all is good.  Thanks for the help!
