### ISSUE TITLE
Using pyeti to pull down observables by feed

### ISSUE THREAD

**Issue by malogos** [yeti-platform/yeti#95]
### Description
I've been trying to interact with the yeti API, but am running into issues. My main use case is to pull down all existing observables in yeti for a given feed/context.source, but even basic queries are failing

No requests in pyeti (`y.observable_details(obs_id)`, `y.observable_search('tag=ransomware')`, etc) are working, and the errors returned are vague:

> <title>500 Internal Server Error</title>
> <h1>Internal Server Error</h1>
> <p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>

So I've been trying to see what works via direct URLs

`curl -H "X-API-KEY: my_api_key" http://yeti:5000/api/feed/` works
`curl -H "X-API-KEY: my_api_key" http://yeti:5000/api/feed/593f0e045a25c026f64ce799 `does not
`curl -H "X-API-KEY: my_api_key" http://yeti:5000/api/observable/594014d45a25c059f0a9e6db` does not

Same for /api/tag/

That's strange, because that's exactly what the documentation (http://yeti-platform.readthedocs.io/en/latest/api.html) says should be possible.

Are there examples for using pyeti observable_search() (especially with context.source)? Or maybe this is a setting that needs to be enabled for the yet server?

**Comment by tomchop** [comment]
This is not in the documentation (should be added!) but you need to pass an extra header for API calls: `Accept: application/json, */*` (that's what pyeti does https://github.com/yeti-platform/pyeti/blob/master/pyeti/api.py#L114)

The next step on our roadmap is to work on pyeti and produce concrete examples both for pyeti and curl-like HTTP usage of the API.

**Comment by gamelinux** [comment]
How I do it:
curl -s -XGET -H "Accept: application/json" -H "X-Api-Key: $APIKEY" http://localhost:5000/api/observable/594014d45a25c059f0a9e6db

**Comment by tomchop** [comment]
We have been working on pyeti with some examples for you to try out! We're still working on curl examples. In the meantime, I'm closing this out.
