### ISSUE TITLE
uWSGI stopped working after git pull

### ISSUE THREAD

**Issue by mshelton** [yeti-platform/yeti#99]
### Description
We are no longer able to connect to Yeti after a recent 'git pull'.  When we connect to Nginx and are forwarded to uWSGI, we get an "Internal Server Error".  We can start Yeti in Flask and it will work just fine.

In the logs, uWSGI starts with the following error:  **unable to load app 0 (mountpoint='') (callable not found or import error)**

How would I troubleshoot this error?

---------------
Jun 15 15:14:01 [redacted] uwsgi[2038]: *** Starting uWSGI 2.0.15 (64bit) on [Thu Jun 15 15:14:01 2017] ***
Jun 15 15:14:01 [redacted] uwsgi[2038]: compiled with version: 5.4.0 20160609 on 12 April 2017 09:13:59
Jun 15 15:14:01 [redacted] uwsgi[2038]: os: Linux-4.4.0-79-generic #100-Ubuntu SMP Wed May 17 19:58:14 UTC 2017
Jun 15 15:14:01 [redacted] uwsgi[2038]: nodename: [redacted]
Jun 15 15:14:01 [redacted] uwsgi[2038]: machine: x86_64
Jun 15 15:14:01 [redacted] uwsgi[2038]: clock source: unix
Jun 15 15:14:01 [redacted] uwsgi[2038]: detected number of CPU cores: 1
Jun 15 15:14:01 [redacted] uwsgi[2038]: current working directory: /opt/yeti
Jun 15 15:14:01 [redacted] uwsgi[2038]: detected binary path: /usr/local/bin/uwsgi
Jun 15 15:14:01 [redacted] uwsgi[2038]: !!! no internal routing support, rebuild with pcre support !!!
Jun 15 15:14:01 [redacted] uwsgi[2038]: your processes number limit is 64039
Jun 15 15:14:01 [redacted] uwsgi[2038]: your memory page size is 4096 bytes
Jun 15 15:14:01 [redacted] uwsgi[2038]: detected max file descriptor number: 1024
Jun 15 15:14:01 [redacted] uwsgi[2038]: lock engine: pthread robust mutexes
Jun 15 15:14:01 [redacted] uwsgi[2038]: thunder lock: disabled (you can enable it with --thunder-lock)
Jun 15 15:14:01 [redacted] uwsgi[2038]: uwsgi socket 0 bound to TCP address 127.0.0.1:8000 fd 4
Jun 15 15:14:01 [redacted] uwsgi[2038]: Python version: 2.7.12 (default, Nov 19 2016, 06:48:10)  [GCC 5.4.0 20160609]
Jun 15 15:14:01 [redacted] uwsgi[2038]: Python main interpreter initialized at 0x15f3190
Jun 15 15:14:01 [redacted] uwsgi[2038]: python threads support enabled
Jun 15 15:14:01 [redacted] uwsgi[2038]: your server socket listen backlog is limited to 100 connections
Jun 15 15:14:01 [redacted] uwsgi[2038]: your mercy for graceful operations on workers is 60 seconds
Jun 15 15:14:01 [redacted] uwsgi[2038]: mapped 415280 bytes (405 KB) for 8 cores
Jun 15 15:14:01 [redacted] uwsgi[2038]: *** Operational MODE: preforking+threaded ***
**Jun 15 15:14:01 [redacted] uwsgi[2038]: unable to load app 0 (mountpoint='') (callable not found or import error)**
Jun 15 15:14:01 [redacted] uwsgi[2038]: *** no app loaded. going in full dynamic mode ***
Jun 15 15:14:01 [redacted] uwsgi[2038]: *** uWSGI is running in multiple interpreter mode ***
Jun 15 15:14:01 [redacted] uwsgi[2038]: spawned uWSGI master process (pid: 2038)
Jun 15 15:14:01 [redacted] systemd[1]: Started Yeti UWSGI server.
Jun 15 15:14:01 [redacted] uwsgi[2038]: spawned uWSGI worker 1 (pid: 2042, cores: 2)
Jun 15 15:14:01 [redacted] uwsgi[2038]: spawned uWSGI worker 2 (pid: 2043, cores: 2)
Jun 15 15:14:01 [redacted] uwsgi[2038]: spawned uWSGI worker 3 (pid: 2044, cores: 2)
Jun 15 15:14:01 [redacted] uwsgi[2038]: spawned uWSGI worker 4 (pid: 2045, cores: 2)
Jun 15 15:14:01 [redacted] uwsgi[2038]: *** Stats server enabled on 127.0.0.1:9191 fd: 16 ***

### Environment

| Question         | Answer
|------------------|--------------------
| Git commit       | 83b9d23370c13f29ae730da0d4632dfdd61d7aac
| OS version       | Ubuntu 16.04
| Browser          | Chrome 56.0.2924.87

**Comment by gaelmuller** [comment]
The solution was discussed here: https://github.com/yeti-platform/yeti/issues/94.
